package com.sony.songpal.mdr.j2objc.actionlog.param;

public enum Dialog {
  ACCOUNT_SETTINGS_BACKUP_CHECK_SERVER_ERROR,
  ACCOUNT_SETTINGS_BACKUP_FAILED,
  ACCOUNT_SETTINGS_BACKUP_RESTORE,
  ACCOUNT_SETTINGS_INITIALIZE_NETWORK_ERROR,
  ACCOUNT_SETTINGS_INITIALIZE_RESIGN_IN_ERROR,
  ACCOUNT_SETTINGS_INITIALIZE_SERVER_ERROR,
  ACCOUNT_SETTINGS_NO_DATA_TO_RESTORE,
  ACCOUNT_SETTINGS_RESTORE_FAILED,
  ACCOUNT_SETTINGS_SIGN_IN_PAGE_SIGN_IN_FAILED,
  ACCOUNT_SETTINGS_TOKEN_SERVER_ERROR,
  ACCOUNT_SETTINGS_TOKEN_SIGN_IN_FAILED,
  AMAZON_ALEXA_INSTALL_CONFIRMATION,
  AMB_SOUND_CONTROL_MODE_SELECT_DESCRIPTION,
  APP_UPDATE_CONFIRMATION_BEFORE_FW_UPDATE,
  ASC_SELECT_APPLYING_TARGET_SETTING,
  ASC_UNREGISTER_PLACE_CONFIRMATION,
  BATTERY_CONSUMPTION_INCREASE_CONFIRMATION,
  BOTTOM_SHEET,
  BT_ON,
  CAMERA_PERMISSION_POST_EXPLANATION_DIALOG,
  CAUTION_DUAL_ASSIGNMENT,
  CAUTION_GPS,
  CAUTION_LOCATION,
  CAUTION_PLAYBACK_CONTROL_DUAL_ASSIGNMENT,
  CHANGE_VA_TO_ALEXA_CONFIRMATION,
  CHANGE_VA_TO_OTHER_CONFIRMATION,
  CHANGE_VOICE_ASSISTANT_BTN_WITH_LR_SELECT_CONFIRMATION,
  CHANGE_VOICE_ASSISTANT_CONFIRMATION,
  CHANGE_VOICE_ASSISTANT_PANEL_CONFIRMATION,
  CHANGE_VOICE_ASSISTANT_SENSOR_WITH_LR_SELECT_CONFIRMATION,
  CRADLE_BATTERY_ACTIVATE,
  CRADLE_BATTERY_INFO,
  DEVICE_PAIRING,
  DISABLE_TOUCH_PANEL_AND_RECONNECTION_CONFIRMATION,
  DISABLE_TOUCH_PANEL_CONFIRMATION,
  ENABLE_TOUCH_PANEL_AND_RECONNECTION_CONFIRMATION,
  ENABLE_TOUCH_PANEL_CONFIRMATION,
  ESA_ABS_ERROR_CANNOTEXECUTE,
  ESA_ABS_ERROR_NOTCONNECTED_LEFT,
  ESA_ABS_ERROR_NOTCONNECTED_RIGHT,
  ESA_ABS_ERROR_NOTWEARING_BOTH,
  ESA_ABS_ERROR_NOTWEARING_LEFT,
  ESA_ABS_ERROR_NOTWEARING_RIGHT,
  ESA_INFORMATION,
  ESA_RELATIVE_ERROR_CANNOTEXECUTE,
  ESA_RELATIVE_ERROR_NOTCONNECTED_LEFT,
  ESA_RELATIVE_ERROR_NOTCONNECTED_RIGHT,
  ESA_RELATIVE_ERROR_NOTWEARING_BOTH,
  ESA_RELATIVE_ERROR_NOTWEARING_LEFT,
  ESA_RELATIVE_ERROR_NOTWEARING_RIGHT,
  FEEDBACK_INFO,
  FW_ABORT_CONFIRMATION,
  FW_ABORT_CONFIRMATION_BEFORE_MULTIPOINT_CONNECT_HISTORY_DEVICE,
  FW_ABORT_CONFIRMATION_BEFORE_MULTIPOINT_PAIRING,
  FW_DATA_ERROR,
  FW_DOWNLOAD_ERROR,
  FW_INSTALL_ERROR,
  FW_MDR_BATTERY_POWER,
  FW_MDR_L_CONNECTION_ERROR,
  FW_MDR_R_CONNECTION_ERROR,
  FW_MOBILE_BATTERY_POWER,
  FW_NETWORK_ERROR,
  FW_TRANSFER_ERROR,
  FW_UPDATE_COMPLETION,
  FW_UPDATE_CONFIRM_COMPLETION,
  FW_UPDATE_RECOMMENDATION,
  GOOGLE_ASSISTANT_INTRODUCTION,
  GPS_ON,
  IA_ALREADY_SAVED_HRTF,
  IA_CAMERA_MANUAL_CONFIRM,
  IA_COUPON_DIALOG,
  IA_DOUBLE_EFFECT_FLOW_CONFIRM,
  IA_DOUBLE_EFFECT_SPC_CAUTION,
  IA_DOUBLE_EFFECT_TRIAL_LISTENING_CONFIRM,
  IA_DOUBLE_EFFECT_VPT_CAUTION,
  IA_GDPR_NOTICE,
  IA_HOW_TO_USE_EAR_IMAGES_NOTICE,
  IA_HRTF_CREATION_ERROR,
  IA_HRTF_DOWNLOAD_ERROR,
  IA_HRTF_UPLOAD_ERROR,
  IA_INSTALL_CONFIRM,
  IA_NO_HRTF_DATA_MANUAL,
  IA_NO_HRTF_DATA_TIMEOUT,
  IA_OPEN_STORE_CONFIRMATION,
  IA_PRIVACY_POLICY_NOTICE,
  IA_SAMPLE_PLAYBACK_PASSIVE_WARNING,
  IA_SAMPLE_PLAYBACK_WARNING,
  IA_SETUP_SKIP_CONFIRMATION,
  IA_STEP_GDPR_NOTICE,
  IA_VOICE_GUIDE_NOTICE,
  INFORMATION,
  LOCATION_BACKGROUND_PERMISSION_POST_EXPLANATION_DIALOG,
  LOCATION_FOREGROUND_PERMISSION_POST_EXPLANATION_DIALOG,
  MULTIPOINT_ADD_DEVICE_CAUTION_MAXIMUM_DEVICE,
  MULTIPOINT_CONNECT_DEVICE_CAUTION_MAXIMUM_DEVICE,
  MULTIPOINT_CONNECT_ERROR,
  MULTIPOINT_DELETE_CONNECTED_DEVICE,
  MULTIPOINT_DELETE_DEVICE_ERROR,
  MULTIPOINT_DELETE_HISTORY_DEVICE,
  MULTIPOINT_DISCONNECT_CONFIRMATION_BEFORE_FW_UPDATE,
  MULTIPOINT_DISCONNECT_CONFIRMATION_BEFORE_VOICE_GUIDANCE,
  MULTIPOINT_DISCONNECT_DEVICE,
  MULTIPOINT_DISCONNECT_DEVICE_ERROR,
  MULTIPOINT_DISCONNECT_OWN_DEVICE,
  MULTIPOINT_ENTER_PAIRING_MODE_ERROR,
  MULTIPOINT_PAIRING_CANCEL,
  MULTIPOINT_PAIRING_ERROR,
  MULTIPOINT_PAIRING_SUCCESS,
  MULTI_POINT_SETTING_DISABLE_CONFIRMATION,
  MULTI_POINT_SETTING_ENABLE_CONFIRMATION,
  MULTI_POINT_SETTING_INFO,
  OTHER,
  OTHER_INFO,
  PERMISSION_LOCATION,
  QUESTIONNAIRE,
  QUESTIONNAIRE_HOW_TO_DISPLAY,
  QUESTIONNAIRE_NOT_EXIST,
  RESET_SETTINGS_CONFIRM_FACTORY_RESET,
  RESET_SETTINGS_CONFIRM_RESET,
  RESET_SETTINGS_CONFIRM_RESET_APPLICATION,
  RESET_SETTINGS_FAILED_L_CONNECTION,
  RESET_SETTINGS_FAILED_L_HEADPHONE,
  RESET_SETTINGS_FAILED_R_CONNECTION,
  RESET_SETTINGS_FAILED_R_HEADPHONE,
  RESET_SETTINGS_SUCCEEDED,
  TALKING_MODE_CONFIRMATION_AFTER_TRIAL,
  TALKING_MODE_DESCRIPTION,
  TALKING_MODE_DESCRIPTION_FOR_ENABLE_FIRST_TIME,
  TALKING_MODE_TURN_ON_CONFIRMATION,
  UNKNOWN("unknown"),
  VA_BTN_DISABLE_AND_RECONNECTION_CONFIRMATION("unknown"),
  VA_BTN_DISABLE_CONFIRMATION("unknown"),
  VA_BTN_ENABLE_AND_RECONNECTION_CONFIRMATION("unknown"),
  VA_BTN_ENABLE_CONFIRMATION("unknown"),
  VA_SENSOR_DISABLE_AND_RECONNECTION_CONFIRMATION("unknown"),
  VA_SENSOR_DISABLE_CONFIRMATION("unknown"),
  VA_SENSOR_ENABLE_AND_RECONNECTION_CONFIRMATION("unknown"),
  VA_SENSOR_ENABLE_CONFIRMATION("unknown"),
  VOICE_ASSISTANT_BTN_INFORMATION("unknown"),
  VOICE_ASSISTANT_INTRODUCTION("unknown"),
  VOICE_ASSISTANT_PANEL_INFORMATION("unknown"),
  VOICE_ASSISTANT_SENSOR_INFORMATION("unknown"),
  VOICE_DATA_DISCARD_FW_UPDATE("unknown"),
  VOICE_DATA_DOWNLOAD_ERROR("unknown"),
  VOICE_DATA_INSTALL_ERROR("unknown"),
  VOICE_DATA_MDR_BATTERY_POWER("unknown"),
  VOICE_DATA_MDR_L_CONNECTION_ERROR("unknown"),
  VOICE_DATA_MDR_R_CONNECTION_ERROR("unknown"),
  VOICE_DATA_MOBILE_BATTERY_POWER("unknown"),
  VOICE_DATA_TRANSFER_ERROR("unknown");
  
  private final String mStrValue;
  
  static {
    OTHER = new Dialog("OTHER", 1, "other");
    BT_ON = new Dialog("BT_ON", 2, "btOn");
    CAUTION_LOCATION = new Dialog("CAUTION_LOCATION", 3, "cautionLocation");
    PERMISSION_LOCATION = new Dialog("PERMISSION_LOCATION", 4, "permissionLocation");
    CAUTION_GPS = new Dialog("CAUTION_GPS", 5, "cautionGps");
    GPS_ON = new Dialog("GPS_ON", 6, "gpsOn");
    DEVICE_PAIRING = new Dialog("DEVICE_PAIRING", 7, "devicePairing");
    VOICE_DATA_MDR_BATTERY_POWER = new Dialog("VOICE_DATA_MDR_BATTERY_POWER", 8, "voiceDataMdrBatteryPower");
    VOICE_DATA_MOBILE_BATTERY_POWER = new Dialog("VOICE_DATA_MOBILE_BATTERY_POWER", 9, "voiceDataMobileBatteryPower");
    VOICE_DATA_DOWNLOAD_ERROR = new Dialog("VOICE_DATA_DOWNLOAD_ERROR", 10, "voiceDataDownloadError");
    VOICE_DATA_TRANSFER_ERROR = new Dialog("VOICE_DATA_TRANSFER_ERROR", 11, "voiceDataTransferError");
    VOICE_DATA_INSTALL_ERROR = new Dialog("VOICE_DATA_INSTALL_ERROR", 12, "voiceDataInstallError");
    VOICE_DATA_DISCARD_FW_UPDATE = new Dialog("VOICE_DATA_DISCARD_FW_UPDATE", 13, "voiceDataDiscardFw");
    GOOGLE_ASSISTANT_INTRODUCTION = new Dialog("GOOGLE_ASSISTANT_INTRODUCTION", 14, "googleAssistantIntroduction");
    FW_UPDATE_RECOMMENDATION = new Dialog("FW_UPDATE_RECOMMENDATION", 15, "fwUpdateRecommendation");
    FW_MDR_BATTERY_POWER = new Dialog("FW_MDR_BATTERY_POWER", 16, "fwMdrBatteryPower");
    FW_MOBILE_BATTERY_POWER = new Dialog("FW_MOBILE_BATTERY_POWER", 17, "fwMobileBatteryPower");
    FW_NETWORK_ERROR = new Dialog("FW_NETWORK_ERROR", 18, "fwNetworkError");
    FW_MDR_L_CONNECTION_ERROR = new Dialog("FW_MDR_L_CONNECTION_ERROR", 19, "fwMdrLConnectionError");
    FW_MDR_R_CONNECTION_ERROR = new Dialog("FW_MDR_R_CONNECTION_ERROR", 20, "fwMdrRConnectionError");
    FW_DATA_ERROR = new Dialog("FW_DATA_ERROR", 21, "fwDataError");
    FW_DOWNLOAD_ERROR = new Dialog("FW_DOWNLOAD_ERROR", 22, "fwDownloadError");
    FW_TRANSFER_ERROR = new Dialog("FW_TRANSFER_ERROR", 23, "fwTransferError");
    FW_INSTALL_ERROR = new Dialog("FW_INSTALL_ERROR", 24, "fwInstallError");
    FW_ABORT_CONFIRMATION = new Dialog("FW_ABORT_CONFIRMATION", 25, "fwAbortConfirmation");
    FW_UPDATE_COMPLETION = new Dialog("FW_UPDATE_COMPLETION", 26, "fwUpdateCompletion");
    FW_UPDATE_CONFIRM_COMPLETION = new Dialog("FW_UPDATE_CONFIRM_COMPLETION", 27, "fwUpdateConfirmCompletion");
    VOICE_DATA_MDR_L_CONNECTION_ERROR = new Dialog("VOICE_DATA_MDR_L_CONNECTION_ERROR", 28, "voiceDataMdrLConnectionError");
    VOICE_DATA_MDR_R_CONNECTION_ERROR = new Dialog("VOICE_DATA_MDR_R_CONNECTION_ERROR", 29, "voiceDataMdrRConnectionError");
    IA_SETUP_SKIP_CONFIRMATION = new Dialog("IA_SETUP_SKIP_CONFIRMATION", 30, "iaSetupSkipConfirmation");
    IA_SAMPLE_PLAYBACK_WARNING = new Dialog("IA_SAMPLE_PLAYBACK_WARNING", 31, "iaSamplePlaybackWarning");
    IA_SAMPLE_PLAYBACK_PASSIVE_WARNING = new Dialog("IA_SAMPLE_PLAYBACK_PASSIVE_WARNING", 32, "iaSamplePlaybackPassiveWarning");
    IA_OPEN_STORE_CONFIRMATION = new Dialog("IA_OPEN_STORE_CONFIRMATION", 33, "iaOpenStoreConfirmation");
    IA_HOW_TO_USE_EAR_IMAGES_NOTICE = new Dialog("IA_HOW_TO_USE_EAR_IMAGES_NOTICE", 34, "iaHowToUseEarImagesNotice");
    IA_PRIVACY_POLICY_NOTICE = new Dialog("IA_PRIVACY_POLICY_NOTICE", 35, "iaPrivacyPolicyNotice");
    IA_GDPR_NOTICE = new Dialog("IA_GDPR_NOTICE", 36, "iaGdprNotice");
    IA_VOICE_GUIDE_NOTICE = new Dialog("IA_VOICE_GUIDE_NOTICE", 37, "iaVoiceGuideNotice");
    IA_HRTF_CREATION_ERROR = new Dialog("IA_HRTF_CREATION_ERROR", 38, "iaHrtfCreationError");
    IA_HRTF_UPLOAD_ERROR = new Dialog("IA_HRTF_UPLOAD_ERROR", 39, "iaHrtfUploadError");
    IA_INSTALL_CONFIRM = new Dialog("IA_INSTALL_CONFIRM", 40, "IaInstallConfirm");
    IA_STEP_GDPR_NOTICE = new Dialog("IA_STEP_GDPR_NOTICE", 41, "IaStepGdprNotice");
    IA_CAMERA_MANUAL_CONFIRM = new Dialog("IA_CAMERA_MANUAL_CONFIRM", 42, "IaCameraManualConfirm");
    IA_DOUBLE_EFFECT_FLOW_CONFIRM = new Dialog("IA_DOUBLE_EFFECT_FLOW_CONFIRM", 43, "IaDoubleEffectFlowConfirm");
    IA_DOUBLE_EFFECT_TRIAL_LISTENING_CONFIRM = new Dialog("IA_DOUBLE_EFFECT_TRIAL_LISTENING_CONFIRM", 44, "IaDoubleEffectTrialListeningConfirm");
    IA_DOUBLE_EFFECT_SPC_CAUTION = new Dialog("IA_DOUBLE_EFFECT_SPC_CAUTION", 45, "IaDoubleEffectSpcCaution");
    IA_DOUBLE_EFFECT_VPT_CAUTION = new Dialog("IA_DOUBLE_EFFECT_VPT_CAUTION", 46, "IaDoubleEffectVptCaution");
    IA_COUPON_DIALOG = new Dialog("IA_COUPON_DIALOG", 47, "IaCouponDialog");
    IA_ALREADY_SAVED_HRTF = new Dialog("IA_ALREADY_SAVED_HRTF", 48, "iaAlreadySavedHrtf");
    IA_HRTF_DOWNLOAD_ERROR = new Dialog("IA_HRTF_DOWNLOAD_ERROR", 49, "iaHrtfDownloadError");
    IA_NO_HRTF_DATA_TIMEOUT = new Dialog("IA_NO_HRTF_DATA_TIMEOUT", 50, "iaNoHrtfDataTimeout");
    IA_NO_HRTF_DATA_MANUAL = new Dialog("IA_NO_HRTF_DATA_MANUAL", 51, "iaNoHrtfDataManual");
    CRADLE_BATTERY_ACTIVATE = new Dialog("CRADLE_BATTERY_ACTIVATE", 52, "cradleBatteryActivate");
    CRADLE_BATTERY_INFO = new Dialog("CRADLE_BATTERY_INFO", 53, "cradleBatteryInfo");
    CAUTION_DUAL_ASSIGNMENT = new Dialog("CAUTION_DUAL_ASSIGNMENT", 54, "cautionDualAssignment");
    QUESTIONNAIRE = new Dialog("QUESTIONNAIRE", 55, "questionnaire");
    QUESTIONNAIRE_HOW_TO_DISPLAY = new Dialog("QUESTIONNAIRE_HOW_TO_DISPLAY", 56, "questionnaireHowToDisplay");
    QUESTIONNAIRE_NOT_EXIST = new Dialog("QUESTIONNAIRE_NOT_EXIST", 57, "questionnaireNotExistDialog");
    TALKING_MODE_DESCRIPTION = new Dialog("TALKING_MODE_DESCRIPTION", 58, "talkingModeDescription");
    TALKING_MODE_DESCRIPTION_FOR_ENABLE_FIRST_TIME = new Dialog("TALKING_MODE_DESCRIPTION_FOR_ENABLE_FIRST_TIME", 59, "talkingModeDescriptionForEnableFirstTime");
    TALKING_MODE_CONFIRMATION_AFTER_TRIAL = new Dialog("TALKING_MODE_CONFIRMATION_AFTER_TRIAL", 60, "talkingModeConfirmationAfterTrial");
    TALKING_MODE_TURN_ON_CONFIRMATION = new Dialog("TALKING_MODE_TURN_ON_CONFIRMATION", 61, "talkingModeTurnOnConfirmation");
    BOTTOM_SHEET = new Dialog("BOTTOM_SHEET", 62, "bottomSheet");
    MULTI_POINT_SETTING_INFO = new Dialog("MULTI_POINT_SETTING_INFO", 63, "multipointSettingInfo");
    MULTI_POINT_SETTING_ENABLE_CONFIRMATION = new Dialog("MULTI_POINT_SETTING_ENABLE_CONFIRMATION", 64, "multipointSettingEnableConfirmation");
    MULTI_POINT_SETTING_DISABLE_CONFIRMATION = new Dialog("MULTI_POINT_SETTING_DISABLE_CONFIRMATION", 65, "multipointSettingDisableConfirmation");
    MULTIPOINT_ADD_DEVICE_CAUTION_MAXIMUM_DEVICE = new Dialog("MULTIPOINT_ADD_DEVICE_CAUTION_MAXIMUM_DEVICE", 66, "multipointAddDeviceCautionMaximumDevice");
    MULTIPOINT_ENTER_PAIRING_MODE_ERROR = new Dialog("MULTIPOINT_ENTER_PAIRING_MODE_ERROR", 67, "multipointEnterPairingModeError");
    MULTIPOINT_PAIRING_CANCEL = new Dialog("MULTIPOINT_PAIRING_CANCEL", 68, "multipointPairingCancel");
    MULTIPOINT_PAIRING_ERROR = new Dialog("MULTIPOINT_PAIRING_ERROR", 69, "multipointPairingError");
    MULTIPOINT_PAIRING_SUCCESS = new Dialog("MULTIPOINT_PAIRING_SUCCESS", 70, "multipointPairingSuccess");
    MULTIPOINT_DELETE_CONNECTED_DEVICE = new Dialog("MULTIPOINT_DELETE_CONNECTED_DEVICE", 71, "multipointDeleteConnectedDevice");
    MULTIPOINT_DELETE_HISTORY_DEVICE = new Dialog("MULTIPOINT_DELETE_HISTORY_DEVICE", 72, "multipointDeleteHistoryDevice");
    MULTIPOINT_DELETE_DEVICE_ERROR = new Dialog("MULTIPOINT_DELETE_DEVICE_ERROR", 73, "multipointDeleteDeviceError");
    MULTIPOINT_CONNECT_DEVICE_CAUTION_MAXIMUM_DEVICE = new Dialog("MULTIPOINT_CONNECT_DEVICE_CAUTION_MAXIMUM_DEVICE", 74, "multipointConnectDeviceCautionMaximumDevice");
    MULTIPOINT_CONNECT_ERROR = new Dialog("MULTIPOINT_CONNECT_ERROR", 75, "multipointConnectError");
    MULTIPOINT_DISCONNECT_OWN_DEVICE = new Dialog("MULTIPOINT_DISCONNECT_OWN_DEVICE", 76, "multipointDisconnectOwnDevice");
    MULTIPOINT_DISCONNECT_DEVICE = new Dialog("MULTIPOINT_DISCONNECT_DEVICE", 77, "multipointDisconnectDevice");
    MULTIPOINT_DISCONNECT_DEVICE_ERROR = new Dialog("MULTIPOINT_DISCONNECT_DEVICE_ERROR", 78, "multipointDisconnectDeviceError");
    MULTIPOINT_DISCONNECT_CONFIRMATION_BEFORE_FW_UPDATE = new Dialog("MULTIPOINT_DISCONNECT_CONFIRMATION_BEFORE_FW_UPDATE", 79, "multipointDisconnectConfirmationBeforeFwUpdate");
    MULTIPOINT_DISCONNECT_CONFIRMATION_BEFORE_VOICE_GUIDANCE = new Dialog("MULTIPOINT_DISCONNECT_CONFIRMATION_BEFORE_VOICE_GUIDANCE", 80, "multipointDisconnectConfirmationBeforeVoiceGuidance");
    FW_ABORT_CONFIRMATION_BEFORE_MULTIPOINT_PAIRING = new Dialog("FW_ABORT_CONFIRMATION_BEFORE_MULTIPOINT_PAIRING", 81, "fwAbortConfirmationBeforeMultipointParing");
    FW_ABORT_CONFIRMATION_BEFORE_MULTIPOINT_CONNECT_HISTORY_DEVICE = new Dialog("FW_ABORT_CONFIRMATION_BEFORE_MULTIPOINT_CONNECT_HISTORY_DEVICE", 82, "fwAbortConfirmationBeforeMultipointConnectHistoryDevice");
    APP_UPDATE_CONFIRMATION_BEFORE_FW_UPDATE = new Dialog("APP_UPDATE_CONFIRMATION_BEFORE_FW_UPDATE", 83, "appUpdateConfirmationBeforeFwUpdate");
    ASC_SELECT_APPLYING_TARGET_SETTING = new Dialog("ASC_SELECT_APPLYING_TARGET_SETTING", 84, "ascSelectApplyingTargetSetting");
    ASC_UNREGISTER_PLACE_CONFIRMATION = new Dialog("ASC_UNREGISTER_PLACE_CONFIRMATION", 85, "ascUnregisterPlaceConfirmation");
    ACCOUNT_SETTINGS_INITIALIZE_NETWORK_ERROR = new Dialog("ACCOUNT_SETTINGS_INITIALIZE_NETWORK_ERROR", 86, "accountSettingsInitializeNetworkError");
    ACCOUNT_SETTINGS_INITIALIZE_RESIGN_IN_ERROR = new Dialog("ACCOUNT_SETTINGS_INITIALIZE_RESIGN_IN_ERROR", 87, "accountSettingsInitializeResignInError");
    ACCOUNT_SETTINGS_INITIALIZE_SERVER_ERROR = new Dialog("ACCOUNT_SETTINGS_INITIALIZE_SERVER_ERROR", 88, "accountSettingsInitializeServerError");
    ACCOUNT_SETTINGS_SIGN_IN_PAGE_SIGN_IN_FAILED = new Dialog("ACCOUNT_SETTINGS_SIGN_IN_PAGE_SIGN_IN_FAILED", 89, "accountSettingsSignInPageSignInFailed");
    ACCOUNT_SETTINGS_TOKEN_SIGN_IN_FAILED = new Dialog("ACCOUNT_SETTINGS_TOKEN_SIGN_IN_FAILED", 90, "accountSettingsTokenSignInFailed");
    ACCOUNT_SETTINGS_TOKEN_SERVER_ERROR = new Dialog("ACCOUNT_SETTINGS_TOKEN_SERVER_ERROR", 91, "accountSettingsTokenServerError");
    ACCOUNT_SETTINGS_BACKUP_RESTORE = new Dialog("ACCOUNT_SETTINGS_BACKUP_RESTORE", 92, "accountSettingsBackupRestore");
    ACCOUNT_SETTINGS_BACKUP_FAILED = new Dialog("ACCOUNT_SETTINGS_BACKUP_FAILED", 93, "accountSettingsBackupFailed");
    ACCOUNT_SETTINGS_RESTORE_FAILED = new Dialog("ACCOUNT_SETTINGS_RESTORE_FAILED", 94, "accountSettingsRestoreFailed");
    ACCOUNT_SETTINGS_BACKUP_CHECK_SERVER_ERROR = new Dialog("ACCOUNT_SETTINGS_BACKUP_CHECK_SERVER_ERROR", 95, "accountSettingsBackupCheckServerError");
    ACCOUNT_SETTINGS_NO_DATA_TO_RESTORE = new Dialog("ACCOUNT_SETTINGS_NO_DATA_TO_RESTORE", 96, "accountSettingsNoDataToRestore");
    BATTERY_CONSUMPTION_INCREASE_CONFIRMATION = new Dialog("BATTERY_CONSUMPTION_INCREASE_CONFIRMATION", 97, "batteryConsumptionIncreaseConfirmation");
    INFORMATION = new Dialog("INFORMATION", 98, "information");
    FEEDBACK_INFO = new Dialog("FEEDBACK_INFO", 99, "feedbackInfo");
    OTHER_INFO = new Dialog("OTHER_INFO", 100, "otherInfo");
    CHANGE_VOICE_ASSISTANT_CONFIRMATION = new Dialog("CHANGE_VOICE_ASSISTANT_CONFIRMATION", 101, "changeVoiceAssistantConfirmation");
    CHANGE_VOICE_ASSISTANT_PANEL_CONFIRMATION = new Dialog("CHANGE_VOICE_ASSISTANT_PANEL_CONFIRMATION", 102, "changeVoiceAssistantPanelConfirmation");
    CHANGE_VOICE_ASSISTANT_BTN_WITH_LR_SELECT_CONFIRMATION = new Dialog("CHANGE_VOICE_ASSISTANT_BTN_WITH_LR_SELECT_CONFIRMATION", 103, "changeVoiceAssistantBtnWithLrSelectConfirmation");
    CHANGE_VOICE_ASSISTANT_SENSOR_WITH_LR_SELECT_CONFIRMATION = new Dialog("CHANGE_VOICE_ASSISTANT_SENSOR_WITH_LR_SELECT_CONFIRMATION", 104, "changeVoiceAssistantSensorWithLrSelectConfirmation");
    VOICE_ASSISTANT_PANEL_INFORMATION = new Dialog("VOICE_ASSISTANT_PANEL_INFORMATION", 105, "voiceAssistantPanelInformation");
    VOICE_ASSISTANT_SENSOR_INFORMATION = new Dialog("VOICE_ASSISTANT_SENSOR_INFORMATION", 106, "voiceAssistantSensorInformation");
    VOICE_ASSISTANT_BTN_INFORMATION = new Dialog("VOICE_ASSISTANT_BTN_INFORMATION", 107, "voiceAssistantBtnInformation");
    VA_SENSOR_DISABLE_AND_RECONNECTION_CONFIRMATION = new Dialog("VA_SENSOR_DISABLE_AND_RECONNECTION_CONFIRMATION", 108, "vaSensorDisableAndReconnectionConfirmation");
    VA_SENSOR_ENABLE_AND_RECONNECTION_CONFIRMATION = new Dialog("VA_SENSOR_ENABLE_AND_RECONNECTION_CONFIRMATION", 109, "vaSensorEnableAndReconnectionConfirmation");
    VA_BTN_DISABLE_AND_RECONNECTION_CONFIRMATION = new Dialog("VA_BTN_DISABLE_AND_RECONNECTION_CONFIRMATION", 110, "vaBtnDisableAndReconnectionConfirmation");
    VA_BTN_ENABLE_AND_RECONNECTION_CONFIRMATION = new Dialog("VA_BTN_ENABLE_AND_RECONNECTION_CONFIRMATION", 111, "vaBtnEnableAndReconnectionConfirmation");
    VA_SENSOR_DISABLE_CONFIRMATION = new Dialog("VA_SENSOR_DISABLE_CONFIRMATION", 112, "vaSensorDisableConfirmation");
    VA_SENSOR_ENABLE_CONFIRMATION = new Dialog("VA_SENSOR_ENABLE_CONFIRMATION", 113, "vaSensorEnableConfirmation");
    VA_BTN_DISABLE_CONFIRMATION = new Dialog("VA_BTN_DISABLE_CONFIRMATION", 114, "vaBtnDisableConfirmation");
    VA_BTN_ENABLE_CONFIRMATION = new Dialog("VA_BTN_ENABLE_CONFIRMATION", 115, "vaBtnEnableConfirmation");
    CAUTION_PLAYBACK_CONTROL_DUAL_ASSIGNMENT = new Dialog("CAUTION_PLAYBACK_CONTROL_DUAL_ASSIGNMENT", 116, "cautionPlaybackControlDualAssignment");
    DISABLE_TOUCH_PANEL_CONFIRMATION = new Dialog("DISABLE_TOUCH_PANEL_CONFIRMATION", 117, "disableTouchPanelConfirmation");
    ENABLE_TOUCH_PANEL_CONFIRMATION = new Dialog("ENABLE_TOUCH_PANEL_CONFIRMATION", 118, "enableTouchPanelConfirmation");
    DISABLE_TOUCH_PANEL_AND_RECONNECTION_CONFIRMATION = new Dialog("DISABLE_TOUCH_PANEL_AND_RECONNECTION_CONFIRMATION", 119, "disableTouchPanelAndReconnectionConfirmation");
    ENABLE_TOUCH_PANEL_AND_RECONNECTION_CONFIRMATION = new Dialog("ENABLE_TOUCH_PANEL_AND_RECONNECTION_CONFIRMATION", 120, "enableTouchPanelAndReconnectionConfirmation");
    LOCATION_FOREGROUND_PERMISSION_POST_EXPLANATION_DIALOG = new Dialog("LOCATION_FOREGROUND_PERMISSION_POST_EXPLANATION_DIALOG", 121, "locationForegroundPermissionPostExplanationDialog");
    LOCATION_BACKGROUND_PERMISSION_POST_EXPLANATION_DIALOG = new Dialog("LOCATION_BACKGROUND_PERMISSION_POST_EXPLANATION_DIALOG", 122, "locationBackgroundPermissionPostExplanationDialog");
    CAMERA_PERMISSION_POST_EXPLANATION_DIALOG = new Dialog("CAMERA_PERMISSION_POST_EXPLANATION_DIALOG", 123, "cameraPermissionPostExplanationDialog");
    AMB_SOUND_CONTROL_MODE_SELECT_DESCRIPTION = new Dialog("AMB_SOUND_CONTROL_MODE_SELECT_DESCRIPTION", 124, "ambSoundControlModeSelectDescription");
    ESA_INFORMATION = new Dialog("ESA_INFORMATION", 125, "esaInformation");
    ESA_ABS_ERROR_NOTCONNECTED_RIGHT = new Dialog("ESA_ABS_ERROR_NOTCONNECTED_RIGHT", 126, "esaAbsErrorNotconnectedRight");
    ESA_ABS_ERROR_NOTCONNECTED_LEFT = new Dialog("ESA_ABS_ERROR_NOTCONNECTED_LEFT", 127, "esaAbsErrorNotconnectedLeft");
    ESA_ABS_ERROR_CANNOTEXECUTE = new Dialog("ESA_ABS_ERROR_CANNOTEXECUTE", 128, "esaAbsErrorCannotexecute");
    ESA_ABS_ERROR_NOTWEARING_RIGHT = new Dialog("ESA_ABS_ERROR_NOTWEARING_RIGHT", 129, "esaAbsErrorNotwearingRight");
    ESA_ABS_ERROR_NOTWEARING_LEFT = new Dialog("ESA_ABS_ERROR_NOTWEARING_LEFT", 130, "esaAbsErrorNotwearingLeft");
    ESA_ABS_ERROR_NOTWEARING_BOTH = new Dialog("ESA_ABS_ERROR_NOTWEARING_BOTH", 131, "esaAbsErrorNotwearingBoth");
    ESA_RELATIVE_ERROR_NOTCONNECTED_RIGHT = new Dialog("ESA_RELATIVE_ERROR_NOTCONNECTED_RIGHT", 132, "esaRelativeErrorNotconnectedRight");
    ESA_RELATIVE_ERROR_NOTCONNECTED_LEFT = new Dialog("ESA_RELATIVE_ERROR_NOTCONNECTED_LEFT", 133, "esaRelativeErrorNotconnectedLeft");
    ESA_RELATIVE_ERROR_CANNOTEXECUTE = new Dialog("ESA_RELATIVE_ERROR_CANNOTEXECUTE", 134, "esaRelativeErrorCannotexecute");
    ESA_RELATIVE_ERROR_NOTWEARING_RIGHT = new Dialog("ESA_RELATIVE_ERROR_NOTWEARING_RIGHT", 135, "esaRelativeErrorNotwearingRight");
    ESA_RELATIVE_ERROR_NOTWEARING_LEFT = new Dialog("ESA_RELATIVE_ERROR_NOTWEARING_LEFT", 136, "esaRelativeErrorNotwearingLeft");
    ESA_RELATIVE_ERROR_NOTWEARING_BOTH = new Dialog("ESA_RELATIVE_ERROR_NOTWEARING_BOTH", 137, "esaRelativeErrorNotwearingBoth");
    RESET_SETTINGS_CONFIRM_RESET = new Dialog("RESET_SETTINGS_CONFIRM_RESET", 138, "resetSettingsConfirmReset");
    RESET_SETTINGS_CONFIRM_RESET_APPLICATION = new Dialog("RESET_SETTINGS_CONFIRM_RESET_APPLICATION", 139, "resetSettingsConfirmResetApplication");
    RESET_SETTINGS_CONFIRM_FACTORY_RESET = new Dialog("RESET_SETTINGS_CONFIRM_FACTORY_RESET", 140, "resetSettingsConfirmFactoryReset");
    RESET_SETTINGS_FAILED_L_CONNECTION = new Dialog("RESET_SETTINGS_FAILED_L_CONNECTION", 141, "resetSettingsFailedLConnection");
    RESET_SETTINGS_FAILED_R_CONNECTION = new Dialog("RESET_SETTINGS_FAILED_R_CONNECTION", 142, "resetSettingsFailedRConnection");
    RESET_SETTINGS_FAILED_L_HEADPHONE = new Dialog("RESET_SETTINGS_FAILED_L_HEADPHONE", 143, "resetSettingsFailedLHeadphone");
    RESET_SETTINGS_FAILED_R_HEADPHONE = new Dialog("RESET_SETTINGS_FAILED_R_HEADPHONE", 144, "resetSettingsFailedRHeadphone");
    RESET_SETTINGS_SUCCEEDED = new Dialog("RESET_SETTINGS_SUCCEEDED", 145, "resetSettingsSucceeded");
    CHANGE_VA_TO_ALEXA_CONFIRMATION = new Dialog("CHANGE_VA_TO_ALEXA_CONFIRMATION", 146, "changeVaToAlexaConfirmation");
    CHANGE_VA_TO_OTHER_CONFIRMATION = new Dialog("CHANGE_VA_TO_OTHER_CONFIRMATION", 147, "changeVaToOtherConfirmation");
    VOICE_ASSISTANT_INTRODUCTION = new Dialog("VOICE_ASSISTANT_INTRODUCTION", 148, "voiceAssistantIntroduction");
    AMAZON_ALEXA_INSTALL_CONFIRMATION = new Dialog("AMAZON_ALEXA_INSTALL_CONFIRMATION", 149, "amazonAlexaInstallConfirmation");
    a = new Dialog[] { 
        UNKNOWN, OTHER, BT_ON, CAUTION_LOCATION, PERMISSION_LOCATION, CAUTION_GPS, GPS_ON, DEVICE_PAIRING, VOICE_DATA_MDR_BATTERY_POWER, VOICE_DATA_MOBILE_BATTERY_POWER, 
        VOICE_DATA_DOWNLOAD_ERROR, VOICE_DATA_TRANSFER_ERROR, VOICE_DATA_INSTALL_ERROR, VOICE_DATA_DISCARD_FW_UPDATE, GOOGLE_ASSISTANT_INTRODUCTION, FW_UPDATE_RECOMMENDATION, FW_MDR_BATTERY_POWER, FW_MOBILE_BATTERY_POWER, FW_NETWORK_ERROR, FW_MDR_L_CONNECTION_ERROR, 
        FW_MDR_R_CONNECTION_ERROR, FW_DATA_ERROR, FW_DOWNLOAD_ERROR, FW_TRANSFER_ERROR, FW_INSTALL_ERROR, FW_ABORT_CONFIRMATION, FW_UPDATE_COMPLETION, FW_UPDATE_CONFIRM_COMPLETION, VOICE_DATA_MDR_L_CONNECTION_ERROR, VOICE_DATA_MDR_R_CONNECTION_ERROR, 
        IA_SETUP_SKIP_CONFIRMATION, IA_SAMPLE_PLAYBACK_WARNING, IA_SAMPLE_PLAYBACK_PASSIVE_WARNING, IA_OPEN_STORE_CONFIRMATION, IA_HOW_TO_USE_EAR_IMAGES_NOTICE, IA_PRIVACY_POLICY_NOTICE, IA_GDPR_NOTICE, IA_VOICE_GUIDE_NOTICE, IA_HRTF_CREATION_ERROR, IA_HRTF_UPLOAD_ERROR, 
        IA_INSTALL_CONFIRM, IA_STEP_GDPR_NOTICE, IA_CAMERA_MANUAL_CONFIRM, IA_DOUBLE_EFFECT_FLOW_CONFIRM, IA_DOUBLE_EFFECT_TRIAL_LISTENING_CONFIRM, IA_DOUBLE_EFFECT_SPC_CAUTION, IA_DOUBLE_EFFECT_VPT_CAUTION, IA_COUPON_DIALOG, IA_ALREADY_SAVED_HRTF, IA_HRTF_DOWNLOAD_ERROR, 
        IA_NO_HRTF_DATA_TIMEOUT, IA_NO_HRTF_DATA_MANUAL, CRADLE_BATTERY_ACTIVATE, CRADLE_BATTERY_INFO, CAUTION_DUAL_ASSIGNMENT, QUESTIONNAIRE, QUESTIONNAIRE_HOW_TO_DISPLAY, QUESTIONNAIRE_NOT_EXIST, TALKING_MODE_DESCRIPTION, TALKING_MODE_DESCRIPTION_FOR_ENABLE_FIRST_TIME, 
        TALKING_MODE_CONFIRMATION_AFTER_TRIAL, TALKING_MODE_TURN_ON_CONFIRMATION, BOTTOM_SHEET, MULTI_POINT_SETTING_INFO, MULTI_POINT_SETTING_ENABLE_CONFIRMATION, MULTI_POINT_SETTING_DISABLE_CONFIRMATION, MULTIPOINT_ADD_DEVICE_CAUTION_MAXIMUM_DEVICE, MULTIPOINT_ENTER_PAIRING_MODE_ERROR, MULTIPOINT_PAIRING_CANCEL, MULTIPOINT_PAIRING_ERROR, 
        MULTIPOINT_PAIRING_SUCCESS, MULTIPOINT_DELETE_CONNECTED_DEVICE, MULTIPOINT_DELETE_HISTORY_DEVICE, MULTIPOINT_DELETE_DEVICE_ERROR, MULTIPOINT_CONNECT_DEVICE_CAUTION_MAXIMUM_DEVICE, MULTIPOINT_CONNECT_ERROR, MULTIPOINT_DISCONNECT_OWN_DEVICE, MULTIPOINT_DISCONNECT_DEVICE, MULTIPOINT_DISCONNECT_DEVICE_ERROR, MULTIPOINT_DISCONNECT_CONFIRMATION_BEFORE_FW_UPDATE, 
        MULTIPOINT_DISCONNECT_CONFIRMATION_BEFORE_VOICE_GUIDANCE, FW_ABORT_CONFIRMATION_BEFORE_MULTIPOINT_PAIRING, FW_ABORT_CONFIRMATION_BEFORE_MULTIPOINT_CONNECT_HISTORY_DEVICE, APP_UPDATE_CONFIRMATION_BEFORE_FW_UPDATE, ASC_SELECT_APPLYING_TARGET_SETTING, ASC_UNREGISTER_PLACE_CONFIRMATION, ACCOUNT_SETTINGS_INITIALIZE_NETWORK_ERROR, ACCOUNT_SETTINGS_INITIALIZE_RESIGN_IN_ERROR, ACCOUNT_SETTINGS_INITIALIZE_SERVER_ERROR, ACCOUNT_SETTINGS_SIGN_IN_PAGE_SIGN_IN_FAILED, 
        ACCOUNT_SETTINGS_TOKEN_SIGN_IN_FAILED, ACCOUNT_SETTINGS_TOKEN_SERVER_ERROR, ACCOUNT_SETTINGS_BACKUP_RESTORE, ACCOUNT_SETTINGS_BACKUP_FAILED, ACCOUNT_SETTINGS_RESTORE_FAILED, ACCOUNT_SETTINGS_BACKUP_CHECK_SERVER_ERROR, ACCOUNT_SETTINGS_NO_DATA_TO_RESTORE, BATTERY_CONSUMPTION_INCREASE_CONFIRMATION, INFORMATION, FEEDBACK_INFO, 
        OTHER_INFO, CHANGE_VOICE_ASSISTANT_CONFIRMATION, CHANGE_VOICE_ASSISTANT_PANEL_CONFIRMATION, CHANGE_VOICE_ASSISTANT_BTN_WITH_LR_SELECT_CONFIRMATION, CHANGE_VOICE_ASSISTANT_SENSOR_WITH_LR_SELECT_CONFIRMATION, VOICE_ASSISTANT_PANEL_INFORMATION, VOICE_ASSISTANT_SENSOR_INFORMATION, VOICE_ASSISTANT_BTN_INFORMATION, VA_SENSOR_DISABLE_AND_RECONNECTION_CONFIRMATION, VA_SENSOR_ENABLE_AND_RECONNECTION_CONFIRMATION, 
        VA_BTN_DISABLE_AND_RECONNECTION_CONFIRMATION, VA_BTN_ENABLE_AND_RECONNECTION_CONFIRMATION, VA_SENSOR_DISABLE_CONFIRMATION, VA_SENSOR_ENABLE_CONFIRMATION, VA_BTN_DISABLE_CONFIRMATION, VA_BTN_ENABLE_CONFIRMATION, CAUTION_PLAYBACK_CONTROL_DUAL_ASSIGNMENT, DISABLE_TOUCH_PANEL_CONFIRMATION, ENABLE_TOUCH_PANEL_CONFIRMATION, DISABLE_TOUCH_PANEL_AND_RECONNECTION_CONFIRMATION, 
        ENABLE_TOUCH_PANEL_AND_RECONNECTION_CONFIRMATION, LOCATION_FOREGROUND_PERMISSION_POST_EXPLANATION_DIALOG, LOCATION_BACKGROUND_PERMISSION_POST_EXPLANATION_DIALOG, CAMERA_PERMISSION_POST_EXPLANATION_DIALOG, AMB_SOUND_CONTROL_MODE_SELECT_DESCRIPTION, ESA_INFORMATION, ESA_ABS_ERROR_NOTCONNECTED_RIGHT, ESA_ABS_ERROR_NOTCONNECTED_LEFT, ESA_ABS_ERROR_CANNOTEXECUTE, ESA_ABS_ERROR_NOTWEARING_RIGHT, 
        ESA_ABS_ERROR_NOTWEARING_LEFT, ESA_ABS_ERROR_NOTWEARING_BOTH, ESA_RELATIVE_ERROR_NOTCONNECTED_RIGHT, ESA_RELATIVE_ERROR_NOTCONNECTED_LEFT, ESA_RELATIVE_ERROR_CANNOTEXECUTE, ESA_RELATIVE_ERROR_NOTWEARING_RIGHT, ESA_RELATIVE_ERROR_NOTWEARING_LEFT, ESA_RELATIVE_ERROR_NOTWEARING_BOTH, RESET_SETTINGS_CONFIRM_RESET, RESET_SETTINGS_CONFIRM_RESET_APPLICATION, 
        RESET_SETTINGS_CONFIRM_FACTORY_RESET, RESET_SETTINGS_FAILED_L_CONNECTION, RESET_SETTINGS_FAILED_R_CONNECTION, RESET_SETTINGS_FAILED_L_HEADPHONE, RESET_SETTINGS_FAILED_R_HEADPHONE, RESET_SETTINGS_SUCCEEDED, CHANGE_VA_TO_ALEXA_CONFIRMATION, CHANGE_VA_TO_OTHER_CONFIRMATION, VOICE_ASSISTANT_INTRODUCTION, AMAZON_ALEXA_INSTALL_CONFIRMATION };
  }
  
  Dialog(String paramString1) {
    this.mStrValue = paramString1;
  }
  
  public String getStrValue() {
    return this.mStrValue;
  }
}


/* Location:              /home/egaebel/Programs/sony-headphones-hack/base-dex2jar.jar!/com/sony/songpal/mdr/j2objc/actionlog/param/Dialog.class
 * Java compiler version: 6 (50.0)
 * JD-Core Version:       1.1.3
 */