package com.sony.songpal.mdr.j2objc.actionlog.param;

public enum EventId {
  ANSWERED_INFORMATION,
  ANSWER_QUESTIONNAIRE,
  CHANGING_ACTIVITY_RECOGNITION_SETTING_AUDIO_DEVICE,
  CHANGING_APPLICATION_SETTING_AUDIO_DEVICE,
  CHANGING_ASC_PLACE_SETTING_AUDIO_DEVICE,
  CHANGING_ASC_SETTING_AUDIO_DEVICE,
  CHANGING_AUDIO_VOLUME,
  CHANGING_CUSTOMIZABLE_ASSIGNABLE_SETTINGS_AUDIO_DEVICE,
  CHANGING_GENERAL_SETTING,
  CHANGING_IA_SETTINGS_AUDIO_DEVICE,
  CHANGING_SETTING_TAKE_OVER_SETTING,
  CHANGING_SOUND_SETTING,
  CHANGING_SYSTEM_SETTING,
  CHANGING_TALKING_MODE_SETTING,
  CHANGING_TRAINING_MODE_SETTING,
  CHANGING_VOICE_GUIDANCE_SETTING_AUDIO_DEVICE,
  CLOSED_INFORMATION_TO_USERS,
  CLOSE_INFORMATION,
  CLOSE_QUESTIONNAIRE,
  CONNECTION_ERROR,
  CREATE_WIDGET_HOME,
  CREATE_WIDGET_SIDE_SENSE,
  DELETED_APPLICATION_NOTIFICATION,
  DELETED_INFORMATION,
  DELETE_WIDGET_HOME,
  DELETE_WIDGET_SIDE_SENSE,
  DETECTED_APPLICATION_NOTIFICATION,
  DETECTED_APPLICATION_NOTIFICATION_AUDIO_DEVICE,
  DETECTED_ASC_CONTEXT_AUDIO_DEVICE,
  DETECTED_INFORMATION_TO_USERS,
  DETECTED_PUSH_NOTIFICATION,
  DISCONNECTED_AUDIO_DEVICE,
  DISCOVERED_SONY_AUDIO_BLE_PERIPHERAL,
  DISPLAYED_DIALOG,
  DISPLAYED_DIALOG_AUDIO_DEVICE,
  DISPLAYED_LOCAL_NOTIFICATION,
  DISPLAYED_LOCAL_NOTIFICATION_AUDIO_DEVICE,
  IA_SYSTEM_ERROR,
  OBTAINED_ACTIVITY_RECOGNITION_SETTING_AUDIO_DEVICE,
  OBTAINED_APPLICATION_NOTIFICATION,
  OBTAINED_APPLICATION_SETTING,
  OBTAINED_APPLICATION_SETTING_AUDIO_DEVICE,
  OBTAINED_ASC_PLACE_SETTING_AUDIO_DEVICE,
  OBTAINED_ASC_SETTING_AUDIO_DEVICE,
  OBTAINED_AUDIO_VOLUME,
  OBTAINED_BATTERY_STATUS_AUDIO_DEVICE,
  OBTAINED_CONNECTED_DEVICES,
  OBTAINED_CUSTOMIZABLE_ASSIGNABLE_SETTINGS_AUDIO_DEVICE,
  OBTAINED_GENERAL_SETTING,
  OBTAINED_IA_SETTINGS_AUDIO_DEVICE,
  OBTAINED_INFORMATION,
  OBTAINED_PAIRED_DEVICES,
  OBTAINED_SETTING_TAKE_OVER_SETTING,
  OBTAINED_SOUND_SETTING("obtainedSoundSetting"),
  OBTAINED_SYSTEM_SETTING("obtainedSoundSetting"),
  OBTAINED_TALKING_MODE_SETTING("obtainedSoundSetting"),
  OBTAINED_TRAINING_MODE_SETTING("obtainedSoundSetting"),
  OBTAINED_VOICE_GUIDANCE_SETTING_AUDIO_DEVICE("obtainedSoundSetting"),
  PERFORMED_FACTORY_RESET_HEADPHONE_AUDIO_DEVICE("obtainedSoundSetting"),
  PERFORMED_RESET_APPLICATION_AUDIO_DEVICE("obtainedSoundSetting"),
  PERFORMED_RESET_HEADPHONE_AUDIO_DEVICE("obtainedSoundSetting"),
  PLAYING_MUSIC_META("obtainedSoundSetting"),
  READ_INFORMATION("obtainedSoundSetting"),
  READ_INFORMATION_TO_USERS("obtainedSoundSetting"),
  READ_QUESTIONNAIRE("obtainedSoundSetting"),
  RECEIVED_AUDIO_VOLUME("obtainedSoundSetting"),
  RECEIVED_BATTERY_STATUS_AUDIO_DEVICE("obtainedSoundSetting"),
  RECEIVED_CONNECTED_DEVICES("obtainedSoundSetting"),
  RECEIVED_CUSTOMIZABLE_ASSIGNABLE_SETTINGS_AUDIO_DEVICE("obtainedSoundSetting"),
  RECEIVED_FW_UPDATE_STATUS_AUDIO_DEVICE("obtainedSoundSetting"),
  RECEIVED_GENERAL_SETTING("obtainedSoundSetting"),
  RECEIVED_MDR_DEVICE_LOG("obtainedSoundSetting"),
  RECEIVED_PAIRED_DEVICES("obtainedSoundSetting"),
  RECEIVED_PLAYBACK_STATUS("obtainedSoundSetting"),
  RECEIVED_SOUND_SETTING("obtainedSoundSetting"),
  RECEIVED_SYSTEM_SETTING("obtainedSoundSetting"),
  RECEIVED_TALKING_MODE_SETTING("obtainedSoundSetting"),
  RECEIVED_VOICE_GUIDANCE_SETTING_AUDIO_DEVICE("obtainedSoundSetting"),
  SELECTED_LOCAL_NOTIFICATION("obtainedSoundSetting"),
  SELECTED_LOCAL_NOTIFICATION_AUDIO_DEVICE("obtainedSoundSetting"),
  SELECTED_PLAYBACK_CONTROLLER("obtainedSoundSetting"),
  SELECTED_PUSH_NOTIFICATION("obtainedSoundSetting"),
  SELECTED_RESET_ITEM_AUDIO_DEVICE("obtainedSoundSetting"),
  START_INITIAL_SETUP_AUDIO_DEVICE("obtainedSoundSetting"),
  START_WIDGET_HOME_AUDIO_DEVICE("obtainedSoundSetting"),
  START_WIDGET_SIDE_SENSE_AUDIO_DEVICE("obtainedSoundSetting"),
  UPDATE_EARPIECE_SIZE_ASSISTANT_RESULT_AUDIO_DEVICE("obtainedSoundSetting");
  
  private final String mStrValue;
  
  static {
    CHANGING_SOUND_SETTING = new EventId("CHANGING_SOUND_SETTING", 1, "changingSoundSetting");
    RECEIVED_SOUND_SETTING = new EventId("RECEIVED_SOUND_SETTING", 2, "receivedSoundSetting");
    OBTAINED_SYSTEM_SETTING = new EventId("OBTAINED_SYSTEM_SETTING", 3, "obtainedSystemSettingAudioDevice");
    CHANGING_SYSTEM_SETTING = new EventId("CHANGING_SYSTEM_SETTING", 4, "changingSystemSettingAudioDevice");
    RECEIVED_SYSTEM_SETTING = new EventId("RECEIVED_SYSTEM_SETTING", 5, "receivedSystemSettingAudioDevice");
    OBTAINED_AUDIO_VOLUME = new EventId("OBTAINED_AUDIO_VOLUME", 6, "obtainedAudioVolumeAudioDevice");
    CHANGING_AUDIO_VOLUME = new EventId("CHANGING_AUDIO_VOLUME", 7, "changingAudioVolumeAudioDevice");
    RECEIVED_AUDIO_VOLUME = new EventId("RECEIVED_AUDIO_VOLUME", 8, "receivedAudioVolumeAudioDevice");
    OBTAINED_APPLICATION_SETTING = new EventId("OBTAINED_APPLICATION_SETTING", 9, "obtainedApplicationSetting");
    OBTAINED_APPLICATION_SETTING_AUDIO_DEVICE = new EventId("OBTAINED_APPLICATION_SETTING_AUDIO_DEVICE", 10, "obtainedApplicationSettingAudioDevice");
    CHANGING_APPLICATION_SETTING_AUDIO_DEVICE = new EventId("CHANGING_APPLICATION_SETTING_AUDIO_DEVICE", 11, "changingApplicationSettingAudioDevice");
    OBTAINED_ACTIVITY_RECOGNITION_SETTING_AUDIO_DEVICE = new EventId("OBTAINED_ACTIVITY_RECOGNITION_SETTING_AUDIO_DEVICE", 12, "obtainedActivityRecognitionSettingAudioDevice");
    CHANGING_ACTIVITY_RECOGNITION_SETTING_AUDIO_DEVICE = new EventId("CHANGING_ACTIVITY_RECOGNITION_SETTING_AUDIO_DEVICE", 13, "changingActivityRecognitionSettingAudioDevice");
    OBTAINED_APPLICATION_NOTIFICATION = new EventId("OBTAINED_APPLICATION_NOTIFICATION", 14, "obtainedApplicationNotification");
    DETECTED_APPLICATION_NOTIFICATION = new EventId("DETECTED_APPLICATION_NOTIFICATION", 15, "detectedApplicationNotification");
    DETECTED_APPLICATION_NOTIFICATION_AUDIO_DEVICE = new EventId("DETECTED_APPLICATION_NOTIFICATION_AUDIO_DEVICE", 16, "detectedApplicationNotificationAudioDevice");
    DELETED_APPLICATION_NOTIFICATION = new EventId("DELETED_APPLICATION_NOTIFICATION", 17, "deletedApplicationNotification");
    PLAYING_MUSIC_META = new EventId("PLAYING_MUSIC_META", 18, "playingMusicMetaAudioDevice");
    SELECTED_PLAYBACK_CONTROLLER = new EventId("SELECTED_PLAYBACK_CONTROLLER", 19, "selectedPlaybackControllerAudioDevice");
    RECEIVED_PLAYBACK_STATUS = new EventId("RECEIVED_PLAYBACK_STATUS", 20, "receivedPlaybackStatusAudioDevice");
    RECEIVED_MDR_DEVICE_LOG = new EventId("RECEIVED_MDR_DEVICE_LOG", 21, "receivedMdrDeviceLogAudioDevice");
    OBTAINED_TRAINING_MODE_SETTING = new EventId("OBTAINED_TRAINING_MODE_SETTING", 22, "obtainedTrainingModeSettingAudioDevice");
    CHANGING_TRAINING_MODE_SETTING = new EventId("CHANGING_TRAINING_MODE_SETTING", 23, "changingTrainingModeSettingAudioDevice");
    OBTAINED_GENERAL_SETTING = new EventId("OBTAINED_GENERAL_SETTING", 24, "obtainedGeneralSettingAudioDevice");
    CHANGING_GENERAL_SETTING = new EventId("CHANGING_GENERAL_SETTING", 25, "changingGeneralSettingAudioDevice");
    RECEIVED_GENERAL_SETTING = new EventId("RECEIVED_GENERAL_SETTING", 26, "receivedGeneralSettingAudioDevice");
    DETECTED_PUSH_NOTIFICATION = new EventId("DETECTED_PUSH_NOTIFICATION", 27, "detectedPushNotification");
    SELECTED_PUSH_NOTIFICATION = new EventId("SELECTED_PUSH_NOTIFICATION", 28, "selectedPushNotification");
    CONNECTION_ERROR = new EventId("CONNECTION_ERROR", 29, "connectionErrorAudioDevice");
    IA_SYSTEM_ERROR = new EventId("IA_SYSTEM_ERROR", 30, "iaSystemErrorAudioDevice");
    DISCOVERED_SONY_AUDIO_BLE_PERIPHERAL = new EventId("DISCOVERED_SONY_AUDIO_BLE_PERIPHERAL", 31, "discoveredSonyAudioBlePeripheral");
    DISPLAYED_DIALOG = new EventId("DISPLAYED_DIALOG", 32, "displayedDialog");
    DISPLAYED_DIALOG_AUDIO_DEVICE = new EventId("DISPLAYED_DIALOG_AUDIO_DEVICE", 33, "displayedDialogAudioDevice");
    DETECTED_INFORMATION_TO_USERS = new EventId("DETECTED_INFORMATION_TO_USERS", 34, "detectedInformationToUsers");
    READ_INFORMATION_TO_USERS = new EventId("READ_INFORMATION_TO_USERS", 35, "readInformationToUsers");
    CLOSED_INFORMATION_TO_USERS = new EventId("CLOSED_INFORMATION_TO_USERS", 36, "closedInformationToUsers");
    OBTAINED_BATTERY_STATUS_AUDIO_DEVICE = new EventId("OBTAINED_BATTERY_STATUS_AUDIO_DEVICE", 37, "obtainedBatteryStatusAudioDevice");
    RECEIVED_BATTERY_STATUS_AUDIO_DEVICE = new EventId("RECEIVED_BATTERY_STATUS_AUDIO_DEVICE", 38, "receivedBatteryStatusAudioDevice");
    OBTAINED_VOICE_GUIDANCE_SETTING_AUDIO_DEVICE = new EventId("OBTAINED_VOICE_GUIDANCE_SETTING_AUDIO_DEVICE", 39, "obtainedVoiceGuidanceSettingAudioDevice");
    CHANGING_VOICE_GUIDANCE_SETTING_AUDIO_DEVICE = new EventId("CHANGING_VOICE_GUIDANCE_SETTING_AUDIO_DEVICE", 40, "changingVoiceGuidanceSettingAudioDevice");
    RECEIVED_VOICE_GUIDANCE_SETTING_AUDIO_DEVICE = new EventId("RECEIVED_VOICE_GUIDANCE_SETTING_AUDIO_DEVICE", 41, "receivedVoiceGuidanceSettingAudioDevice");
    RECEIVED_FW_UPDATE_STATUS_AUDIO_DEVICE = new EventId("RECEIVED_FW_UPDATE_STATUS_AUDIO_DEVICE", 42, "receivedFwUpdateStatusAudioDevice");
    ANSWER_QUESTIONNAIRE = new EventId("ANSWER_QUESTIONNAIRE", 43, "answerQuestionnaire");
    READ_QUESTIONNAIRE = new EventId("READ_QUESTIONNAIRE", 44, "readQuestionnaire");
    CLOSE_QUESTIONNAIRE = new EventId("CLOSE_QUESTIONNAIRE", 45, "closeQuestionnaire");
    OBTAINED_TALKING_MODE_SETTING = new EventId("OBTAINED_TALKING_MODE_SETTING", 46, "obtainedTalkingModeSettingAudioDevice");
    CHANGING_TALKING_MODE_SETTING = new EventId("CHANGING_TALKING_MODE_SETTING", 47, "changingTalkingModeSettingAudioDevice");
    RECEIVED_TALKING_MODE_SETTING = new EventId("RECEIVED_TALKING_MODE_SETTING", 48, "receivedTalkingModeSettingAudioDevice");
    OBTAINED_CONNECTED_DEVICES = new EventId("OBTAINED_CONNECTED_DEVICES", 49, "obtainedConnectedDevicesAudioDevice");
    RECEIVED_CONNECTED_DEVICES = new EventId("RECEIVED_CONNECTED_DEVICES", 50, "receivedConnectedDevicesAudioDevice");
    OBTAINED_PAIRED_DEVICES = new EventId("OBTAINED_PAIRED_DEVICES", 51, "obtainedPairedDevicesAudioDevice");
    RECEIVED_PAIRED_DEVICES = new EventId("RECEIVED_PAIRED_DEVICES", 52, "receivedPairedDevicesAudioDevice");
    OBTAINED_ASC_SETTING_AUDIO_DEVICE = new EventId("OBTAINED_ASC_SETTING_AUDIO_DEVICE", 53, "obtainedAscSettingAudioDevice");
    CHANGING_ASC_SETTING_AUDIO_DEVICE = new EventId("CHANGING_ASC_SETTING_AUDIO_DEVICE", 54, "changingAscSettingAudioDevice");
    OBTAINED_ASC_PLACE_SETTING_AUDIO_DEVICE = new EventId("OBTAINED_ASC_PLACE_SETTING_AUDIO_DEVICE", 55, "obtainedAscPlaceSettingAudioDevice");
    CHANGING_ASC_PLACE_SETTING_AUDIO_DEVICE = new EventId("CHANGING_ASC_PLACE_SETTING_AUDIO_DEVICE", 56, "changingAscPlaceSettingAudioDevice");
    DETECTED_ASC_CONTEXT_AUDIO_DEVICE = new EventId("DETECTED_ASC_CONTEXT_AUDIO_DEVICE", 57, "detectedAscContextAudioDevice");
    DISPLAYED_LOCAL_NOTIFICATION = new EventId("DISPLAYED_LOCAL_NOTIFICATION", 58, "displayedLocalNotification");
    SELECTED_LOCAL_NOTIFICATION = new EventId("SELECTED_LOCAL_NOTIFICATION", 59, "selectedLocalNotification");
    OBTAINED_IA_SETTINGS_AUDIO_DEVICE = new EventId("OBTAINED_IA_SETTINGS_AUDIO_DEVICE", 60, "obtained360RASettingAudioDevice");
    DISPLAYED_LOCAL_NOTIFICATION_AUDIO_DEVICE = new EventId("DISPLAYED_LOCAL_NOTIFICATION_AUDIO_DEVICE", 61, "displayedLocalNotificationAudioDevice");
    SELECTED_LOCAL_NOTIFICATION_AUDIO_DEVICE = new EventId("SELECTED_LOCAL_NOTIFICATION_AUDIO_DEVICE", 62, "selectedLocalNotificationAudioDevice");
    OBTAINED_SETTING_TAKE_OVER_SETTING = new EventId("OBTAINED_SETTING_TAKE_OVER_SETTING", 63, "obtainedSettingTakeOverSetting");
    CHANGING_SETTING_TAKE_OVER_SETTING = new EventId("CHANGING_SETTING_TAKE_OVER_SETTING", 64, "changingSettingTakeOverSetting");
    CHANGING_IA_SETTINGS_AUDIO_DEVICE = new EventId("CHANGING_IA_SETTINGS_AUDIO_DEVICE", 65, "changing360RASettingAudioDevice");
    DELETED_INFORMATION = new EventId("DELETED_INFORMATION", 66, "deletedInformation");
    READ_INFORMATION = new EventId("READ_INFORMATION", 67, "readInformation");
    CLOSE_INFORMATION = new EventId("CLOSE_INFORMATION", 68, "closeInformation");
    ANSWERED_INFORMATION = new EventId("ANSWERED_INFORMATION", 69, "answeredInformation");
    OBTAINED_INFORMATION = new EventId("OBTAINED_INFORMATION", 70, "obtainedInformation");
    CREATE_WIDGET_HOME = new EventId("CREATE_WIDGET_HOME", 71, "createWidgetHome");
    CREATE_WIDGET_SIDE_SENSE = new EventId("CREATE_WIDGET_SIDE_SENSE", 72, "createWidgetSideSense");
    DELETE_WIDGET_HOME = new EventId("DELETE_WIDGET_HOME", 73, "deleteWidgetHome");
    DELETE_WIDGET_SIDE_SENSE = new EventId("DELETE_WIDGET_SIDE_SENSE", 74, "deleteWidgetSideSense");
    START_WIDGET_HOME_AUDIO_DEVICE = new EventId("START_WIDGET_HOME_AUDIO_DEVICE", 75, "startWidgetHomeAudioDevice");
    START_WIDGET_SIDE_SENSE_AUDIO_DEVICE = new EventId("START_WIDGET_SIDE_SENSE_AUDIO_DEVICE", 76, "startWidgetSideSenseAudioDevice");
    OBTAINED_CUSTOMIZABLE_ASSIGNABLE_SETTINGS_AUDIO_DEVICE = new EventId("OBTAINED_CUSTOMIZABLE_ASSIGNABLE_SETTINGS_AUDIO_DEVICE", 77, "obtainedCustomizableAssignableSettingsAudioDevice");
    CHANGING_CUSTOMIZABLE_ASSIGNABLE_SETTINGS_AUDIO_DEVICE = new EventId("CHANGING_CUSTOMIZABLE_ASSIGNABLE_SETTINGS_AUDIO_DEVICE", 78, "changingCustomizableAssignableSettingsAudioDevice");
    RECEIVED_CUSTOMIZABLE_ASSIGNABLE_SETTINGS_AUDIO_DEVICE = new EventId("RECEIVED_CUSTOMIZABLE_ASSIGNABLE_SETTINGS_AUDIO_DEVICE", 79, "receivedCustomizableAssignableSettingsAudioDevice");
    UPDATE_EARPIECE_SIZE_ASSISTANT_RESULT_AUDIO_DEVICE = new EventId("UPDATE_EARPIECE_SIZE_ASSISTANT_RESULT_AUDIO_DEVICE", 80, "updateESAResultAudioDevice");
    SELECTED_RESET_ITEM_AUDIO_DEVICE = new EventId("SELECTED_RESET_ITEM_AUDIO_DEVICE", 81, "selectedResetItemAudioDevice");
    PERFORMED_RESET_APPLICATION_AUDIO_DEVICE = new EventId("PERFORMED_RESET_APPLICATION_AUDIO_DEVICE", 82, "performedResetApplicationAudioDevice");
    PERFORMED_RESET_HEADPHONE_AUDIO_DEVICE = new EventId("PERFORMED_RESET_HEADPHONE_AUDIO_DEVICE", 83, "performedResetHeadphoneAudioDevice");
    PERFORMED_FACTORY_RESET_HEADPHONE_AUDIO_DEVICE = new EventId("PERFORMED_FACTORY_RESET_HEADPHONE_AUDIO_DEVICE", 84, "performedFactoryResetHeadphoneAudioDevice");
    DISCONNECTED_AUDIO_DEVICE = new EventId("DISCONNECTED_AUDIO_DEVICE", 85, "disconnectedAudioDevice");
    START_INITIAL_SETUP_AUDIO_DEVICE = new EventId("START_INITIAL_SETUP_AUDIO_DEVICE", 86, "startInitialSetupAudioDevice");
    a = new EventId[] { 
        OBTAINED_SOUND_SETTING, CHANGING_SOUND_SETTING, RECEIVED_SOUND_SETTING, OBTAINED_SYSTEM_SETTING, CHANGING_SYSTEM_SETTING, RECEIVED_SYSTEM_SETTING, OBTAINED_AUDIO_VOLUME, CHANGING_AUDIO_VOLUME, RECEIVED_AUDIO_VOLUME, OBTAINED_APPLICATION_SETTING, 
        OBTAINED_APPLICATION_SETTING_AUDIO_DEVICE, CHANGING_APPLICATION_SETTING_AUDIO_DEVICE, OBTAINED_ACTIVITY_RECOGNITION_SETTING_AUDIO_DEVICE, CHANGING_ACTIVITY_RECOGNITION_SETTING_AUDIO_DEVICE, OBTAINED_APPLICATION_NOTIFICATION, DETECTED_APPLICATION_NOTIFICATION, DETECTED_APPLICATION_NOTIFICATION_AUDIO_DEVICE, DELETED_APPLICATION_NOTIFICATION, PLAYING_MUSIC_META, SELECTED_PLAYBACK_CONTROLLER, 
        RECEIVED_PLAYBACK_STATUS, RECEIVED_MDR_DEVICE_LOG, OBTAINED_TRAINING_MODE_SETTING, CHANGING_TRAINING_MODE_SETTING, OBTAINED_GENERAL_SETTING, CHANGING_GENERAL_SETTING, RECEIVED_GENERAL_SETTING, DETECTED_PUSH_NOTIFICATION, SELECTED_PUSH_NOTIFICATION, CONNECTION_ERROR, 
        IA_SYSTEM_ERROR, DISCOVERED_SONY_AUDIO_BLE_PERIPHERAL, DISPLAYED_DIALOG, DISPLAYED_DIALOG_AUDIO_DEVICE, DETECTED_INFORMATION_TO_USERS, READ_INFORMATION_TO_USERS, CLOSED_INFORMATION_TO_USERS, OBTAINED_BATTERY_STATUS_AUDIO_DEVICE, RECEIVED_BATTERY_STATUS_AUDIO_DEVICE, OBTAINED_VOICE_GUIDANCE_SETTING_AUDIO_DEVICE, 
        CHANGING_VOICE_GUIDANCE_SETTING_AUDIO_DEVICE, RECEIVED_VOICE_GUIDANCE_SETTING_AUDIO_DEVICE, RECEIVED_FW_UPDATE_STATUS_AUDIO_DEVICE, ANSWER_QUESTIONNAIRE, READ_QUESTIONNAIRE, CLOSE_QUESTIONNAIRE, OBTAINED_TALKING_MODE_SETTING, CHANGING_TALKING_MODE_SETTING, RECEIVED_TALKING_MODE_SETTING, OBTAINED_CONNECTED_DEVICES, 
        RECEIVED_CONNECTED_DEVICES, OBTAINED_PAIRED_DEVICES, RECEIVED_PAIRED_DEVICES, OBTAINED_ASC_SETTING_AUDIO_DEVICE, CHANGING_ASC_SETTING_AUDIO_DEVICE, OBTAINED_ASC_PLACE_SETTING_AUDIO_DEVICE, CHANGING_ASC_PLACE_SETTING_AUDIO_DEVICE, DETECTED_ASC_CONTEXT_AUDIO_DEVICE, DISPLAYED_LOCAL_NOTIFICATION, SELECTED_LOCAL_NOTIFICATION, 
        OBTAINED_IA_SETTINGS_AUDIO_DEVICE, DISPLAYED_LOCAL_NOTIFICATION_AUDIO_DEVICE, SELECTED_LOCAL_NOTIFICATION_AUDIO_DEVICE, OBTAINED_SETTING_TAKE_OVER_SETTING, CHANGING_SETTING_TAKE_OVER_SETTING, CHANGING_IA_SETTINGS_AUDIO_DEVICE, DELETED_INFORMATION, READ_INFORMATION, CLOSE_INFORMATION, ANSWERED_INFORMATION, 
        OBTAINED_INFORMATION, CREATE_WIDGET_HOME, CREATE_WIDGET_SIDE_SENSE, DELETE_WIDGET_HOME, DELETE_WIDGET_SIDE_SENSE, START_WIDGET_HOME_AUDIO_DEVICE, START_WIDGET_SIDE_SENSE_AUDIO_DEVICE, OBTAINED_CUSTOMIZABLE_ASSIGNABLE_SETTINGS_AUDIO_DEVICE, CHANGING_CUSTOMIZABLE_ASSIGNABLE_SETTINGS_AUDIO_DEVICE, RECEIVED_CUSTOMIZABLE_ASSIGNABLE_SETTINGS_AUDIO_DEVICE, 
        UPDATE_EARPIECE_SIZE_ASSISTANT_RESULT_AUDIO_DEVICE, SELECTED_RESET_ITEM_AUDIO_DEVICE, PERFORMED_RESET_APPLICATION_AUDIO_DEVICE, PERFORMED_RESET_HEADPHONE_AUDIO_DEVICE, PERFORMED_FACTORY_RESET_HEADPHONE_AUDIO_DEVICE, DISCONNECTED_AUDIO_DEVICE, START_INITIAL_SETUP_AUDIO_DEVICE };
  }
  
  EventId(String paramString1) {
    this.mStrValue = paramString1;
  }
  
  public String getStrValue() {
    return this.mStrValue;
  }
}


/* Location:              /home/egaebel/Programs/sony-headphones-hack/base-dex2jar.jar!/com/sony/songpal/mdr/j2objc/actionlog/param/EventId.class
 * Java compiler version: 6 (50.0)
 * JD-Core Version:       1.1.3
 */