package com.sony.songpal.mdr.j2objc.actionlog.param;

public enum Screen {
  ABOUT_LICENSE_INFORMATION,
  ABOUT_THIS_APP,
  ACCOUNT_SETTINGS_AUTO_SYNC_INTRODUCTION,
  ACCOUNT_SETTINGS_AUTO_SYNC_OFF,
  ACCOUNT_SETTINGS_AUTO_SYNC_ON,
  ACCOUNT_SETTINGS_BACKUP_PROGRESS,
  ACCOUNT_SETTINGS_DETAIL_PAGE,
  ACCOUNT_SETTINGS_INITIALIZE_PROGRESS,
  ACCOUNT_SETTINGS_RESTORE_NEWDEVICE,
  ACCOUNT_SETTINGS_RESTORE_PROGRESS,
  ACCOUNT_SETTINGS_TOKEN_PROGRESS,
  ACCOUNT_SETTINGS_TOS,
  ACTIVITY_RECOG_CUSTOM,
  ADD_DEVICE,
  AMAZON_ALEXA_SPLASH,
  AMAZON_ALEXA_THINGS_TO_TRY,
  APP_NOTIFICATION_SETTING,
  ASC_CUSTOM_SOUND_SETTING_ACTIVITY_RECOGNITION,
  ASC_CUSTOM_SOUND_SETTING_PLACE,
  ASC_CUSTOM_SOUND_SETTING_SELECT_TARGET_ITEM,
  ASC_EDIT_PLACE_POSITION,
  ASC_PLACE_SETTING,
  ASC_REGISTER_PLACE,
  ASC_SELECT_LEARNED_PLACE,
  ASC_SELECT_PLACE_POSITION,
  ASC_SELECT_PLACE_TYPE,
  ASC_TOP,
  ASSIGNABLE_SETTINGS_CUSTOM,
  BACKGROUND,
  CONNECTION_DEVICE_LIST,
  CONNECTION_IN_PROGRESS,
  CONNECTION_NONE,
  CONNECTION_PAIRED_DEVICE,
  DASHBOARD,
  DASHBOARD_SOUND,
  DASHBOARD_STATUS,
  DASHBOARD_SYSTEM,
  DEVICE_SETTING,
  EQ_CUSTOM,
  ESA_ABS_COMPLETE_NG_BOTH,
  ESA_ABS_COMPLETE_NG_LEFT,
  ESA_ABS_COMPLETE_NG_RIGHT,
  ESA_ABS_COMPLETE_OK,
  ESA_ABS_MEASURING,
  ESA_ABS_MEASURING_ERROR,
  ESA_ABS_START_MEASURE,
  ESA_RELATIVE_JUDGEMENT_COMPLETE,
  ESA_RELATIVE_JUDGEMENT_ERROR,
  ESA_RELATIVE_MEASURING,
  ESA_RELATIVE_MEASURING_ERROR_1,
  ESA_RELATIVE_MEASURING_ERROR_2,
  ESA_RELATIVE_MEASURING_ERROR_3,
  ESA_RELATIVE_START_MEASURE_1,
  ESA_RELATIVE_START_MEASURE_2,
  ESA_RELATIVE_START_MEASURE_3,
  ESA_SIZE_SELECTION,
  ESA_TOP,
  EULA,
  FEEDBACK_INFO,
  FW_CONFIRMATION,
  FW_DOWNLOADING,
  FW_TRANSFERRED,
  FW_TRANSFERRING,
  FW_UPDATE_ABORTED,
  FW_UPDATE_COMPLETION,
  FW_UPDATE_IN_PROGRESS,
  IA_SETUP_ANALYSIS_CAMERA_LEFT_AUTO,
  IA_SETUP_ANALYSIS_CAMERA_LEFT_CONFIRMATION,
  IA_SETUP_ANALYSIS_CAMERA_LEFT_EDIT,
  IA_SETUP_ANALYSIS_CAMERA_LEFT_MANUAL,
  IA_SETUP_ANALYSIS_CAMERA_RIGHT_AUTO,
  IA_SETUP_ANALYSIS_CAMERA_RIGHT_CONFIRMATION,
  IA_SETUP_ANALYSIS_CAMERA_RIGHT_EDIT,
  IA_SETUP_ANALYSIS_CAMERA_RIGHT_MANUAL,
  IA_SETUP_ANALYSIS_COMPLETED,
  IA_SETUP_ANALYSIS_ERROR_CONFIRMATION,
  IA_SETUP_ANALYSIS_HOW_TO_TAKE,
  IA_SETUP_ANALYSIS_HRTF_APP_INTRO,
  IA_SETUP_ANALYSIS_HRTF_DOWNLOADING,
  IA_SETUP_ANALYSIS_INTRO,
  IA_SETUP_ANALYSIS_PROGRESS,
  IA_SETUP_ANALYSIS_SIGNIN_FOR_HRTF,
  IA_SETUP_ANALYSIS_SWITCH_HRTF_APP,
  IA_SETUP_INTRO_CONFIRMATION,
  IA_SETUP_INTRO_ENTRANCE,
  IA_SETUP_INTRO_SP_APP,
  IA_SETUP_INTRO_TRIAL_LISTENING,
  IA_SETUP_OPTIMIZE_APP_LIST,
  IA_SETUP_OPTIMIZE_APP_SELECTED,
  IA_SETUP_OPTIMIZE_COMPLETED,
  INFORMATION,
  INFORMATION_LIST,
  INITIAL_SETUP_ADAPTIVE_COMPLETION,
  INITIAL_SETUP_ADAPTIVE_PLACE_LEARN_SETTING,
  INITIAL_SETUP_ADAPTIVE_SETTING,
  INITIAL_SETUP_OVERALL_COMPLETION,
  INITIAL_SETUP_OVERALL_FINAL,
  INITIAL_SETUP_OVERALL_START,
  MULTIPOINT_ADDING_NEW_DEVICE,
  MULTIPOINT_DEVICE_OPTIONS,
  MULTIPOINT_DEVICE_SETTINGS,
  NCOPT_BAROMETRIC_MEASURE,
  NCOPT_COMPLETE,
  NCOPT_OPTIMIZING,
  NCOPT_PERSONAL_MEASURE,
  NON_EXISTENCE,
  OOBE_BLE_PAIRING,
  OOBE_MANUAL_PAIRING,
  OOBE_MANUAL_PAIRING_2,
  OOBE_NFC_PAIRING,
  OOBE_PAIRING_COMPLETION,
  OOBE_PASSIVE_MDR_LIST,
  OOBE_POWER_ON,
  OOBE_PROXIMITY,
  OTHER,
  OTHER_INFO,
  PTOUR_ASSIGNABLE_BUTTON_SETTING,
  PTOUR_CHANGE_EARPIECE,
  PTOUR_MAIN_BODY_OPERATION_1,
  PTOUR_MAIN_BODY_OPERATION_2,
  PTOUR_OFFLINE,
  PTOUR_PLAYBACK_BUTTON_OPERATION,
  PTOUR_QUICK_ATTENTION,
  PTOUR_TOUCH_PAD_OPERATION,
  PTOUR_WEAR_EARPHONE,
  QUESTIONNAIRE,
  RESET_SETTINGS_FACTORY_RESET,
  RESET_SETTINGS_MENU,
  RESET_SETTINGS_RESET,
  SETTINGS_TAKE_OVER_INTRODUCTION,
  SETTINGS_TAKE_OVER_INTRODUCTION_TIPS,
  TALKING_MODE_ACTION,
  TALKING_MODE_CUSTOM,
  TALKING_MODE_READY,
  TIPS_DETAIL_ASC_ENABLE_LOCATION_PERMISSION,
  TIPS_DETAIL_ASC_ENABLE_LOCATION_SETTING,
  TIPS_DETAIL_ASC_ENABLE_NOTIFICATION_SETTING,
  TIPS_DETAIL_ASC_ENABLE_PLACE_LEARNING,
  TIPS_DETAIL_ASC_ENABLE_PRECISE_LOCATION_PERMISSION,
  TIPS_DETAIL_IA_OPTIMIZE_SP_APP,
  TIPS_LIST,
  TRAINING_MODE_CUSTOM,
  UNKNOWN("unknown"),
  VOICE_ASSISTANT_SERVICELIST("unknown"),
  VOICE_DATA_COMPLETION("unknown"),
  VOICE_DATA_CONFIRMATION("unknown"),
  VOICE_DATA_DOWNLOADING("unknown"),
  VOICE_DATA_IN_PROGRESS("unknown"),
  VOICE_DATA_TRANSFERRING("unknown"),
  WELCOME("unknown");
  
  private final String mStrValue;
  
  static {
    OTHER = new Screen("OTHER", 1, "other");
    NON_EXISTENCE = new Screen("NON_EXISTENCE", 2, "nonExistence");
    BACKGROUND = new Screen("BACKGROUND", 3, "background");
    WELCOME = new Screen("WELCOME", 4, "welcome");
    EULA = new Screen("EULA", 5, "eula");
    ABOUT_THIS_APP = new Screen("ABOUT_THIS_APP", 6, "aboutThisApp");
    ABOUT_LICENSE_INFORMATION = new Screen("ABOUT_LICENSE_INFORMATION", 7, "aboutLicenseInformation");
    ADD_DEVICE = new Screen("ADD_DEVICE", 8, "addDevice");
    OOBE_NFC_PAIRING = new Screen("OOBE_NFC_PAIRING", 9, "oobeNfcPairing");
    OOBE_MANUAL_PAIRING = new Screen("OOBE_MANUAL_PAIRING", 10, "oobeManualPairing");
    OOBE_MANUAL_PAIRING_2 = new Screen("OOBE_MANUAL_PAIRING_2", 11, "oobeManualPairing2");
    OOBE_PAIRING_COMPLETION = new Screen("OOBE_PAIRING_COMPLETION", 12, "oobePairingCompletion");
    OOBE_PASSIVE_MDR_LIST = new Screen("OOBE_PASSIVE_MDR_LIST", 13, "oobePassiveMdrList");
    OOBE_POWER_ON = new Screen("OOBE_POWER_ON", 14, "oobePowerOn");
    OOBE_PROXIMITY = new Screen("OOBE_PROXIMITY", 15, "oobeProximity");
    OOBE_BLE_PAIRING = new Screen("OOBE_BLE_PAIRING", 16, "oobeBlePairing");
    DEVICE_SETTING = new Screen("DEVICE_SETTING", 17, "deviceSetting");
    CONNECTION_NONE = new Screen("CONNECTION_NONE", 18, "connectionNone");
    CONNECTION_PAIRED_DEVICE = new Screen("CONNECTION_PAIRED_DEVICE", 19, "connectionPairedDevice");
    CONNECTION_DEVICE_LIST = new Screen("CONNECTION_DEVICE_LIST", 20, "connectionDeviceList");
    CONNECTION_IN_PROGRESS = new Screen("CONNECTION_IN_PROGRESS", 21, "connectionInProgress");
    DASHBOARD = new Screen("DASHBOARD", 22, "dashboard");
    DASHBOARD_STATUS = new Screen("DASHBOARD_STATUS", 23, "dashboardStatus");
    DASHBOARD_SOUND = new Screen("DASHBOARD_SOUND", 24, "dashboardSound");
    DASHBOARD_SYSTEM = new Screen("DASHBOARD_SYSTEM", 25, "dashboardSystem");
    FW_CONFIRMATION = new Screen("FW_CONFIRMATION", 26, "fwConfirmation");
    FW_DOWNLOADING = new Screen("FW_DOWNLOADING", 27, "fwDownloading");
    FW_TRANSFERRING = new Screen("FW_TRANSFERRING", 28, "fwTransferring");
    FW_UPDATE_IN_PROGRESS = new Screen("FW_UPDATE_IN_PROGRESS", 29, "fwUpdateInProgress");
    FW_UPDATE_COMPLETION = new Screen("FW_UPDATE_COMPLETION", 30, "fwUpdateCompletion");
    FW_UPDATE_ABORTED = new Screen("FW_UPDATE_ABORTED", 31, "fwUpdateAborted");
    FW_TRANSFERRED = new Screen("FW_TRANSFERRED", 32, "fwTransferred");
    EQ_CUSTOM = new Screen("EQ_CUSTOM", 33, "eqCustom");
    ACTIVITY_RECOG_CUSTOM = new Screen("ACTIVITY_RECOG_CUSTOM", 34, "activityRecogCustom");
    APP_NOTIFICATION_SETTING = new Screen("APP_NOTIFICATION_SETTING", 35, "appNotificationSetting");
    NCOPT_PERSONAL_MEASURE = new Screen("NCOPT_PERSONAL_MEASURE", 36, "ncoptPersonalMeasure");
    NCOPT_BAROMETRIC_MEASURE = new Screen("NCOPT_BAROMETRIC_MEASURE", 37, "ncoptBarometricMeasure");
    NCOPT_OPTIMIZING = new Screen("NCOPT_OPTIMIZING", 38, "ncoptOptimizing");
    NCOPT_COMPLETE = new Screen("NCOPT_COMPLETE", 39, "ncoptComplete");
    TRAINING_MODE_CUSTOM = new Screen("TRAINING_MODE_CUSTOM", 40, "trainingModeCustom");
    TALKING_MODE_READY = new Screen("TALKING_MODE_READY", 41, "talkingModeReady");
    TALKING_MODE_ACTION = new Screen("TALKING_MODE_ACTION", 42, "talkingModeAction");
    TALKING_MODE_CUSTOM = new Screen("TALKING_MODE_CUSTOM", 43, "talkingModeCustom");
    VOICE_DATA_CONFIRMATION = new Screen("VOICE_DATA_CONFIRMATION", 44, "voiceDataConfirmation");
    VOICE_DATA_DOWNLOADING = new Screen("VOICE_DATA_DOWNLOADING", 45, "voiceDataDownloading");
    VOICE_DATA_TRANSFERRING = new Screen("VOICE_DATA_TRANSFERRING", 46, "voiceDataTransferring");
    VOICE_DATA_IN_PROGRESS = new Screen("VOICE_DATA_IN_PROGRESS", 47, "voiceDataInProgress");
    VOICE_DATA_COMPLETION = new Screen("VOICE_DATA_COMPLETION", 48, "voiceDataCompletion");
    INITIAL_SETUP_OVERALL_START = new Screen("INITIAL_SETUP_OVERALL_START", 49, "initialSetupOverallStart");
    INITIAL_SETUP_OVERALL_FINAL = new Screen("INITIAL_SETUP_OVERALL_FINAL", 50, "initialSetupOverallFinal");
    INITIAL_SETUP_OVERALL_COMPLETION = new Screen("INITIAL_SETUP_OVERALL_COMPLETION", 51, "initialSetupOverallCompletion");
    INITIAL_SETUP_ADAPTIVE_SETTING = new Screen("INITIAL_SETUP_ADAPTIVE_SETTING", 52, "initialSetupAdaptiveSetting");
    INITIAL_SETUP_ADAPTIVE_PLACE_LEARN_SETTING = new Screen("INITIAL_SETUP_ADAPTIVE_PLACE_LEARN_SETTING", 53, "initialSetupAdaptivePlaceLearnSetting");
    INITIAL_SETUP_ADAPTIVE_COMPLETION = new Screen("INITIAL_SETUP_ADAPTIVE_COMPLETION", 54, "initialSetupAdaptiveCompletion");
    IA_SETUP_INTRO_ENTRANCE = new Screen("IA_SETUP_INTRO_ENTRANCE", 55, "iaSetupIntroEntrance");
    IA_SETUP_INTRO_TRIAL_LISTENING = new Screen("IA_SETUP_INTRO_TRIAL_LISTENING", 56, "iaSetupIntroTrialListening");
    IA_SETUP_INTRO_SP_APP = new Screen("IA_SETUP_INTRO_SP_APP", 57, "iaSetupIntroSpApp");
    IA_SETUP_INTRO_CONFIRMATION = new Screen("IA_SETUP_INTRO_CONFIRMATION", 58, "iaSetupIntroConfirmation");
    IA_SETUP_ANALYSIS_INTRO = new Screen("IA_SETUP_ANALYSIS_INTRO", 59, "iaSetupAnalysisIntro");
    IA_SETUP_ANALYSIS_HOW_TO_TAKE = new Screen("IA_SETUP_ANALYSIS_HOW_TO_TAKE", 60, "iaSetupAnalysisHowToTake");
    IA_SETUP_ANALYSIS_CAMERA_LEFT_AUTO = new Screen("IA_SETUP_ANALYSIS_CAMERA_LEFT_AUTO", 61, "iaSetupAnalysisCameraLeftAuto");
    IA_SETUP_ANALYSIS_CAMERA_LEFT_MANUAL = new Screen("IA_SETUP_ANALYSIS_CAMERA_LEFT_MANUAL", 62, "iaSetupAnalysisCameraLeftManual");
    IA_SETUP_ANALYSIS_CAMERA_LEFT_EDIT = new Screen("IA_SETUP_ANALYSIS_CAMERA_LEFT_EDIT", 63, "iaSetupAnalysisCameraLeftEdit");
    IA_SETUP_ANALYSIS_CAMERA_LEFT_CONFIRMATION = new Screen("IA_SETUP_ANALYSIS_CAMERA_LEFT_CONFIRMATION", 64, "iaSetupAnalysisCameraLeftConfirmation");
    IA_SETUP_ANALYSIS_CAMERA_RIGHT_AUTO = new Screen("IA_SETUP_ANALYSIS_CAMERA_RIGHT_AUTO", 65, "iaSetupAnalysisCameraRightAuto");
    IA_SETUP_ANALYSIS_CAMERA_RIGHT_MANUAL = new Screen("IA_SETUP_ANALYSIS_CAMERA_RIGHT_MANUAL", 66, "iaSetupAnalysisCameraRightManual");
    IA_SETUP_ANALYSIS_CAMERA_RIGHT_EDIT = new Screen("IA_SETUP_ANALYSIS_CAMERA_RIGHT_EDIT", 67, "iaSetupAnalysisCameraRightEdit");
    IA_SETUP_ANALYSIS_CAMERA_RIGHT_CONFIRMATION = new Screen("IA_SETUP_ANALYSIS_CAMERA_RIGHT_CONFIRMATION", 68, "iaSetupAnalysisCameraRightConfirmation");
    IA_SETUP_ANALYSIS_PROGRESS = new Screen("IA_SETUP_ANALYSIS_PROGRESS", 69, "iaSetupAnalysisProgress");
    IA_SETUP_ANALYSIS_COMPLETED = new Screen("IA_SETUP_ANALYSIS_COMPLETED", 70, "iaSetupAnalysisCompleted");
    IA_SETUP_ANALYSIS_ERROR_CONFIRMATION = new Screen("IA_SETUP_ANALYSIS_ERROR_CONFIRMATION", 71, "iaSetupAnalysisErrorConfirmation");
    IA_SETUP_OPTIMIZE_APP_LIST = new Screen("IA_SETUP_OPTIMIZE_APP_LIST", 72, "iaSetupOptimizeAppList");
    IA_SETUP_OPTIMIZE_APP_SELECTED = new Screen("IA_SETUP_OPTIMIZE_APP_SELECTED", 73, "iaSetupOptimizeAppSelected");
    IA_SETUP_OPTIMIZE_COMPLETED = new Screen("IA_SETUP_OPTIMIZE_COMPLETED", 74, "iaSetupOptimizeCompleted");
    IA_SETUP_ANALYSIS_SIGNIN_FOR_HRTF = new Screen("IA_SETUP_ANALYSIS_SIGNIN_FOR_HRTF", 75, "iaSetupAnalysisSigninForHrtf");
    IA_SETUP_ANALYSIS_HRTF_APP_INTRO = new Screen("IA_SETUP_ANALYSIS_HRTF_APP_INTRO", 76, "iaSetupAnalysisHrtfAppIntro");
    IA_SETUP_ANALYSIS_SWITCH_HRTF_APP = new Screen("IA_SETUP_ANALYSIS_SWITCH_HRTF_APP", 77, "iaSetupAnalysisSwitchHrtfApp");
    IA_SETUP_ANALYSIS_HRTF_DOWNLOADING = new Screen("IA_SETUP_ANALYSIS_HRTF_DOWNLOADING", 78, "iaSetupAnalysisHrtfDownloading");
    ASSIGNABLE_SETTINGS_CUSTOM = new Screen("ASSIGNABLE_SETTINGS_CUSTOM", 79, "assignableSettingsCustom");
    PTOUR_CHANGE_EARPIECE = new Screen("PTOUR_CHANGE_EARPIECE", 80, "ptourChangeEarpiece");
    PTOUR_WEAR_EARPHONE = new Screen("PTOUR_WEAR_EARPHONE", 81, "ptourWearEarphone");
    PTOUR_PLAYBACK_BUTTON_OPERATION = new Screen("PTOUR_PLAYBACK_BUTTON_OPERATION", 82, "ptourPlaybackButtonOperation");
    PTOUR_TOUCH_PAD_OPERATION = new Screen("PTOUR_TOUCH_PAD_OPERATION", 83, "ptourTouchPadOperation");
    PTOUR_MAIN_BODY_OPERATION_1 = new Screen("PTOUR_MAIN_BODY_OPERATION_1", 84, "ptourMainBodyOperation1");
    PTOUR_MAIN_BODY_OPERATION_2 = new Screen("PTOUR_MAIN_BODY_OPERATION_2", 85, "ptourMainBodyOperation2");
    PTOUR_QUICK_ATTENTION = new Screen("PTOUR_QUICK_ATTENTION", 86, "ptourQuickAttention");
    PTOUR_ASSIGNABLE_BUTTON_SETTING = new Screen("PTOUR_ASSIGNABLE_BUTTON_SETTING", 87, "ptourAssignableButtonSetting");
    PTOUR_OFFLINE = new Screen("PTOUR_OFFLINE", 88, "ptourOffline");
    MULTIPOINT_DEVICE_SETTINGS = new Screen("MULTIPOINT_DEVICE_SETTINGS", 89, "multipointDeviceSettings");
    MULTIPOINT_ADDING_NEW_DEVICE = new Screen("MULTIPOINT_ADDING_NEW_DEVICE", 90, "multipointAddingNewDevice");
    MULTIPOINT_DEVICE_OPTIONS = new Screen("MULTIPOINT_DEVICE_OPTIONS", 91, "multipointDeviceOptions");
    ASC_TOP = new Screen("ASC_TOP", 92, "ascTop");
    ASC_SELECT_PLACE_POSITION = new Screen("ASC_SELECT_PLACE_POSITION", 93, "ascSelectPlacePosition");
    ASC_EDIT_PLACE_POSITION = new Screen("ASC_EDIT_PLACE_POSITION", 94, "ascEditPlacePosition");
    ASC_SELECT_PLACE_TYPE = new Screen("ASC_SELECT_PLACE_TYPE", 95, "ascSelectPlaceType");
    ASC_SELECT_LEARNED_PLACE = new Screen("ASC_SELECT_LEARNED_PLACE", 96, "ascSelectLearnedPlace");
    ASC_REGISTER_PLACE = new Screen("ASC_REGISTER_PLACE", 97, "ascRegisterPlace");
    ASC_PLACE_SETTING = new Screen("ASC_PLACE_SETTING", 98, "ascPlaceSetting");
    ASC_CUSTOM_SOUND_SETTING_PLACE = new Screen("ASC_CUSTOM_SOUND_SETTING_PLACE", 99, "ascCustomSoundSettingPlace");
    ASC_CUSTOM_SOUND_SETTING_SELECT_TARGET_ITEM = new Screen("ASC_CUSTOM_SOUND_SETTING_SELECT_TARGET_ITEM", 100, "ascCustomSoundSettingSelectTargetItem");
    ASC_CUSTOM_SOUND_SETTING_ACTIVITY_RECOGNITION = new Screen("ASC_CUSTOM_SOUND_SETTING_ACTIVITY_RECOGNITION", 101, "ascCustomSoundSettingActivityRecognition");
    TIPS_LIST = new Screen("TIPS_LIST", 102, "tipsList");
    TIPS_DETAIL_ASC_ENABLE_LOCATION_PERMISSION = new Screen("TIPS_DETAIL_ASC_ENABLE_LOCATION_PERMISSION", 103, "tipsDetailAscEnableLocationPermission");
    TIPS_DETAIL_ASC_ENABLE_PRECISE_LOCATION_PERMISSION = new Screen("TIPS_DETAIL_ASC_ENABLE_PRECISE_LOCATION_PERMISSION", 104, "tipsDetailAscEnablePreciseLocationPermission");
    TIPS_DETAIL_ASC_ENABLE_LOCATION_SETTING = new Screen("TIPS_DETAIL_ASC_ENABLE_LOCATION_SETTING", 105, "tipsDetailAscEnableLocationSetting");
    TIPS_DETAIL_ASC_ENABLE_PLACE_LEARNING = new Screen("TIPS_DETAIL_ASC_ENABLE_PLACE_LEARNING", 106, "tipsDetailAscEnablePlaceLearning");
    TIPS_DETAIL_ASC_ENABLE_NOTIFICATION_SETTING = new Screen("TIPS_DETAIL_ASC_ENABLE_NOTIFICATION_SETTING", 107, "tipsDetailAscEnableNotificationSetting");
    TIPS_DETAIL_IA_OPTIMIZE_SP_APP = new Screen("TIPS_DETAIL_IA_OPTIMIZE_SP_APP", 108, "tipsDetailIaOptimizeSpApp");
    SETTINGS_TAKE_OVER_INTRODUCTION = new Screen("SETTINGS_TAKE_OVER_INTRODUCTION", 109, "settingsTakeOverIntroduction");
    ACCOUNT_SETTINGS_INITIALIZE_PROGRESS = new Screen("ACCOUNT_SETTINGS_INITIALIZE_PROGRESS", 110, "accountSettingsInitializeProgress");
    ACCOUNT_SETTINGS_TOKEN_PROGRESS = new Screen("ACCOUNT_SETTINGS_TOKEN_PROGRESS", 111, "accountSettingsTokenProgress");
    SETTINGS_TAKE_OVER_INTRODUCTION_TIPS = new Screen("SETTINGS_TAKE_OVER_INTRODUCTION_TIPS", 112, "settingsTakeOverIntroductionTips");
    ACCOUNT_SETTINGS_BACKUP_PROGRESS = new Screen("ACCOUNT_SETTINGS_BACKUP_PROGRESS", 113, "accountSettingsBackupProgress");
    ACCOUNT_SETTINGS_AUTO_SYNC_INTRODUCTION = new Screen("ACCOUNT_SETTINGS_AUTO_SYNC_INTRODUCTION", 114, "accountSettingsAutoSyncIntroduction");
    ACCOUNT_SETTINGS_AUTO_SYNC_OFF = new Screen("ACCOUNT_SETTINGS_AUTO_SYNC_OFF", 115, "accountSettingsAutoSyncOff");
    ACCOUNT_SETTINGS_AUTO_SYNC_ON = new Screen("ACCOUNT_SETTINGS_AUTO_SYNC_ON", 116, "accountSettingsAutoSyncOn");
    ACCOUNT_SETTINGS_RESTORE_PROGRESS = new Screen("ACCOUNT_SETTINGS_RESTORE_PROGRESS", 117, "accountSettingsRestoreProgress");
    ACCOUNT_SETTINGS_RESTORE_NEWDEVICE = new Screen("ACCOUNT_SETTINGS_RESTORE_NEWDEVICE", 118, "accountSettingsRestoreNewDevice");
    ACCOUNT_SETTINGS_DETAIL_PAGE = new Screen("ACCOUNT_SETTINGS_DETAIL_PAGE", 119, "accountSettingsDetailPage");
    ACCOUNT_SETTINGS_TOS = new Screen("ACCOUNT_SETTINGS_TOS", 120, "accountSettingsTOS");
    INFORMATION_LIST = new Screen("INFORMATION_LIST", 121, "informationList");
    INFORMATION = new Screen("INFORMATION", 122, "information");
    QUESTIONNAIRE = new Screen("QUESTIONNAIRE", 123, "questionnaire");
    FEEDBACK_INFO = new Screen("FEEDBACK_INFO", 124, "feedbackInfo");
    OTHER_INFO = new Screen("OTHER_INFO", 125, "otherInfo");
    ESA_TOP = new Screen("ESA_TOP", 126, "esaTop");
    ESA_ABS_START_MEASURE = new Screen("ESA_ABS_START_MEASURE", 127, "esaAbsStartMeasure");
    ESA_ABS_MEASURING = new Screen("ESA_ABS_MEASURING", 128, "esaAbsMeasuring");
    ESA_ABS_MEASURING_ERROR = new Screen("ESA_ABS_MEASURING_ERROR", 129, "esaAbsMeasuringError");
    ESA_ABS_COMPLETE_OK = new Screen("ESA_ABS_COMPLETE_OK", 130, "esaAbsCompleteOk");
    ESA_ABS_COMPLETE_NG_BOTH = new Screen("ESA_ABS_COMPLETE_NG_BOTH", 131, "esaAbsCompleteNgBoth");
    ESA_ABS_COMPLETE_NG_RIGHT = new Screen("ESA_ABS_COMPLETE_NG_RIGHT", 132, "esaAbsCompleteNgRight");
    ESA_ABS_COMPLETE_NG_LEFT = new Screen("ESA_ABS_COMPLETE_NG_LEFT", 133, "esaAbsCompleteNgLeft");
    ESA_SIZE_SELECTION = new Screen("ESA_SIZE_SELECTION", 134, "esaSizeSelection");
    ESA_RELATIVE_START_MEASURE_1 = new Screen("ESA_RELATIVE_START_MEASURE_1", 135, "esaRelativeStartMeasure1");
    ESA_RELATIVE_START_MEASURE_2 = new Screen("ESA_RELATIVE_START_MEASURE_2", 136, "esaRelativeStartMeasure2");
    ESA_RELATIVE_START_MEASURE_3 = new Screen("ESA_RELATIVE_START_MEASURE_3", 137, "esaRelativeStartMeasure3");
    ESA_RELATIVE_MEASURING = new Screen("ESA_RELATIVE_MEASURING", 138, "esaRelativeMeasuring");
    ESA_RELATIVE_MEASURING_ERROR_1 = new Screen("ESA_RELATIVE_MEASURING_ERROR_1", 139, "esaRelativeMeasuringError1");
    ESA_RELATIVE_MEASURING_ERROR_2 = new Screen("ESA_RELATIVE_MEASURING_ERROR_2", 140, "esaRelativeMeasuringError2");
    ESA_RELATIVE_MEASURING_ERROR_3 = new Screen("ESA_RELATIVE_MEASURING_ERROR_3", 141, "esaRelativeMeasuringError3");
    ESA_RELATIVE_JUDGEMENT_ERROR = new Screen("ESA_RELATIVE_JUDGEMENT_ERROR", 142, "esaRelativeJudgementError");
    ESA_RELATIVE_JUDGEMENT_COMPLETE = new Screen("ESA_RELATIVE_JUDGEMENT_COMPLETE", 143, "esaRelativeJudgementComplete");
    RESET_SETTINGS_MENU = new Screen("RESET_SETTINGS_MENU", 144, "resetSettingsMenu");
    RESET_SETTINGS_RESET = new Screen("RESET_SETTINGS_RESET", 145, "resetSettingsReset");
    RESET_SETTINGS_FACTORY_RESET = new Screen("RESET_SETTINGS_FACTORY_RESET", 146, "resetSettingsFactoryReset");
    VOICE_ASSISTANT_SERVICELIST = new Screen("VOICE_ASSISTANT_SERVICELIST", 147, "voiceAssistantServiceList");
    AMAZON_ALEXA_SPLASH = new Screen("AMAZON_ALEXA_SPLASH", 148, "amazonAlexaSplash");
    AMAZON_ALEXA_THINGS_TO_TRY = new Screen("AMAZON_ALEXA_THINGS_TO_TRY", 149, "amazonAlexaThingsToTry");
    a = new Screen[] { 
        UNKNOWN, OTHER, NON_EXISTENCE, BACKGROUND, WELCOME, EULA, ABOUT_THIS_APP, ABOUT_LICENSE_INFORMATION, ADD_DEVICE, OOBE_NFC_PAIRING, 
        OOBE_MANUAL_PAIRING, OOBE_MANUAL_PAIRING_2, OOBE_PAIRING_COMPLETION, OOBE_PASSIVE_MDR_LIST, OOBE_POWER_ON, OOBE_PROXIMITY, OOBE_BLE_PAIRING, DEVICE_SETTING, CONNECTION_NONE, CONNECTION_PAIRED_DEVICE, 
        CONNECTION_DEVICE_LIST, CONNECTION_IN_PROGRESS, DASHBOARD, DASHBOARD_STATUS, DASHBOARD_SOUND, DASHBOARD_SYSTEM, FW_CONFIRMATION, FW_DOWNLOADING, FW_TRANSFERRING, FW_UPDATE_IN_PROGRESS, 
        FW_UPDATE_COMPLETION, FW_UPDATE_ABORTED, FW_TRANSFERRED, EQ_CUSTOM, ACTIVITY_RECOG_CUSTOM, APP_NOTIFICATION_SETTING, NCOPT_PERSONAL_MEASURE, NCOPT_BAROMETRIC_MEASURE, NCOPT_OPTIMIZING, NCOPT_COMPLETE, 
        TRAINING_MODE_CUSTOM, TALKING_MODE_READY, TALKING_MODE_ACTION, TALKING_MODE_CUSTOM, VOICE_DATA_CONFIRMATION, VOICE_DATA_DOWNLOADING, VOICE_DATA_TRANSFERRING, VOICE_DATA_IN_PROGRESS, VOICE_DATA_COMPLETION, INITIAL_SETUP_OVERALL_START, 
        INITIAL_SETUP_OVERALL_FINAL, INITIAL_SETUP_OVERALL_COMPLETION, INITIAL_SETUP_ADAPTIVE_SETTING, INITIAL_SETUP_ADAPTIVE_PLACE_LEARN_SETTING, INITIAL_SETUP_ADAPTIVE_COMPLETION, IA_SETUP_INTRO_ENTRANCE, IA_SETUP_INTRO_TRIAL_LISTENING, IA_SETUP_INTRO_SP_APP, IA_SETUP_INTRO_CONFIRMATION, IA_SETUP_ANALYSIS_INTRO, 
        IA_SETUP_ANALYSIS_HOW_TO_TAKE, IA_SETUP_ANALYSIS_CAMERA_LEFT_AUTO, IA_SETUP_ANALYSIS_CAMERA_LEFT_MANUAL, IA_SETUP_ANALYSIS_CAMERA_LEFT_EDIT, IA_SETUP_ANALYSIS_CAMERA_LEFT_CONFIRMATION, IA_SETUP_ANALYSIS_CAMERA_RIGHT_AUTO, IA_SETUP_ANALYSIS_CAMERA_RIGHT_MANUAL, IA_SETUP_ANALYSIS_CAMERA_RIGHT_EDIT, IA_SETUP_ANALYSIS_CAMERA_RIGHT_CONFIRMATION, IA_SETUP_ANALYSIS_PROGRESS, 
        IA_SETUP_ANALYSIS_COMPLETED, IA_SETUP_ANALYSIS_ERROR_CONFIRMATION, IA_SETUP_OPTIMIZE_APP_LIST, IA_SETUP_OPTIMIZE_APP_SELECTED, IA_SETUP_OPTIMIZE_COMPLETED, IA_SETUP_ANALYSIS_SIGNIN_FOR_HRTF, IA_SETUP_ANALYSIS_HRTF_APP_INTRO, IA_SETUP_ANALYSIS_SWITCH_HRTF_APP, IA_SETUP_ANALYSIS_HRTF_DOWNLOADING, ASSIGNABLE_SETTINGS_CUSTOM, 
        PTOUR_CHANGE_EARPIECE, PTOUR_WEAR_EARPHONE, PTOUR_PLAYBACK_BUTTON_OPERATION, PTOUR_TOUCH_PAD_OPERATION, PTOUR_MAIN_BODY_OPERATION_1, PTOUR_MAIN_BODY_OPERATION_2, PTOUR_QUICK_ATTENTION, PTOUR_ASSIGNABLE_BUTTON_SETTING, PTOUR_OFFLINE, MULTIPOINT_DEVICE_SETTINGS, 
        MULTIPOINT_ADDING_NEW_DEVICE, MULTIPOINT_DEVICE_OPTIONS, ASC_TOP, ASC_SELECT_PLACE_POSITION, ASC_EDIT_PLACE_POSITION, ASC_SELECT_PLACE_TYPE, ASC_SELECT_LEARNED_PLACE, ASC_REGISTER_PLACE, ASC_PLACE_SETTING, ASC_CUSTOM_SOUND_SETTING_PLACE, 
        ASC_CUSTOM_SOUND_SETTING_SELECT_TARGET_ITEM, ASC_CUSTOM_SOUND_SETTING_ACTIVITY_RECOGNITION, TIPS_LIST, TIPS_DETAIL_ASC_ENABLE_LOCATION_PERMISSION, TIPS_DETAIL_ASC_ENABLE_PRECISE_LOCATION_PERMISSION, TIPS_DETAIL_ASC_ENABLE_LOCATION_SETTING, TIPS_DETAIL_ASC_ENABLE_PLACE_LEARNING, TIPS_DETAIL_ASC_ENABLE_NOTIFICATION_SETTING, TIPS_DETAIL_IA_OPTIMIZE_SP_APP, SETTINGS_TAKE_OVER_INTRODUCTION, 
        ACCOUNT_SETTINGS_INITIALIZE_PROGRESS, ACCOUNT_SETTINGS_TOKEN_PROGRESS, SETTINGS_TAKE_OVER_INTRODUCTION_TIPS, ACCOUNT_SETTINGS_BACKUP_PROGRESS, ACCOUNT_SETTINGS_AUTO_SYNC_INTRODUCTION, ACCOUNT_SETTINGS_AUTO_SYNC_OFF, ACCOUNT_SETTINGS_AUTO_SYNC_ON, ACCOUNT_SETTINGS_RESTORE_PROGRESS, ACCOUNT_SETTINGS_RESTORE_NEWDEVICE, ACCOUNT_SETTINGS_DETAIL_PAGE, 
        ACCOUNT_SETTINGS_TOS, INFORMATION_LIST, INFORMATION, QUESTIONNAIRE, FEEDBACK_INFO, OTHER_INFO, ESA_TOP, ESA_ABS_START_MEASURE, ESA_ABS_MEASURING, ESA_ABS_MEASURING_ERROR, 
        ESA_ABS_COMPLETE_OK, ESA_ABS_COMPLETE_NG_BOTH, ESA_ABS_COMPLETE_NG_RIGHT, ESA_ABS_COMPLETE_NG_LEFT, ESA_SIZE_SELECTION, ESA_RELATIVE_START_MEASURE_1, ESA_RELATIVE_START_MEASURE_2, ESA_RELATIVE_START_MEASURE_3, ESA_RELATIVE_MEASURING, ESA_RELATIVE_MEASURING_ERROR_1, 
        ESA_RELATIVE_MEASURING_ERROR_2, ESA_RELATIVE_MEASURING_ERROR_3, ESA_RELATIVE_JUDGEMENT_ERROR, ESA_RELATIVE_JUDGEMENT_COMPLETE, RESET_SETTINGS_MENU, RESET_SETTINGS_RESET, RESET_SETTINGS_FACTORY_RESET, VOICE_ASSISTANT_SERVICELIST, AMAZON_ALEXA_SPLASH, AMAZON_ALEXA_THINGS_TO_TRY };
  }
  
  Screen(String paramString1) {
    this.mStrValue = paramString1;
  }
  
  public String getStrValue() {
    return this.mStrValue;
  }
}


/* Location:              /home/egaebel/Programs/sony-headphones-hack/base-dex2jar.jar!/com/sony/songpal/mdr/j2objc/actionlog/param/Screen.class
 * Java compiler version: 6 (50.0)
 * JD-Core Version:       1.1.3
 */