package com.sony.songpal.mdr.j2objc.actionlog.param;

public enum UIPart {
  ACCOUNT_SETTINGS_BACKUP_CONFIRMATION("unknown"),
  ACCOUNT_SETTINGS_BACKUP_SELECTION("unknown"),
  ACCOUNT_SETTINGS_INTRODUCTION_HELP("unknown"),
  ACCOUNT_SETTINGS_NOTHING_TO_RESTORE_HELP("unknown"),
  ACCOUNT_SETTINGS_RESTORE_CONFIRMATION("unknown"),
  ACCOUNT_SETTINGS_RESTORE_FROM_SERVER("unknown"),
  ACCOUNT_SETTINGS_RESTORE_HELP("unknown"),
  ACCOUNT_SETTINGS_RESTORE_SELECTION("unknown"),
  ACCOUNT_SETTINGS_SET_AS_NEW_DEVICE("unknown"),
  ACCOUNT_SETTINGS_TOS_ACCEPT("unknown"),
  ACCOUNT_SETTINGS_TOS_DECLINE("unknown"),
  AMAZON_ALEXA_INSTALL_CONFIRMATION_CANCEL("unknown"),
  AMAZON_ALEXA_INSTALL_CONFIRMATION_OK("unknown"),
  AMAZON_ALEXA_SPLASH_APP("unknown"),
  AMAZON_ALEXA_THINGS_TO_TRY_APP("unknown"),
  APP_UPDATE_CONFIRMATION_BEFORE_FW_UPDATE_CANCEL("unknown"),
  APP_UPDATE_CONFIRMATION_BEFORE_FW_UPDATE_HELP("unknown"),
  APP_UPDATE_CONFIRMATION_BEFORE_FW_UPDATE_OK("unknown"),
  APP_UPDATE_CONFIRMATION_CANCEL("unknown"),
  APP_UPDATE_CONFIRMATION_OK("unknown"),
  ASC_APPLY_SETTING_MANUALLY_BANNER_BUTTON("unknown"),
  ASC_APPLY_SETTING_MANUALLY_BUTTON("unknown"),
  ASC_CANCEL_SETTING_MANUALLY_BANNER_BUTTON("unknown"),
  ASC_CANCEL_SETTING_MANUALLY_BUTTON("unknown"),
  ASC_OS_NOTIFICATION_SETTING_OPEN("unknown"),
  ASC_REGISTER_PLACE_FROM_LEARNED_PLACE("unknown"),
  ASC_REGISTER_PLACE_FROM_MANUAL_POSITION("unknown"),
  ASC_REGISTER_PLACE_FROM_NOTIFICATION("unknown"),
  ASC_REGISTER_PLACE_FROM_TIPS("unknown"),
  ASC_SETTING_DETAIL_CLOSE("unknown"),
  ASC_SETTING_DETAIL_OPEN("unknown"),
  ASC_UNREGISTER_PLACE_CANCEL("unknown"),
  ASC_UNREGISTER_PLACE_OK("unknown"),
  BATTERY_CONSUMPTION_INCREASE_CONFIRMATION_CANCEL("unknown"),
  BATTERY_CONSUMPTION_INCREASE_CONFIRMATION_OK("unknown"),
  BLE_CONNECTION_ERROR_DIALOG_OK("unknown"),
  BOTTOM_SHEET_ABOUT_THIS_APP("unknown"),
  BOTTOM_SHEET_BACKUP_RESTORE("unknown"),
  BOTTOM_SHEET_HELP("unknown"),
  BOTTOM_SHEET_MC_LAUNCH("unknown"),
  BOTTOM_SHEET_MENU("unknown"),
  BOTTOM_SHEET_NOTIFICATION("unknown"),
  BOTTOM_SHEET_SELECT_DEVICE("unknown"),
  BT_ON_DIALOG_CANCEL("unknown"),
  BT_ON_DIALOG_OK("unknown"),
  CAMERA_PERMISSION_ALLOW("unknown"),
  CAMERA_PERMISSION_DENY_OR_NOTDISPLAYED("unknown"),
  CAMERA_PERMISSION_OS_SETTING_ALLOW("unknown"),
  CAMERA_PERMISSION_OS_SETTING_DENY_OR_CANCELLED("unknown"),
  CAMERA_PERMISSION_POST_EXPLANATION_DIALOG_CANCEL("unknown"),
  CAMERA_PERMISSION_POST_EXPLANATION_DIALOG_SETTING("unknown"),
  CAUTION_GPS_DIALOG_OK("unknown"),
  CAUTION_LOCATION_DIALOG_OK("unknown"),
  CHANGE_KEY_ASSIGN_CONFIRAMATION_CANCEL("unknown"),
  CHANGE_KEY_ASSIGN_CONFIRAMATION_OK("unknown"),
  CHANGE_VA_TO_ALEXA_CONFIRMATION_CANCEL("unknown"),
  CHANGE_VA_TO_ALEXA_CONFIRMATION_OK("unknown"),
  CHANGE_VA_TO_OTHER_CONFIRMATION_OK("unknown"),
  CHANGE_VOICE_ASSISTANT_BTN_WITH_LR_SELECT_CONFIRMATION_CANCEL("unknown"),
  CHANGE_VOICE_ASSISTANT_BTN_WITH_LR_SELECT_CONFIRMATION_LEFT("unknown"),
  CHANGE_VOICE_ASSISTANT_BTN_WITH_LR_SELECT_CONFIRMATION_RIGHT("unknown"),
  CHANGE_VOICE_ASSISTANT_CONFIRMATION_CANCEL("unknown"),
  CHANGE_VOICE_ASSISTANT_CONFIRMATION_OK("unknown"),
  CHANGE_VOICE_ASSISTANT_PANEL_CONFIRMATION_CANCEL("unknown"),
  CHANGE_VOICE_ASSISTANT_SENSOR_WITH_LR_SELECT_CONFIRMATION_CANCEL("unknown"),
  CHANGE_VOICE_ASSISTANT_SENSOR_WITH_LR_SELECT_CONFIRMATION_LEFT("unknown"),
  CHANGE_VOICE_ASSISTANT_SENSOR_WITH_LR_SELECT_CONFIRMATION_RIGHT("unknown"),
  CHANGE_VOICE_ASSiSTANT_PANEL_CONFIRMATION_OK("unknown"),
  CONNECTION_ERROR_DIALOG_OK("unknown"),
  CONNECT_MODE_CAUTION_CANCEL("unknown"),
  CONNECT_MODE_CAUTION_OK("unknown"),
  CONNECT_MODE_CONFIRMATION_CANCEL("unknown"),
  CONNECT_MODE_CONFIRMATION_OK("unknown"),
  CRADLE_BATTERY_ACTIVATE_CANCEL("unknown"),
  CRADLE_BATTERY_ACTIVATE_OK("unknown"),
  DEVICE_PAIRING_DIALOG_CANCEL("unknown"),
  DEVICE_PAIRING_DIALOG_OK("unknown"),
  DISABLE_TOUCH_PANEL_AND_RECONNECTION_CONFIRMATION_CANCEL("unknown"),
  DISABLE_TOUCH_PANEL_AND_RECONNECTION_CONFIRMATION_OK("unknown"),
  DISABLE_TOUCH_PANEL_CONFIRMATION_CANCEL("unknown"),
  DISABLE_TOUCH_PANEL_CONFIRMATION_OK("unknown"),
  ENABLE_TOUCH_PANEL_AND_RECONNECTION_CONFIRMATION_CANCEL("unknown"),
  ENABLE_TOUCH_PANEL_AND_RECONNECTION_CONFIRMATION_OK("unknown"),
  ENABLE_TOUCH_PANEL_CONFIRMATION_CANCEL("unknown"),
  ENABLE_TOUCH_PANEL_CONFIRMATION_OK("unknown"),
  ESA_ABS_COMPLETE_FINISH("unknown"),
  ESA_ABS_COMPLETE_RESTART("unknown"),
  ESA_ABS_MEASURING_CANCEL("unknown"),
  ESA_ABS_MEASURING_ERROR_FINISH("unknown"),
  ESA_ABS_MEASURING_ERROR_RESTART("unknown"),
  ESA_ABS_MEASURING_START("unknown"),
  ESA_ABS_NOT_WEARING_BACK("unknown"),
  ESA_ABS_START_FORCEFUL("unknown"),
  ESA_RELATIVE_JUDGEMENT_ERROR_FINISH("unknown"),
  ESA_RELATIVE_MEASURING_CANCEL("unknown"),
  ESA_RELATIVE_MEASURING_ERROR_RESTART("unknown"),
  ESA_RELATIVE_MEASURING_ERROR_SKIP("unknown"),
  ESA_RELATIVE_MEASURING_FINISH("unknown"),
  ESA_RELATIVE_MEASURING_START("unknown"),
  ESA_RELATIVE_NOT_WEARING_BACK("unknown"),
  ESA_RELATIVE_START_FORCEFUL("unknown"),
  FEEDBACK_INFO_CLOSE("unknown"),
  FEEDBACK_INFO_ITEM("unknown"),
  FW_ABORT_CONFIRMATION_BEFORE_MULTIPOINT_CONNECT_HISTORY_DEVICE_CANCEL("unknown"),
  FW_ABORT_CONFIRMATION_BEFORE_MULTIPOINT_CONNECT_HISTORY_DEVICE_OK("unknown"),
  FW_ABORT_CONFIRMATION_BEFORE_MULTIPOINT_PAIRING_CANCEL("unknown"),
  FW_ABORT_CONFIRMATION_BEFORE_MULTIPOINT_PAIRING_OK("unknown"),
  FW_ABORT_DIALOG_CANCEL("unknown"),
  FW_ABORT_DIALOG_OK("unknown"),
  FW_DATA_ERROR_DIALOG_OK("unknown"),
  FW_DOWNLOAD_ERROR_DIALOG_OK("unknown"),
  FW_INSTALL_ERROR_DIALOG_OK("unknown"),
  FW_MDR_BATTERY_POWER_DIALOG_OK("unknown"),
  FW_MOBILE_BATTERY_POWER_DIALOG_OK("unknown"),
  FW_TRANSFER_ERROR_DIALOG_OK("unknown"),
  FW_UPDATE_COMPETION_DIALOG_OK("unknown"),
  FW_UPDATE_RECOMMENDATION_OK("unknown"),
  FW_UPDATE_RETRY_CAUTION_CANCEL("unknown"),
  FW_UPDATE_RETRY_CAUTION_OK("unknown"),
  FW_VERSION_CONFIRMATION("unknown"),
  GPS_ON_DIALOG_CANCEL("unknown"),
  GPS_ON_DIALOG_OK("unknown"),
  IA_ALREADY_SAVED_HRTF_CANCEL("unknown"),
  IA_ALREADY_SAVED_HRTF_DOWNLOAD("unknown"),
  IA_CAMERA_MANUAL_CONFIRM_AUTO("unknown"),
  IA_CAMERA_MANUAL_CONFIRM_MANUAL("unknown"),
  IA_CARD_ANALYSIS("unknown"),
  IA_CARD_INFO("unknown"),
  IA_CARD_OPTIMIZATION("unknown"),
  IA_COUPON_DIALOG_CLOSE("unknown"),
  IA_COUPON_SITE_OPEN("unknown"),
  IA_DOUBLE_EFFECT_FLOW_CONFIRM_CANCEL("unknown"),
  IA_DOUBLE_EFFECT_FLOW_CONFIRM_OK("unknown"),
  IA_DOUBLE_EFFECT_TRIAL_LISTENING_CONFIRM_CANCEL("unknown"),
  IA_DOUBLE_EFFECT_TRIAL_LISTENING_CONFIRM_OK("unknown"),
  IA_GDPR_NOTICE_CANCEL("unknown"),
  IA_GDPR_NOTICE_OK("unknown"),
  IA_INSTALL_CONFIRM_CANCEL("unknown"),
  IA_INSTALL_CONFIRM_OK("unknown"),
  IA_OPEN_STORE_CONFIRMATION_CANCEL("unknown"),
  IA_OPEN_STORE_CONFIRMATION_OK("unknown"),
  IA_SETUP_ANALYSIS_HRTF_DOWNLOAD_MANUAL("unknown"),
  IA_SETUP_ANALYSIS_SIGNIN_LEARN_MORE("unknown"),
  IA_SETUP_ANALYSIS_SWITCH_HRTF_APP_MANUAL("unknown"),
  IA_SETUP_CAMERA_EDIT_HELP("unknown"),
  IA_SETUP_LEARN_MORE("unknown"),
  IA_SETUP_SELECT_SP_APP("unknown"),
  IA_SETUP_SKIP_CONFIRMATION_CANCEL("unknown"),
  IA_SETUP_SKIP_CONFIRMATION_OK("unknown"),
  IA_SETUP_SP_APP_INTRO_LEARN_MORE("unknown"),
  IA_SETUP_SP_APP_LIST_LEARN_MORE("unknown"),
  IA_SP_APP_INSTALL("unknown"),
  IA_SP_APP_OPTIMIZATION("unknown"),
  IA_SP_APP_RE_OPTIMIZATION("unknown"),
  IA_STEP_GDPR_NOTICE_OK("unknown"),
  IA_TRIAL_LISTENING_13CH("unknown"),
  IA_TRIAL_LISTENING_2CH("unknown"),
  INFORMATION_CLOSE("unknown"),
  INFORMATION_ITEM("unknown"),
  INITIAL_SETUP_ASC_LATER("unknown"),
  INITIAL_SETUP_ASC_OK("unknown"),
  INITIAL_SETUP_ASC_PLACE_LEARNING_LATER("unknown"),
  INITIAL_SETUP_ASC_PLACE_LEARNING_OK("unknown"),
  INITIAL_SETUP_LATER("unknown"),
  LOCATION_BACKGROUND_PERMISSION_ALLOW("unknown"),
  LOCATION_BACKGROUND_PERMISSION_DENY_OR_NOTDISPLAYED("unknown"),
  LOCATION_BACKGROUND_PERMISSION_POST_EXPLANATION_DIALOG_CANCEL("unknown"),
  LOCATION_BACKGROUND_PERMISSION_POST_EXPLANATION_DIALOG_SETTING("unknown"),
  LOCATION_FOREGROUND_PERMISSION_ALLOW("unknown"),
  LOCATION_FOREGROUND_PERMISSION_DENY_OR_NOTDISPLAYED("unknown"),
  LOCATION_FOREGROUND_PERMISSION_POST_EXPLANATION_DIALOG_CANCEL("unknown"),
  LOCATION_FOREGROUND_PERMISSION_POST_EXPLANATION_DIALOG_SETTING("unknown"),
  LOCATION_PERMISSION_OS_SETTING_BACKGROUND_ALLOW("unknown"),
  LOCATION_PERMISSION_OS_SETTING_DENY_OR_CANCELLED("unknown"),
  LOCATION_PERMISSION_OS_SETTING_FOREGROUND_ALLOW("unknown"),
  MULTIPOINT_ADDING_NEW_DEVICE("unknown"),
  MULTIPOINT_CONNECT_HISTORY_DEVICE("unknown"),
  MULTIPOINT_DELETE_CONNECTED_DEVICE("unknown"),
  MULTIPOINT_DELETE_CONNECTED_DEVICE_CANCEL("unknown"),
  MULTIPOINT_DELETE_CONNECTED_DEVICE_OK("unknown"),
  MULTIPOINT_DELETE_HISTORY_DEVICE("unknown"),
  MULTIPOINT_DELETE_HISTORY_DEVICE_CANCEL("unknown"),
  MULTIPOINT_DELETE_HISTORY_DEVICE_OK("unknown"),
  MULTIPOINT_DISCONNECT_CONFIRMATION_BEFORE_FW_UPDATE_CANCEL("unknown"),
  MULTIPOINT_DISCONNECT_CONFIRMATION_BEFORE_FW_UPDATE_OK("unknown"),
  MULTIPOINT_DISCONNECT_CONFIRMATION_BEFORE_VOICE_GUIDANCE_CANCEL("unknown"),
  MULTIPOINT_DISCONNECT_CONFIRMATION_BEFORE_VOICE_GUIDANCE_OK("unknown"),
  MULTIPOINT_DISCONNECT_DEVICE("unknown"),
  MULTIPOINT_DISCONNECT_DEVICE_CANCEL("unknown"),
  MULTIPOINT_DISCONNECT_DEVICE_OK("unknown"),
  MULTIPOINT_DISCONNECT_OWN_DEVICE("unknown"),
  MULTIPOINT_DISCONNECT_OWN_DEVICE_CANCEL("unknown"),
  MULTIPOINT_DISCONNECT_OWN_DEVICE_OK("unknown"),
  MULTIPOINT_PAIRING_HELP("unknown"),
  MULTI_POINT_SETTING_DISABLE_CONFIRMATION_CANCEL("unknown"),
  MULTI_POINT_SETTING_DISABLE_CONFIRMATION_OK("unknown"),
  MULTI_POINT_SETTING_ENABLE_CONFIRMATION_CANCEL("unknown"),
  MULTI_POINT_SETTING_ENABLE_CONFIRMATION_OK("unknown"),
  OTHER_INFO_CLOSE("unknown"),
  OTHER_INFO_ITEM("unknown"),
  POWER_OFF_DIALOG_CANCEL("unknown"),
  POWER_OFF_DIALOG_OK("unknown"),
  POWER_OFF_MENU("unknown"),
  PTOUR_MENU("unknown"),
  QUESTIONNAIRE_ANSWER("unknown"),
  QUESTIONNAIRE_CLOSE("unknown"),
  QUESTIONNAIRE_HOW_TO_DISPLAY_DIALOG_CLOSE("unknown"),
  QUESTIONNAIRE_ITEM("unknown"),
  RESET_SETTINGS_FACTORY_RESET("unknown"),
  SONGPAL_INSTALL_CONFIRMATION_CANCEL("unknown"),
  SONGPAL_INSTALL_CONFIRMATION_OK("unknown"),
  TALKING_MODE_CONFIRMATION_AFTER_TRIAL_NEGATIVE("unknown"),
  TALKING_MODE_CONFIRMATION_AFTER_TRIAL_POSITIVE("unknown"),
  TALKING_MODE_TURN_ON_CONFIRTATION_CANCEL("unknown"),
  TALKING_MODE_TURN_ON_CONFIRTATION_OK("unknown"),
  UNKNOWN("unknown"),
  VA_AMAZON_ALEXA_LEARN_MORE("unknown"),
  VA_BTN_DISABLE_AND_RECONNECTION_CONFIRMATION_CANCEL("unknown"),
  VA_BTN_DISABLE_AND_RECONNECTION_CONFIRMATION_OK("unknown"),
  VA_BTN_DISABLE_CONFIRMATION_CANCEL("unknown"),
  VA_BTN_DISABLE_CONFIRMATION_OK("unknown"),
  VA_BTN_ENABLE_AND_RECONNECTION_CONFIRMATION_CANCEL("unknown"),
  VA_BTN_ENABLE_AND_RECONNECTION_CONFIRMATION_OK("unknown"),
  VA_BTN_ENABLE_CONFIRMATION_CANCEL("unknown"),
  VA_BTN_ENABLE_CONFIRMATION_OK("unknown"),
  VA_GOOGLE_ASSISTANT_LEARN_MORE("unknown"),
  VA_SENSOR_DISABLE_AND_RECONNECTION_CONFIRMATION_CANCEL("unknown"),
  VA_SENSOR_DISABLE_AND_RECONNECTION_CONFIRMATION_OK("unknown"),
  VA_SENSOR_DISABLE_CONFIRMATION_CANCEL("unknown"),
  VA_SENSOR_DISABLE_CONFIRMATION_OK("unknown"),
  VA_SENSOR_ENABLE_AND_RECONNECTION_CONFIRMATION_CANCEL("unknown"),
  VA_SENSOR_ENABLE_AND_RECONNECTION_CONFIRMATION_OK("unknown"),
  VA_SENSOR_ENABLE_CONFIRMATION_CANCEL("unknown"),
  VA_SENSOR_ENABLE_CONFIRMATION_OK("unknown"),
  VA_TENCENT_XIAOWEI_LEARN_MORE("unknown"),
  VOICE_ASSISTANT_INTRODUCTION_AMAZON_ALEXA_LEARN_MORE("unknown"),
  VOICE_ASSISTANT_INTRODUCTION_CLOSE("unknown"),
  VOICE_ASSISTANT_INTRODUCTION_GOOGLE_ASSISTANT_LEARN_MORE("unknown"),
  VOICE_ASSISTANT_INTRODUCTION_SET("unknown"),
  VOICE_ASSISTANT_INTRODUCTION_TENCENT_XIAOWEI_LEARN_MORE("unknown"),
  VOICE_DATA_ABORT_DIALOG_CANCEL("unknown"),
  VOICE_DATA_ABORT_DIALOG_OK("unknown"),
  VOICE_DATA_DISCARD_FW_DIALOG_CANCEL("unknown"),
  VOICE_DATA_DISCARD_FW_DIALOG_OK("unknown"),
  WIDGET_CLEARBASS_CHANGE_HOME("unknown"),
  WIDGET_CLEARBASS_CHANGE_SIDESENSE("unknown"),
  WIDGET_EQ_CHANGE_HOME("unknown"),
  WIDGET_EQ_CHANGE_SIDESENSE("unknown"),
  WIDGET_LAUNCH_HPC_HOME("unknown"),
  WIDGET_LAUNCH_HPC_SIDESENSE("unknown");
  
  private final String mStrValue;
  
  static {
    CONNECTION_ERROR_DIALOG_OK = new UIPart("CONNECTION_ERROR_DIALOG_OK", 1, "connectionErrorDialogOk");
    SONGPAL_INSTALL_CONFIRMATION_OK = new UIPart("SONGPAL_INSTALL_CONFIRMATION_OK", 2, "songpalInstallConfirmationPositive");
    SONGPAL_INSTALL_CONFIRMATION_CANCEL = new UIPart("SONGPAL_INSTALL_CONFIRMATION_CANCEL", 3, "songpalInstallConfirmationNegative");
    APP_UPDATE_CONFIRMATION_OK = new UIPart("APP_UPDATE_CONFIRMATION_OK", 4, "appUpdateConfirmationPositive");
    APP_UPDATE_CONFIRMATION_CANCEL = new UIPart("APP_UPDATE_CONFIRMATION_CANCEL", 5, "appUpdateConfirmationNegative");
    FW_UPDATE_RECOMMENDATION_OK = new UIPart("FW_UPDATE_RECOMMENDATION_OK", 6, "fwUpdateRecommendationOk");
    FW_MDR_BATTERY_POWER_DIALOG_OK = new UIPart("FW_MDR_BATTERY_POWER_DIALOG_OK", 7, "fwMdrBatteryPowerDialogOk");
    FW_MOBILE_BATTERY_POWER_DIALOG_OK = new UIPart("FW_MOBILE_BATTERY_POWER_DIALOG_OK", 8, "fwMobileBatteryPowerDialogOk");
    FW_DATA_ERROR_DIALOG_OK = new UIPart("FW_DATA_ERROR_DIALOG_OK", 9, "fwDataErrorDialogOk");
    FW_DOWNLOAD_ERROR_DIALOG_OK = new UIPart("FW_DOWNLOAD_ERROR_DIALOG_OK", 10, "fwDownloadErrorDialogOk");
    FW_TRANSFER_ERROR_DIALOG_OK = new UIPart("FW_TRANSFER_ERROR_DIALOG_OK", 11, "fwTransferErrorDialogOk");
    FW_INSTALL_ERROR_DIALOG_OK = new UIPart("FW_INSTALL_ERROR_DIALOG_OK", 12, "fwInstallErrorDialogOk");
    FW_UPDATE_COMPETION_DIALOG_OK = new UIPart("FW_UPDATE_COMPETION_DIALOG_OK", 13, "fwUpdateCompletionDialogOk");
    CONNECT_MODE_CONFIRMATION_OK = new UIPart("CONNECT_MODE_CONFIRMATION_OK", 14, "connectModeConfirmationOk");
    CONNECT_MODE_CONFIRMATION_CANCEL = new UIPart("CONNECT_MODE_CONFIRMATION_CANCEL", 15, "connectModeConfirmationCancel");
    CONNECT_MODE_CAUTION_OK = new UIPart("CONNECT_MODE_CAUTION_OK", 16, "connectModeCautionOk");
    CONNECT_MODE_CAUTION_CANCEL = new UIPart("CONNECT_MODE_CAUTION_CANCEL", 17, "connectModeCautionCancel");
    CHANGE_KEY_ASSIGN_CONFIRAMATION_OK = new UIPart("CHANGE_KEY_ASSIGN_CONFIRAMATION_OK", 18, "changeKeyAssignConfirmationOk");
    CHANGE_KEY_ASSIGN_CONFIRAMATION_CANCEL = new UIPart("CHANGE_KEY_ASSIGN_CONFIRAMATION_CANCEL", 19, "changeKeyAssignConfirmationCancel");
    FW_VERSION_CONFIRMATION = new UIPart("FW_VERSION_CONFIRMATION", 20, "fwVersionConfirmation");
    FW_UPDATE_RETRY_CAUTION_OK = new UIPart("FW_UPDATE_RETRY_CAUTION_OK", 21, "fwUpdateRetryCautionOk");
    FW_UPDATE_RETRY_CAUTION_CANCEL = new UIPart("FW_UPDATE_RETRY_CAUTION_CANCEL", 22, "fwUpdateRetryCautionCancel");
    BLE_CONNECTION_ERROR_DIALOG_OK = new UIPart("BLE_CONNECTION_ERROR_DIALOG_OK", 23, "bleConnectionErrorDialogOk");
    FW_ABORT_DIALOG_OK = new UIPart("FW_ABORT_DIALOG_OK", 24, "fwAbortDialogOk");
    FW_ABORT_DIALOG_CANCEL = new UIPart("FW_ABORT_DIALOG_CANCEL", 25, "fwAbortDialogCancel");
    BT_ON_DIALOG_OK = new UIPart("BT_ON_DIALOG_OK", 26, "btOnDialogOk");
    BT_ON_DIALOG_CANCEL = new UIPart("BT_ON_DIALOG_CANCEL", 27, "btOnDialogCancel");
    CAUTION_LOCATION_DIALOG_OK = new UIPart("CAUTION_LOCATION_DIALOG_OK", 28, "cautionLocationDialogOk");
    CAUTION_GPS_DIALOG_OK = new UIPart("CAUTION_GPS_DIALOG_OK", 29, "cautionGpsDialogOk");
    GPS_ON_DIALOG_OK = new UIPart("GPS_ON_DIALOG_OK", 30, "gpsOnDialogOk");
    GPS_ON_DIALOG_CANCEL = new UIPart("GPS_ON_DIALOG_CANCEL", 31, "gpsOnDialogCancel");
    DEVICE_PAIRING_DIALOG_OK = new UIPart("DEVICE_PAIRING_DIALOG_OK", 32, "devicePairingDialogOk");
    DEVICE_PAIRING_DIALOG_CANCEL = new UIPart("DEVICE_PAIRING_DIALOG_CANCEL", 33, "devicePairingDialogCancel");
    VOICE_DATA_ABORT_DIALOG_OK = new UIPart("VOICE_DATA_ABORT_DIALOG_OK", 34, "voiceDataAbortDialogOk");
    VOICE_DATA_ABORT_DIALOG_CANCEL = new UIPart("VOICE_DATA_ABORT_DIALOG_CANCEL", 35, "voiceDataAbortDialogCancel");
    VOICE_DATA_DISCARD_FW_DIALOG_OK = new UIPart("VOICE_DATA_DISCARD_FW_DIALOG_OK", 36, "voiceDataDiscardFwDialogOk");
    VOICE_DATA_DISCARD_FW_DIALOG_CANCEL = new UIPart("VOICE_DATA_DISCARD_FW_DIALOG_CANCEL", 37, "voiceDataDiscardFwDialogCancel");
    POWER_OFF_DIALOG_OK = new UIPart("POWER_OFF_DIALOG_OK", 38, "powerOffDialogOk");
    POWER_OFF_DIALOG_CANCEL = new UIPart("POWER_OFF_DIALOG_CANCEL", 39, "powerOffDialogCancel");
    INITIAL_SETUP_LATER = new UIPart("INITIAL_SETUP_LATER", 40, "initialSetupLater");
    IA_TRIAL_LISTENING_2CH = new UIPart("IA_TRIAL_LISTENING_2CH", 41, "iaTrialListening2ch");
    IA_TRIAL_LISTENING_13CH = new UIPart("IA_TRIAL_LISTENING_13CH", 42, "iaTrialListening13ch");
    IA_SETUP_SELECT_SP_APP = new UIPart("IA_SETUP_SELECT_SP_APP", 43, "iaSetupSelectSpApp");
    IA_SETUP_LEARN_MORE = new UIPart("IA_SETUP_LEARN_MORE", 44, "iaSetupLearnMore");
    IA_SP_APP_RE_OPTIMIZATION = new UIPart("IA_SP_APP_RE_OPTIMIZATION", 45, "iaSpAppReOptimization");
    IA_SP_APP_OPTIMIZATION = new UIPart("IA_SP_APP_OPTIMIZATION", 46, "iaSpAppOptimization");
    IA_SP_APP_INSTALL = new UIPart("IA_SP_APP_INSTALL", 47, "iaSpAppInstall");
    IA_SETUP_SKIP_CONFIRMATION_OK = new UIPart("IA_SETUP_SKIP_CONFIRMATION_OK", 48, "iaSetupSkipConfirmationOk");
    IA_SETUP_SKIP_CONFIRMATION_CANCEL = new UIPart("IA_SETUP_SKIP_CONFIRMATION_CANCEL", 49, "iaSetupSkipConfirmationCancel");
    IA_OPEN_STORE_CONFIRMATION_OK = new UIPart("IA_OPEN_STORE_CONFIRMATION_OK", 50, "iaOpenStoreConfirmationOk");
    IA_OPEN_STORE_CONFIRMATION_CANCEL = new UIPart("IA_OPEN_STORE_CONFIRMATION_CANCEL", 51, "iaOpenStoreConfirmationCancel");
    IA_GDPR_NOTICE_OK = new UIPart("IA_GDPR_NOTICE_OK", 52, "iaGdprNoticeOk");
    IA_GDPR_NOTICE_CANCEL = new UIPart("IA_GDPR_NOTICE_CANCEL", 53, "iaGdprNoticeCancel");
    IA_CARD_INFO = new UIPart("IA_CARD_INFO", 54, "iaCardInfo");
    IA_CARD_ANALYSIS = new UIPart("IA_CARD_ANALYSIS", 55, "iaCardAnalysis");
    IA_CARD_OPTIMIZATION = new UIPart("IA_CARD_OPTIMIZATION", 56, "iaCardOptimization");
    IA_INSTALL_CONFIRM_OK = new UIPart("IA_INSTALL_CONFIRM_OK", 57, "IaInstallConfirmOk");
    IA_INSTALL_CONFIRM_CANCEL = new UIPart("IA_INSTALL_CONFIRM_CANCEL", 58, "IaInstallConfirmCancel");
    IA_SETUP_CAMERA_EDIT_HELP = new UIPart("IA_SETUP_CAMERA_EDIT_HELP", 59, "IaSetupCameraEditHelp");
    IA_SETUP_SP_APP_INTRO_LEARN_MORE = new UIPart("IA_SETUP_SP_APP_INTRO_LEARN_MORE", 60, "IaSetupSpAppIntroLearnMore");
    IA_SETUP_SP_APP_LIST_LEARN_MORE = new UIPart("IA_SETUP_SP_APP_LIST_LEARN_MORE", 61, "IaSetupSpAppListLearnMore");
    IA_CAMERA_MANUAL_CONFIRM_AUTO = new UIPart("IA_CAMERA_MANUAL_CONFIRM_AUTO", 62, "IaCameraManualConfirmAuto");
    IA_CAMERA_MANUAL_CONFIRM_MANUAL = new UIPart("IA_CAMERA_MANUAL_CONFIRM_MANUAL", 63, "IaCameraManualConfirmManual");
    IA_DOUBLE_EFFECT_FLOW_CONFIRM_OK = new UIPart("IA_DOUBLE_EFFECT_FLOW_CONFIRM_OK", 64, "IaDoubleEffectFlowConfirmOk");
    IA_DOUBLE_EFFECT_FLOW_CONFIRM_CANCEL = new UIPart("IA_DOUBLE_EFFECT_FLOW_CONFIRM_CANCEL", 65, "IaDoubleEffectFlowConfirmCancel");
    IA_DOUBLE_EFFECT_TRIAL_LISTENING_CONFIRM_OK = new UIPart("IA_DOUBLE_EFFECT_TRIAL_LISTENING_CONFIRM_OK", 66, "IaDoubleEffectTrialListeningConfirmOk");
    IA_DOUBLE_EFFECT_TRIAL_LISTENING_CONFIRM_CANCEL = new UIPart("IA_DOUBLE_EFFECT_TRIAL_LISTENING_CONFIRM_CANCEL", 67, "IaDoubleEffectTrialListeningConfirmCancel");
    IA_STEP_GDPR_NOTICE_OK = new UIPart("IA_STEP_GDPR_NOTICE_OK", 68, "IaStepGdprNoticeOk");
    IA_COUPON_SITE_OPEN = new UIPart("IA_COUPON_SITE_OPEN", 69, "IaCouponSiteOpen");
    IA_COUPON_DIALOG_CLOSE = new UIPart("IA_COUPON_DIALOG_CLOSE", 70, "IaCouponDialogClose");
    IA_ALREADY_SAVED_HRTF_DOWNLOAD = new UIPart("IA_ALREADY_SAVED_HRTF_DOWNLOAD", 71, "iaAlreadySavedHrtfDownload");
    IA_ALREADY_SAVED_HRTF_CANCEL = new UIPart("IA_ALREADY_SAVED_HRTF_CANCEL", 72, "iaAlreadySavedHrtfCancel");
    IA_SETUP_ANALYSIS_SIGNIN_LEARN_MORE = new UIPart("IA_SETUP_ANALYSIS_SIGNIN_LEARN_MORE", 73, "iaSetupAnalysisSigninLearnMore");
    IA_SETUP_ANALYSIS_SWITCH_HRTF_APP_MANUAL = new UIPart("IA_SETUP_ANALYSIS_SWITCH_HRTF_APP_MANUAL", 74, "iaSetupAnalysisSwitchHrtfAppManual");
    IA_SETUP_ANALYSIS_HRTF_DOWNLOAD_MANUAL = new UIPart("IA_SETUP_ANALYSIS_HRTF_DOWNLOAD_MANUAL", 75, "iaSetupAnalysisHrtfDownloadManual");
    CRADLE_BATTERY_ACTIVATE_OK = new UIPart("CRADLE_BATTERY_ACTIVATE_OK", 76, "cradleBatteryActivateOk");
    CRADLE_BATTERY_ACTIVATE_CANCEL = new UIPart("CRADLE_BATTERY_ACTIVATE_CANCEL", 77, "cradleBatteryActivateCancel");
    PTOUR_MENU = new UIPart("PTOUR_MENU", 78, "ptourMenu");
    QUESTIONNAIRE_ANSWER = new UIPart("QUESTIONNAIRE_ANSWER", 79, "questionnaireAnswer");
    QUESTIONNAIRE_CLOSE = new UIPart("QUESTIONNAIRE_CLOSE", 80, "questionnaireClose");
    QUESTIONNAIRE_HOW_TO_DISPLAY_DIALOG_CLOSE = new UIPart("QUESTIONNAIRE_HOW_TO_DISPLAY_DIALOG_CLOSE", 81, "questionnaireHowToDisplayDialogClose");
    TALKING_MODE_CONFIRMATION_AFTER_TRIAL_POSITIVE = new UIPart("TALKING_MODE_CONFIRMATION_AFTER_TRIAL_POSITIVE", 82, "talkingModeConfirmationAfterTrialPositive");
    TALKING_MODE_CONFIRMATION_AFTER_TRIAL_NEGATIVE = new UIPart("TALKING_MODE_CONFIRMATION_AFTER_TRIAL_NEGATIVE", 83, "talkingModeConfirmationAfterTrialNegative");
    TALKING_MODE_TURN_ON_CONFIRTATION_OK = new UIPart("TALKING_MODE_TURN_ON_CONFIRTATION_OK", 84, "talkingModeTurnOnConfirmationOk");
    TALKING_MODE_TURN_ON_CONFIRTATION_CANCEL = new UIPart("TALKING_MODE_TURN_ON_CONFIRTATION_CANCEL", 85, "talkingModeTurnOnConfirmationCancel");
    POWER_OFF_MENU = new UIPart("POWER_OFF_MENU", 86, "powerOffMenu");
    BOTTOM_SHEET_MENU = new UIPart("BOTTOM_SHEET_MENU", 87, "bottomSheetMenu");
    BOTTOM_SHEET_SELECT_DEVICE = new UIPart("BOTTOM_SHEET_SELECT_DEVICE", 88, "bottomSheetSelectDevice");
    BOTTOM_SHEET_NOTIFICATION = new UIPart("BOTTOM_SHEET_NOTIFICATION", 89, "bottomSheetNotification");
    BOTTOM_SHEET_MC_LAUNCH = new UIPart("BOTTOM_SHEET_MC_LAUNCH", 90, "bottomSheetMcLaunch");
    BOTTOM_SHEET_ABOUT_THIS_APP = new UIPart("BOTTOM_SHEET_ABOUT_THIS_APP", 91, "bottomSheetAboutThisApp");
    BOTTOM_SHEET_HELP = new UIPart("BOTTOM_SHEET_HELP", 92, "bottomSheetHelp");
    MULTI_POINT_SETTING_ENABLE_CONFIRMATION_OK = new UIPart("MULTI_POINT_SETTING_ENABLE_CONFIRMATION_OK", 93, "multipointSettingEnableConfirmationOk");
    MULTI_POINT_SETTING_ENABLE_CONFIRMATION_CANCEL = new UIPart("MULTI_POINT_SETTING_ENABLE_CONFIRMATION_CANCEL", 94, "multipointSettingEnableConfirmationCancel");
    MULTI_POINT_SETTING_DISABLE_CONFIRMATION_OK = new UIPart("MULTI_POINT_SETTING_DISABLE_CONFIRMATION_OK", 95, "multipointSettingDisableConfirmationOk");
    MULTI_POINT_SETTING_DISABLE_CONFIRMATION_CANCEL = new UIPart("MULTI_POINT_SETTING_DISABLE_CONFIRMATION_CANCEL", 96, "multipointSettingDisableConfirmationCancel");
    MULTIPOINT_ADDING_NEW_DEVICE = new UIPart("MULTIPOINT_ADDING_NEW_DEVICE", 97, "multipointAddingNewDevice");
    MULTIPOINT_PAIRING_HELP = new UIPart("MULTIPOINT_PAIRING_HELP", 98, "multipointPairingHelp");
    MULTIPOINT_CONNECT_HISTORY_DEVICE = new UIPart("MULTIPOINT_CONNECT_HISTORY_DEVICE", 99, "multipointConnectHistoryDevice");
    MULTIPOINT_DISCONNECT_OWN_DEVICE = new UIPart("MULTIPOINT_DISCONNECT_OWN_DEVICE", 100, "multipointDisconnectOwnDevice");
    MULTIPOINT_DISCONNECT_DEVICE = new UIPart("MULTIPOINT_DISCONNECT_DEVICE", 101, "multipointDisconnectDevice");
    MULTIPOINT_DISCONNECT_OWN_DEVICE_OK = new UIPart("MULTIPOINT_DISCONNECT_OWN_DEVICE_OK", 102, "multipointDisconnectOwnDeviceOk");
    MULTIPOINT_DISCONNECT_OWN_DEVICE_CANCEL = new UIPart("MULTIPOINT_DISCONNECT_OWN_DEVICE_CANCEL", 103, "multipointDisconnectOwnDeviceCancel");
    MULTIPOINT_DISCONNECT_DEVICE_OK = new UIPart("MULTIPOINT_DISCONNECT_DEVICE_OK", 104, "multipointDisconnectDeviceOk");
    MULTIPOINT_DISCONNECT_DEVICE_CANCEL = new UIPart("MULTIPOINT_DISCONNECT_DEVICE_CANCEL", 105, "multipointDisconnectDeviceCancel");
    MULTIPOINT_DELETE_CONNECTED_DEVICE = new UIPart("MULTIPOINT_DELETE_CONNECTED_DEVICE", 106, "multipointDeleteConnectedDevice");
    MULTIPOINT_DELETE_HISTORY_DEVICE = new UIPart("MULTIPOINT_DELETE_HISTORY_DEVICE", 107, "multipointDeleteHistoryDevice");
    MULTIPOINT_DELETE_CONNECTED_DEVICE_OK = new UIPart("MULTIPOINT_DELETE_CONNECTED_DEVICE_OK", 108, "multipointDeleteConnectedDeviceOk");
    MULTIPOINT_DELETE_CONNECTED_DEVICE_CANCEL = new UIPart("MULTIPOINT_DELETE_CONNECTED_DEVICE_CANCEL", 109, "multipointDeleteConnectedDeviceCancel");
    MULTIPOINT_DELETE_HISTORY_DEVICE_OK = new UIPart("MULTIPOINT_DELETE_HISTORY_DEVICE_OK", 110, "multipointDeleteHistoryDeviceOk");
    MULTIPOINT_DELETE_HISTORY_DEVICE_CANCEL = new UIPart("MULTIPOINT_DELETE_HISTORY_DEVICE_CANCEL", 111, "multipointDeleteHistoryDeviceCancel");
    MULTIPOINT_DISCONNECT_CONFIRMATION_BEFORE_FW_UPDATE_OK = new UIPart("MULTIPOINT_DISCONNECT_CONFIRMATION_BEFORE_FW_UPDATE_OK", 112, "multipointDisconnectConfirmationBeforeFwUpdateOk");
    MULTIPOINT_DISCONNECT_CONFIRMATION_BEFORE_FW_UPDATE_CANCEL = new UIPart("MULTIPOINT_DISCONNECT_CONFIRMATION_BEFORE_FW_UPDATE_CANCEL", 113, "multipointDisconnectConfirmationBeforeFwUpdateCancel");
    MULTIPOINT_DISCONNECT_CONFIRMATION_BEFORE_VOICE_GUIDANCE_OK = new UIPart("MULTIPOINT_DISCONNECT_CONFIRMATION_BEFORE_VOICE_GUIDANCE_OK", 114, "multipointDisconnectConfirmationBeforeVoiceGuidanceOk");
    MULTIPOINT_DISCONNECT_CONFIRMATION_BEFORE_VOICE_GUIDANCE_CANCEL = new UIPart("MULTIPOINT_DISCONNECT_CONFIRMATION_BEFORE_VOICE_GUIDANCE_CANCEL", 115, "multipointDisconnectConfirmationBeforeVoiceGuidanceCancel");
    FW_ABORT_CONFIRMATION_BEFORE_MULTIPOINT_PAIRING_OK = new UIPart("FW_ABORT_CONFIRMATION_BEFORE_MULTIPOINT_PAIRING_OK", 116, "fwAbortConfirmationBeforeMultipointPairingOk");
    FW_ABORT_CONFIRMATION_BEFORE_MULTIPOINT_PAIRING_CANCEL = new UIPart("FW_ABORT_CONFIRMATION_BEFORE_MULTIPOINT_PAIRING_CANCEL", 117, "fwAbortConfirmationBeforeMultipointPairingCancel");
    FW_ABORT_CONFIRMATION_BEFORE_MULTIPOINT_CONNECT_HISTORY_DEVICE_OK = new UIPart("FW_ABORT_CONFIRMATION_BEFORE_MULTIPOINT_CONNECT_HISTORY_DEVICE_OK", 118, "fwAbortConfirmationBeforeMultipointConnectHistoryDeviceOk");
    FW_ABORT_CONFIRMATION_BEFORE_MULTIPOINT_CONNECT_HISTORY_DEVICE_CANCEL = new UIPart("FW_ABORT_CONFIRMATION_BEFORE_MULTIPOINT_CONNECT_HISTORY_DEVICE_CANCEL", 119, "fwAbortConfirmationBeforeMultipointConnectHistoryDeviceCancel");
    APP_UPDATE_CONFIRMATION_BEFORE_FW_UPDATE_OK = new UIPart("APP_UPDATE_CONFIRMATION_BEFORE_FW_UPDATE_OK", 120, "appUpdateConfirmationBeforeFwUpdateOk");
    APP_UPDATE_CONFIRMATION_BEFORE_FW_UPDATE_CANCEL = new UIPart("APP_UPDATE_CONFIRMATION_BEFORE_FW_UPDATE_CANCEL", 121, "appUpdateConfirmationBeforeFwUpdateCancel");
    APP_UPDATE_CONFIRMATION_BEFORE_FW_UPDATE_HELP = new UIPart("APP_UPDATE_CONFIRMATION_BEFORE_FW_UPDATE_HELP", 122, "appUpdateConfirmationBeforeFwUpdateHelp");
    INITIAL_SETUP_ASC_OK = new UIPart("INITIAL_SETUP_ASC_OK", 123, "initialSetupAscOk");
    INITIAL_SETUP_ASC_LATER = new UIPart("INITIAL_SETUP_ASC_LATER", 124, "initalSetupAscLater");
    INITIAL_SETUP_ASC_PLACE_LEARNING_OK = new UIPart("INITIAL_SETUP_ASC_PLACE_LEARNING_OK", 125, "initalSetupAscPlaceLearningOK");
    INITIAL_SETUP_ASC_PLACE_LEARNING_LATER = new UIPart("INITIAL_SETUP_ASC_PLACE_LEARNING_LATER", 126, "initalSetupAscPlaceLearningLater");
    ASC_REGISTER_PLACE_FROM_MANUAL_POSITION = new UIPart("ASC_REGISTER_PLACE_FROM_MANUAL_POSITION", 127, "ascRegisterPlaceFromManualPosition");
    ASC_REGISTER_PLACE_FROM_LEARNED_PLACE = new UIPart("ASC_REGISTER_PLACE_FROM_LEARNED_PLACE", 128, "ascRegisterPlaceFromLearnedPlace");
    ASC_REGISTER_PLACE_FROM_TIPS = new UIPart("ASC_REGISTER_PLACE_FROM_TIPS", 129, "ascRegisterPlaceFromTips");
    ASC_REGISTER_PLACE_FROM_NOTIFICATION = new UIPart("ASC_REGISTER_PLACE_FROM_NOTIFICATION", 130, "ascRegisterPlaceFromNotification");
    ASC_UNREGISTER_PLACE_OK = new UIPart("ASC_UNREGISTER_PLACE_OK", 131, "ascUnregisterPlaceOk");
    ASC_UNREGISTER_PLACE_CANCEL = new UIPart("ASC_UNREGISTER_PLACE_CANCEL", 132, "ascUnregisterPlaceCancel");
    ASC_SETTING_DETAIL_OPEN = new UIPart("ASC_SETTING_DETAIL_OPEN", 133, "ascSettingDetailOpen");
    ASC_SETTING_DETAIL_CLOSE = new UIPart("ASC_SETTING_DETAIL_CLOSE", 134, "ascSettingDetailClose");
    ASC_OS_NOTIFICATION_SETTING_OPEN = new UIPart("ASC_OS_NOTIFICATION_SETTING_OPEN", 135, "ascOsNotificationSettingOpen");
    ASC_APPLY_SETTING_MANUALLY_BUTTON = new UIPart("ASC_APPLY_SETTING_MANUALLY_BUTTON", 136, "ascApplySettingManuallyButton");
    ASC_CANCEL_SETTING_MANUALLY_BUTTON = new UIPart("ASC_CANCEL_SETTING_MANUALLY_BUTTON", 137, "ascCancelSettingManuallyButton");
    ASC_APPLY_SETTING_MANUALLY_BANNER_BUTTON = new UIPart("ASC_APPLY_SETTING_MANUALLY_BANNER_BUTTON", 138, "ascApplySettingManuallyBannerButton");
    ASC_CANCEL_SETTING_MANUALLY_BANNER_BUTTON = new UIPart("ASC_CANCEL_SETTING_MANUALLY_BANNER_BUTTON", 139, "ascCancelSettingManuallyBannerButton");
    ACCOUNT_SETTINGS_BACKUP_SELECTION = new UIPart("ACCOUNT_SETTINGS_BACKUP_SELECTION", 140, "accountSettingsBackupSelection");
    ACCOUNT_SETTINGS_RESTORE_SELECTION = new UIPart("ACCOUNT_SETTINGS_RESTORE_SELECTION", 141, "accountSettingsRestoreSelection");
    ACCOUNT_SETTINGS_BACKUP_CONFIRMATION = new UIPart("ACCOUNT_SETTINGS_BACKUP_CONFIRMATION", 142, "accountSettingsBackupConfirmation");
    ACCOUNT_SETTINGS_RESTORE_CONFIRMATION = new UIPart("ACCOUNT_SETTINGS_RESTORE_CONFIRMATION", 143, "accountSettingsRestoreConfirmation");
    ACCOUNT_SETTINGS_INTRODUCTION_HELP = new UIPart("ACCOUNT_SETTINGS_INTRODUCTION_HELP", 144, "accountSettingsIntroductionHelp");
    ACCOUNT_SETTINGS_RESTORE_HELP = new UIPart("ACCOUNT_SETTINGS_RESTORE_HELP", 145, "accountSettingsRestoreHelp");
    ACCOUNT_SETTINGS_NOTHING_TO_RESTORE_HELP = new UIPart("ACCOUNT_SETTINGS_NOTHING_TO_RESTORE_HELP", 146, "accountSettingsNothingToRestoreHelp");
    ACCOUNT_SETTINGS_RESTORE_FROM_SERVER = new UIPart("ACCOUNT_SETTINGS_RESTORE_FROM_SERVER", 147, "accountSettingsRestoreFromServer");
    ACCOUNT_SETTINGS_SET_AS_NEW_DEVICE = new UIPart("ACCOUNT_SETTINGS_SET_AS_NEW_DEVICE", 148, "accountSettingsSetAsNewDevice");
    BOTTOM_SHEET_BACKUP_RESTORE = new UIPart("BOTTOM_SHEET_BACKUP_RESTORE", 149, "bottomSheetBackupRestore");
    ACCOUNT_SETTINGS_TOS_ACCEPT = new UIPart("ACCOUNT_SETTINGS_TOS_ACCEPT", 150, "accountSettingsAccept");
    ACCOUNT_SETTINGS_TOS_DECLINE = new UIPart("ACCOUNT_SETTINGS_TOS_DECLINE", 151, "accountSettingsDecline");
    BATTERY_CONSUMPTION_INCREASE_CONFIRMATION_OK = new UIPart("BATTERY_CONSUMPTION_INCREASE_CONFIRMATION_OK", 152, "batteryConsumptionIncreaseConfirmationOk");
    BATTERY_CONSUMPTION_INCREASE_CONFIRMATION_CANCEL = new UIPart("BATTERY_CONSUMPTION_INCREASE_CONFIRMATION_CANCEL", 153, "batteryConsumptionIncreaseConfirmationCancel");
    INFORMATION_CLOSE = new UIPart("INFORMATION_CLOSE", 154, "informationClose");
    FEEDBACK_INFO_CLOSE = new UIPart("FEEDBACK_INFO_CLOSE", 155, "feedbackInfoClose");
    OTHER_INFO_CLOSE = new UIPart("OTHER_INFO_CLOSE", 156, "otherInfoClose");
    INFORMATION_ITEM = new UIPart("INFORMATION_ITEM", 157, "informationItem");
    FEEDBACK_INFO_ITEM = new UIPart("FEEDBACK_INFO_ITEM", 158, "feedbackInfoItem");
    QUESTIONNAIRE_ITEM = new UIPart("QUESTIONNAIRE_ITEM", 159, "questionnaireItem");
    OTHER_INFO_ITEM = new UIPart("OTHER_INFO_ITEM", 160, "otherInfoItem");
    VA_GOOGLE_ASSISTANT_LEARN_MORE = new UIPart("VA_GOOGLE_ASSISTANT_LEARN_MORE", 161, "vaGoogleAssistantLearnMore");
    VA_AMAZON_ALEXA_LEARN_MORE = new UIPart("VA_AMAZON_ALEXA_LEARN_MORE", 162, "vaAmazonAlexaLearnMore");
    VA_TENCENT_XIAOWEI_LEARN_MORE = new UIPart("VA_TENCENT_XIAOWEI_LEARN_MORE", 163, "vaTencentXiaoweiLearnMore");
    CHANGE_VOICE_ASSISTANT_CONFIRMATION_OK = new UIPart("CHANGE_VOICE_ASSISTANT_CONFIRMATION_OK", 164, "changeVoiceAssistantConfirmationOk");
    CHANGE_VOICE_ASSISTANT_CONFIRMATION_CANCEL = new UIPart("CHANGE_VOICE_ASSISTANT_CONFIRMATION_CANCEL", 165, "changeVoiceAssistantConfirmationCancel");
    CHANGE_VOICE_ASSiSTANT_PANEL_CONFIRMATION_OK = new UIPart("CHANGE_VOICE_ASSiSTANT_PANEL_CONFIRMATION_OK", 166, "chengeVoiceAssistantPanelConfirmationOk");
    CHANGE_VOICE_ASSISTANT_PANEL_CONFIRMATION_CANCEL = new UIPart("CHANGE_VOICE_ASSISTANT_PANEL_CONFIRMATION_CANCEL", 167, "changeVoiceAssistantPanelConfirmationCancel");
    CHANGE_VOICE_ASSISTANT_BTN_WITH_LR_SELECT_CONFIRMATION_LEFT = new UIPart("CHANGE_VOICE_ASSISTANT_BTN_WITH_LR_SELECT_CONFIRMATION_LEFT", 168, "changeVoiceAssistantBtnWithLrSelectConfirmationLeft");
    CHANGE_VOICE_ASSISTANT_BTN_WITH_LR_SELECT_CONFIRMATION_RIGHT = new UIPart("CHANGE_VOICE_ASSISTANT_BTN_WITH_LR_SELECT_CONFIRMATION_RIGHT", 169, "changeVoiceAssistantBtnWithLrSelectConfirmationRight");
    CHANGE_VOICE_ASSISTANT_BTN_WITH_LR_SELECT_CONFIRMATION_CANCEL = new UIPart("CHANGE_VOICE_ASSISTANT_BTN_WITH_LR_SELECT_CONFIRMATION_CANCEL", 170, "changeVoiceAssistantBtnWithLrSelectConfirmationCancel");
    CHANGE_VOICE_ASSISTANT_SENSOR_WITH_LR_SELECT_CONFIRMATION_LEFT = new UIPart("CHANGE_VOICE_ASSISTANT_SENSOR_WITH_LR_SELECT_CONFIRMATION_LEFT", 171, "changeVoiceAssistantSensorWithLrSelectConfirmationLeft");
    CHANGE_VOICE_ASSISTANT_SENSOR_WITH_LR_SELECT_CONFIRMATION_RIGHT = new UIPart("CHANGE_VOICE_ASSISTANT_SENSOR_WITH_LR_SELECT_CONFIRMATION_RIGHT", 172, "changeVoiceAssistantSensorWithLrSelectConfirmationRight");
    CHANGE_VOICE_ASSISTANT_SENSOR_WITH_LR_SELECT_CONFIRMATION_CANCEL = new UIPart("CHANGE_VOICE_ASSISTANT_SENSOR_WITH_LR_SELECT_CONFIRMATION_CANCEL", 173, "changeVoiceAssistantSensorWithLrSelectConfirmationCancel");
    VA_SENSOR_DISABLE_AND_RECONNECTION_CONFIRMATION_OK = new UIPart("VA_SENSOR_DISABLE_AND_RECONNECTION_CONFIRMATION_OK", 174, "vaSensorDisableAndReconnectionConfirmationOk");
    VA_SENSOR_DISABLE_AND_RECONNECTION_CONFIRMATION_CANCEL = new UIPart("VA_SENSOR_DISABLE_AND_RECONNECTION_CONFIRMATION_CANCEL", 175, "vaSensorDisableAndReconnectionConfirmationCancel");
    VA_SENSOR_ENABLE_AND_RECONNECTION_CONFIRMATION_OK = new UIPart("VA_SENSOR_ENABLE_AND_RECONNECTION_CONFIRMATION_OK", 176, "vaSensorEnableAndReconnectionConfirmationOk");
    VA_SENSOR_ENABLE_AND_RECONNECTION_CONFIRMATION_CANCEL = new UIPart("VA_SENSOR_ENABLE_AND_RECONNECTION_CONFIRMATION_CANCEL", 177, "vaSensorEnableAndReconnectionConfirmationCancel");
    VA_BTN_DISABLE_AND_RECONNECTION_CONFIRMATION_OK = new UIPart("VA_BTN_DISABLE_AND_RECONNECTION_CONFIRMATION_OK", 178, "vaBtnDisableAndReconnectionConfirmationOk");
    VA_BTN_DISABLE_AND_RECONNECTION_CONFIRMATION_CANCEL = new UIPart("VA_BTN_DISABLE_AND_RECONNECTION_CONFIRMATION_CANCEL", 179, "vaBtnDisableAndReconnectionConfirmationCancel");
    VA_BTN_ENABLE_AND_RECONNECTION_CONFIRMATION_OK = new UIPart("VA_BTN_ENABLE_AND_RECONNECTION_CONFIRMATION_OK", 180, "vaBtnEnableAndReconnectionConfirmationOk");
    VA_BTN_ENABLE_AND_RECONNECTION_CONFIRMATION_CANCEL = new UIPart("VA_BTN_ENABLE_AND_RECONNECTION_CONFIRMATION_CANCEL", 181, "vaBtnEnableAndReconnectionConfirmationCancel");
    VA_SENSOR_DISABLE_CONFIRMATION_OK = new UIPart("VA_SENSOR_DISABLE_CONFIRMATION_OK", 182, "vaSensorDisableConfirmationOk");
    VA_SENSOR_DISABLE_CONFIRMATION_CANCEL = new UIPart("VA_SENSOR_DISABLE_CONFIRMATION_CANCEL", 183, "vaSensorDisableConfirmationCancel");
    VA_SENSOR_ENABLE_CONFIRMATION_OK = new UIPart("VA_SENSOR_ENABLE_CONFIRMATION_OK", 184, "vaSensorEnableConfirmationOk");
    VA_SENSOR_ENABLE_CONFIRMATION_CANCEL = new UIPart("VA_SENSOR_ENABLE_CONFIRMATION_CANCEL", 185, "vaSensorEnableConfirmationCancel");
    VA_BTN_DISABLE_CONFIRMATION_OK = new UIPart("VA_BTN_DISABLE_CONFIRMATION_OK", 186, "vaBtnDisableConfirmationOk");
    VA_BTN_DISABLE_CONFIRMATION_CANCEL = new UIPart("VA_BTN_DISABLE_CONFIRMATION_CANCEL", 187, "vaBtnDisableConfirmationCancel");
    VA_BTN_ENABLE_CONFIRMATION_OK = new UIPart("VA_BTN_ENABLE_CONFIRMATION_OK", 188, "vaBtnEnableConfirmationOk");
    VA_BTN_ENABLE_CONFIRMATION_CANCEL = new UIPart("VA_BTN_ENABLE_CONFIRMATION_CANCEL", 189, "vaBtnEnableConfirmationCancel");
    DISABLE_TOUCH_PANEL_CONFIRMATION_OK = new UIPart("DISABLE_TOUCH_PANEL_CONFIRMATION_OK", 190, "disableTouchPanelConfirmationOk");
    DISABLE_TOUCH_PANEL_CONFIRMATION_CANCEL = new UIPart("DISABLE_TOUCH_PANEL_CONFIRMATION_CANCEL", 191, "disableTouchPanelConfirmationCancel");
    ENABLE_TOUCH_PANEL_CONFIRMATION_OK = new UIPart("ENABLE_TOUCH_PANEL_CONFIRMATION_OK", 192, "enableTouchPanelConfirmationOk");
    ENABLE_TOUCH_PANEL_CONFIRMATION_CANCEL = new UIPart("ENABLE_TOUCH_PANEL_CONFIRMATION_CANCEL", 193, "enableTouchPanelConfirmationCancel");
    DISABLE_TOUCH_PANEL_AND_RECONNECTION_CONFIRMATION_OK = new UIPart("DISABLE_TOUCH_PANEL_AND_RECONNECTION_CONFIRMATION_OK", 194, "disableTouchPanelAndReconnectionConfirmationOk");
    DISABLE_TOUCH_PANEL_AND_RECONNECTION_CONFIRMATION_CANCEL = new UIPart("DISABLE_TOUCH_PANEL_AND_RECONNECTION_CONFIRMATION_CANCEL", 195, "disableTouchPanelAndReconnectionConfirmationCancel");
    ENABLE_TOUCH_PANEL_AND_RECONNECTION_CONFIRMATION_OK = new UIPart("ENABLE_TOUCH_PANEL_AND_RECONNECTION_CONFIRMATION_OK", 196, "enableTouchPanelAndReconnectionConfirmationOk");
    ENABLE_TOUCH_PANEL_AND_RECONNECTION_CONFIRMATION_CANCEL = new UIPart("ENABLE_TOUCH_PANEL_AND_RECONNECTION_CONFIRMATION_CANCEL", 197, "enableTouchPanelAndReconnectionConfirmationCancel");
    LOCATION_BACKGROUND_PERMISSION_POST_EXPLANATION_DIALOG_SETTING = new UIPart("LOCATION_BACKGROUND_PERMISSION_POST_EXPLANATION_DIALOG_SETTING", 198, "locationBackgroundPermissionPostExplanationDialogSetting");
    LOCATION_BACKGROUND_PERMISSION_POST_EXPLANATION_DIALOG_CANCEL = new UIPart("LOCATION_BACKGROUND_PERMISSION_POST_EXPLANATION_DIALOG_CANCEL", 199, "locationBackgroundPermissionPostExplanationDialogCancel");
    LOCATION_FOREGROUND_PERMISSION_POST_EXPLANATION_DIALOG_SETTING = new UIPart("LOCATION_FOREGROUND_PERMISSION_POST_EXPLANATION_DIALOG_SETTING", 200, "locationForegroundPermissionPostExplanationDialogSetting");
    LOCATION_FOREGROUND_PERMISSION_POST_EXPLANATION_DIALOG_CANCEL = new UIPart("LOCATION_FOREGROUND_PERMISSION_POST_EXPLANATION_DIALOG_CANCEL", 201, "locationForegroundPermissionPostExplanationDialogCancel");
    LOCATION_FOREGROUND_PERMISSION_ALLOW = new UIPart("LOCATION_FOREGROUND_PERMISSION_ALLOW", 202, "locationForegroundPermissionAllow");
    LOCATION_FOREGROUND_PERMISSION_DENY_OR_NOTDISPLAYED = new UIPart("LOCATION_FOREGROUND_PERMISSION_DENY_OR_NOTDISPLAYED", 203, "locationForegroundPermissionDenyOrNotdisplayed");
    LOCATION_BACKGROUND_PERMISSION_ALLOW = new UIPart("LOCATION_BACKGROUND_PERMISSION_ALLOW", 204, "locationBackgroundPermissionAllow");
    LOCATION_BACKGROUND_PERMISSION_DENY_OR_NOTDISPLAYED = new UIPart("LOCATION_BACKGROUND_PERMISSION_DENY_OR_NOTDISPLAYED", 205, "locationBackgroundPermissionDenyOrNotdisplayed");
    LOCATION_PERMISSION_OS_SETTING_FOREGROUND_ALLOW = new UIPart("LOCATION_PERMISSION_OS_SETTING_FOREGROUND_ALLOW", 206, "locationPermissionOsSettingForegroundAllow");
    LOCATION_PERMISSION_OS_SETTING_BACKGROUND_ALLOW = new UIPart("LOCATION_PERMISSION_OS_SETTING_BACKGROUND_ALLOW", 207, "locationPermissionOsSettingBackgroundAllow");
    LOCATION_PERMISSION_OS_SETTING_DENY_OR_CANCELLED = new UIPart("LOCATION_PERMISSION_OS_SETTING_DENY_OR_CANCELLED", 208, "locationPermissionOsSettingDenyOrCancelled");
    CAMERA_PERMISSION_POST_EXPLANATION_DIALOG_SETTING = new UIPart("CAMERA_PERMISSION_POST_EXPLANATION_DIALOG_SETTING", 209, "cameraPermissionPostExplanationDialogSetting");
    CAMERA_PERMISSION_POST_EXPLANATION_DIALOG_CANCEL = new UIPart("CAMERA_PERMISSION_POST_EXPLANATION_DIALOG_CANCEL", 210, "cameraPermissionPostExplanationDialogCancel");
    CAMERA_PERMISSION_DENY_OR_NOTDISPLAYED = new UIPart("CAMERA_PERMISSION_DENY_OR_NOTDISPLAYED", 211, "cameraPermissionDenyOrNotdisplayed");
    CAMERA_PERMISSION_ALLOW = new UIPart("CAMERA_PERMISSION_ALLOW", 212, "cameraPermissionAllow");
    CAMERA_PERMISSION_OS_SETTING_ALLOW = new UIPart("CAMERA_PERMISSION_OS_SETTING_ALLOW", 213, "cameraPermissionOsSettingAllow");
    CAMERA_PERMISSION_OS_SETTING_DENY_OR_CANCELLED = new UIPart("CAMERA_PERMISSION_OS_SETTING_DENY_OR_CANCELLED", 214, "cameraPermissionOsSettingDenyOrCancelled");
    WIDGET_LAUNCH_HPC_HOME = new UIPart("WIDGET_LAUNCH_HPC_HOME", 215, "widgetLaunchHpcHome");
    WIDGET_LAUNCH_HPC_SIDESENSE = new UIPart("WIDGET_LAUNCH_HPC_SIDESENSE", 216, "widgetLaunchHpcSideSense");
    WIDGET_EQ_CHANGE_HOME = new UIPart("WIDGET_EQ_CHANGE_HOME", 217, "widgetEqChangeHome");
    WIDGET_EQ_CHANGE_SIDESENSE = new UIPart("WIDGET_EQ_CHANGE_SIDESENSE", 218, "widgetEqChangeSideSense");
    WIDGET_CLEARBASS_CHANGE_HOME = new UIPart("WIDGET_CLEARBASS_CHANGE_HOME", 219, "widgetClearBassChangeHome");
    WIDGET_CLEARBASS_CHANGE_SIDESENSE = new UIPart("WIDGET_CLEARBASS_CHANGE_SIDESENSE", 220, "widgetClearBassChangeSideSense");
    ESA_ABS_MEASURING_START = new UIPart("ESA_ABS_MEASURING_START", 221, "esaAbsMeasuringStart");
    ESA_ABS_START_FORCEFUL = new UIPart("ESA_ABS_START_FORCEFUL", 222, "esaAbsStartForceful");
    ESA_ABS_NOT_WEARING_BACK = new UIPart("ESA_ABS_NOT_WEARING_BACK", 223, "esaAbsNotWearingBack");
    ESA_ABS_MEASURING_CANCEL = new UIPart("ESA_ABS_MEASURING_CANCEL", 224, "esaAbsMeasuringCancel");
    ESA_ABS_MEASURING_ERROR_RESTART = new UIPart("ESA_ABS_MEASURING_ERROR_RESTART", 225, "esaAbsMeasuringErrorRestart");
    ESA_ABS_MEASURING_ERROR_FINISH = new UIPart("ESA_ABS_MEASURING_ERROR_FINISH", 226, "esaAbsMeasuringErrorFinish");
    ESA_ABS_COMPLETE_RESTART = new UIPart("ESA_ABS_COMPLETE_RESTART", 227, "esaAbsCompleteRestart");
    ESA_ABS_COMPLETE_FINISH = new UIPart("ESA_ABS_COMPLETE_FINISH", 228, "esaAbsCompleteFinish");
    ESA_RELATIVE_MEASURING_START = new UIPart("ESA_RELATIVE_MEASURING_START", 229, "esaRelativeMeasuringStart");
    ESA_RELATIVE_MEASURING_FINISH = new UIPart("ESA_RELATIVE_MEASURING_FINISH", 230, "esaRelativeMeasuringFinish");
    ESA_RELATIVE_START_FORCEFUL = new UIPart("ESA_RELATIVE_START_FORCEFUL", 231, "esaRelativeStartForceful");
    ESA_RELATIVE_NOT_WEARING_BACK = new UIPart("ESA_RELATIVE_NOT_WEARING_BACK", 232, "esaRelativeNotWearingBack");
    ESA_RELATIVE_MEASURING_CANCEL = new UIPart("ESA_RELATIVE_MEASURING_CANCEL", 233, "esaRelativeMeasuringCancel");
    ESA_RELATIVE_MEASURING_ERROR_RESTART = new UIPart("ESA_RELATIVE_MEASURING_ERROR_RESTART", 234, "esaRelativeMeasuringErrorRestart");
    ESA_RELATIVE_MEASURING_ERROR_SKIP = new UIPart("ESA_RELATIVE_MEASURING_ERROR_SKIP", 235, "esaRelativeMeasuringErrorSkip");
    ESA_RELATIVE_JUDGEMENT_ERROR_FINISH = new UIPart("ESA_RELATIVE_JUDGEMENT_ERROR_FINISH", 236, "esaRelativeJudgementErrorFinish");
    RESET_SETTINGS_FACTORY_RESET = new UIPart("RESET_SETTINGS_FACTORY_RESET", 237, "resetSettingsFactoryReset");
    CHANGE_VA_TO_ALEXA_CONFIRMATION_OK = new UIPart("CHANGE_VA_TO_ALEXA_CONFIRMATION_OK", 238, "changeVaToAlexaConfirmationOk");
    CHANGE_VA_TO_ALEXA_CONFIRMATION_CANCEL = new UIPart("CHANGE_VA_TO_ALEXA_CONFIRMATION_CANCEL", 239, "changeVaToAlexaConfirmationCancel");
    CHANGE_VA_TO_OTHER_CONFIRMATION_OK = new UIPart("CHANGE_VA_TO_OTHER_CONFIRMATION_OK", 240, "changeVaToOtherConfirmationOk");
    VOICE_ASSISTANT_INTRODUCTION_GOOGLE_ASSISTANT_LEARN_MORE = new UIPart("VOICE_ASSISTANT_INTRODUCTION_GOOGLE_ASSISTANT_LEARN_MORE", 241, "voiceAssistantIntroductionGoogleAssistantLearnMore");
    VOICE_ASSISTANT_INTRODUCTION_AMAZON_ALEXA_LEARN_MORE = new UIPart("VOICE_ASSISTANT_INTRODUCTION_AMAZON_ALEXA_LEARN_MORE", 242, "voiceAssistantIntroductionAmazonAlexaLearnMore");
    VOICE_ASSISTANT_INTRODUCTION_TENCENT_XIAOWEI_LEARN_MORE = new UIPart("VOICE_ASSISTANT_INTRODUCTION_TENCENT_XIAOWEI_LEARN_MORE", 243, "voiceAssistantIntroductionTencentXiaoweiLearnMore");
    AMAZON_ALEXA_INSTALL_CONFIRMATION_OK = new UIPart("AMAZON_ALEXA_INSTALL_CONFIRMATION_OK", 244, "amazonAlexaInstallConfirmationOk");
    AMAZON_ALEXA_INSTALL_CONFIRMATION_CANCEL = new UIPart("AMAZON_ALEXA_INSTALL_CONFIRMATION_CANCEL", 245, "amazonAlexaInstallConfirmationCancel");
    VOICE_ASSISTANT_INTRODUCTION_SET = new UIPart("VOICE_ASSISTANT_INTRODUCTION_SET", 246, "voiceAssistantIntroductionSet");
    VOICE_ASSISTANT_INTRODUCTION_CLOSE = new UIPart("VOICE_ASSISTANT_INTRODUCTION_CLOSE", 247, "voiceAssistantIntroductionClose");
    AMAZON_ALEXA_SPLASH_APP = new UIPart("AMAZON_ALEXA_SPLASH_APP", 248, "amazonAlexaSplashApp");
    AMAZON_ALEXA_THINGS_TO_TRY_APP = new UIPart("AMAZON_ALEXA_THINGS_TO_TRY_APP", 249, "amazonAlexaThingsToTryApp");
    a = new UIPart[] { 
        UNKNOWN, CONNECTION_ERROR_DIALOG_OK, SONGPAL_INSTALL_CONFIRMATION_OK, SONGPAL_INSTALL_CONFIRMATION_CANCEL, APP_UPDATE_CONFIRMATION_OK, APP_UPDATE_CONFIRMATION_CANCEL, FW_UPDATE_RECOMMENDATION_OK, FW_MDR_BATTERY_POWER_DIALOG_OK, FW_MOBILE_BATTERY_POWER_DIALOG_OK, FW_DATA_ERROR_DIALOG_OK, 
        FW_DOWNLOAD_ERROR_DIALOG_OK, FW_TRANSFER_ERROR_DIALOG_OK, FW_INSTALL_ERROR_DIALOG_OK, FW_UPDATE_COMPETION_DIALOG_OK, CONNECT_MODE_CONFIRMATION_OK, CONNECT_MODE_CONFIRMATION_CANCEL, CONNECT_MODE_CAUTION_OK, CONNECT_MODE_CAUTION_CANCEL, CHANGE_KEY_ASSIGN_CONFIRAMATION_OK, CHANGE_KEY_ASSIGN_CONFIRAMATION_CANCEL, 
        FW_VERSION_CONFIRMATION, FW_UPDATE_RETRY_CAUTION_OK, FW_UPDATE_RETRY_CAUTION_CANCEL, BLE_CONNECTION_ERROR_DIALOG_OK, FW_ABORT_DIALOG_OK, FW_ABORT_DIALOG_CANCEL, BT_ON_DIALOG_OK, BT_ON_DIALOG_CANCEL, CAUTION_LOCATION_DIALOG_OK, CAUTION_GPS_DIALOG_OK, 
        GPS_ON_DIALOG_OK, GPS_ON_DIALOG_CANCEL, DEVICE_PAIRING_DIALOG_OK, DEVICE_PAIRING_DIALOG_CANCEL, VOICE_DATA_ABORT_DIALOG_OK, VOICE_DATA_ABORT_DIALOG_CANCEL, VOICE_DATA_DISCARD_FW_DIALOG_OK, VOICE_DATA_DISCARD_FW_DIALOG_CANCEL, POWER_OFF_DIALOG_OK, POWER_OFF_DIALOG_CANCEL, 
        INITIAL_SETUP_LATER, IA_TRIAL_LISTENING_2CH, IA_TRIAL_LISTENING_13CH, IA_SETUP_SELECT_SP_APP, IA_SETUP_LEARN_MORE, IA_SP_APP_RE_OPTIMIZATION, IA_SP_APP_OPTIMIZATION, IA_SP_APP_INSTALL, IA_SETUP_SKIP_CONFIRMATION_OK, IA_SETUP_SKIP_CONFIRMATION_CANCEL, 
        IA_OPEN_STORE_CONFIRMATION_OK, IA_OPEN_STORE_CONFIRMATION_CANCEL, IA_GDPR_NOTICE_OK, IA_GDPR_NOTICE_CANCEL, IA_CARD_INFO, IA_CARD_ANALYSIS, IA_CARD_OPTIMIZATION, IA_INSTALL_CONFIRM_OK, IA_INSTALL_CONFIRM_CANCEL, IA_SETUP_CAMERA_EDIT_HELP, 
        IA_SETUP_SP_APP_INTRO_LEARN_MORE, IA_SETUP_SP_APP_LIST_LEARN_MORE, IA_CAMERA_MANUAL_CONFIRM_AUTO, IA_CAMERA_MANUAL_CONFIRM_MANUAL, IA_DOUBLE_EFFECT_FLOW_CONFIRM_OK, IA_DOUBLE_EFFECT_FLOW_CONFIRM_CANCEL, IA_DOUBLE_EFFECT_TRIAL_LISTENING_CONFIRM_OK, IA_DOUBLE_EFFECT_TRIAL_LISTENING_CONFIRM_CANCEL, IA_STEP_GDPR_NOTICE_OK, IA_COUPON_SITE_OPEN, 
        IA_COUPON_DIALOG_CLOSE, IA_ALREADY_SAVED_HRTF_DOWNLOAD, IA_ALREADY_SAVED_HRTF_CANCEL, IA_SETUP_ANALYSIS_SIGNIN_LEARN_MORE, IA_SETUP_ANALYSIS_SWITCH_HRTF_APP_MANUAL, IA_SETUP_ANALYSIS_HRTF_DOWNLOAD_MANUAL, CRADLE_BATTERY_ACTIVATE_OK, CRADLE_BATTERY_ACTIVATE_CANCEL, PTOUR_MENU, QUESTIONNAIRE_ANSWER, 
        QUESTIONNAIRE_CLOSE, QUESTIONNAIRE_HOW_TO_DISPLAY_DIALOG_CLOSE, TALKING_MODE_CONFIRMATION_AFTER_TRIAL_POSITIVE, TALKING_MODE_CONFIRMATION_AFTER_TRIAL_NEGATIVE, TALKING_MODE_TURN_ON_CONFIRTATION_OK, TALKING_MODE_TURN_ON_CONFIRTATION_CANCEL, POWER_OFF_MENU, BOTTOM_SHEET_MENU, BOTTOM_SHEET_SELECT_DEVICE, BOTTOM_SHEET_NOTIFICATION, 
        BOTTOM_SHEET_MC_LAUNCH, BOTTOM_SHEET_ABOUT_THIS_APP, BOTTOM_SHEET_HELP, MULTI_POINT_SETTING_ENABLE_CONFIRMATION_OK, MULTI_POINT_SETTING_ENABLE_CONFIRMATION_CANCEL, MULTI_POINT_SETTING_DISABLE_CONFIRMATION_OK, MULTI_POINT_SETTING_DISABLE_CONFIRMATION_CANCEL, MULTIPOINT_ADDING_NEW_DEVICE, MULTIPOINT_PAIRING_HELP, MULTIPOINT_CONNECT_HISTORY_DEVICE, 
        MULTIPOINT_DISCONNECT_OWN_DEVICE, MULTIPOINT_DISCONNECT_DEVICE, MULTIPOINT_DISCONNECT_OWN_DEVICE_OK, MULTIPOINT_DISCONNECT_OWN_DEVICE_CANCEL, MULTIPOINT_DISCONNECT_DEVICE_OK, MULTIPOINT_DISCONNECT_DEVICE_CANCEL, MULTIPOINT_DELETE_CONNECTED_DEVICE, MULTIPOINT_DELETE_HISTORY_DEVICE, MULTIPOINT_DELETE_CONNECTED_DEVICE_OK, MULTIPOINT_DELETE_CONNECTED_DEVICE_CANCEL, 
        MULTIPOINT_DELETE_HISTORY_DEVICE_OK, MULTIPOINT_DELETE_HISTORY_DEVICE_CANCEL, MULTIPOINT_DISCONNECT_CONFIRMATION_BEFORE_FW_UPDATE_OK, MULTIPOINT_DISCONNECT_CONFIRMATION_BEFORE_FW_UPDATE_CANCEL, MULTIPOINT_DISCONNECT_CONFIRMATION_BEFORE_VOICE_GUIDANCE_OK, MULTIPOINT_DISCONNECT_CONFIRMATION_BEFORE_VOICE_GUIDANCE_CANCEL, FW_ABORT_CONFIRMATION_BEFORE_MULTIPOINT_PAIRING_OK, FW_ABORT_CONFIRMATION_BEFORE_MULTIPOINT_PAIRING_CANCEL, FW_ABORT_CONFIRMATION_BEFORE_MULTIPOINT_CONNECT_HISTORY_DEVICE_OK, FW_ABORT_CONFIRMATION_BEFORE_MULTIPOINT_CONNECT_HISTORY_DEVICE_CANCEL, 
        APP_UPDATE_CONFIRMATION_BEFORE_FW_UPDATE_OK, APP_UPDATE_CONFIRMATION_BEFORE_FW_UPDATE_CANCEL, APP_UPDATE_CONFIRMATION_BEFORE_FW_UPDATE_HELP, INITIAL_SETUP_ASC_OK, INITIAL_SETUP_ASC_LATER, INITIAL_SETUP_ASC_PLACE_LEARNING_OK, INITIAL_SETUP_ASC_PLACE_LEARNING_LATER, ASC_REGISTER_PLACE_FROM_MANUAL_POSITION, ASC_REGISTER_PLACE_FROM_LEARNED_PLACE, ASC_REGISTER_PLACE_FROM_TIPS, 
        ASC_REGISTER_PLACE_FROM_NOTIFICATION, ASC_UNREGISTER_PLACE_OK, ASC_UNREGISTER_PLACE_CANCEL, ASC_SETTING_DETAIL_OPEN, ASC_SETTING_DETAIL_CLOSE, ASC_OS_NOTIFICATION_SETTING_OPEN, ASC_APPLY_SETTING_MANUALLY_BUTTON, ASC_CANCEL_SETTING_MANUALLY_BUTTON, ASC_APPLY_SETTING_MANUALLY_BANNER_BUTTON, ASC_CANCEL_SETTING_MANUALLY_BANNER_BUTTON, 
        ACCOUNT_SETTINGS_BACKUP_SELECTION, ACCOUNT_SETTINGS_RESTORE_SELECTION, ACCOUNT_SETTINGS_BACKUP_CONFIRMATION, ACCOUNT_SETTINGS_RESTORE_CONFIRMATION, ACCOUNT_SETTINGS_INTRODUCTION_HELP, ACCOUNT_SETTINGS_RESTORE_HELP, ACCOUNT_SETTINGS_NOTHING_TO_RESTORE_HELP, ACCOUNT_SETTINGS_RESTORE_FROM_SERVER, ACCOUNT_SETTINGS_SET_AS_NEW_DEVICE, BOTTOM_SHEET_BACKUP_RESTORE, 
        ACCOUNT_SETTINGS_TOS_ACCEPT, ACCOUNT_SETTINGS_TOS_DECLINE, BATTERY_CONSUMPTION_INCREASE_CONFIRMATION_OK, BATTERY_CONSUMPTION_INCREASE_CONFIRMATION_CANCEL, INFORMATION_CLOSE, FEEDBACK_INFO_CLOSE, OTHER_INFO_CLOSE, INFORMATION_ITEM, FEEDBACK_INFO_ITEM, QUESTIONNAIRE_ITEM, 
        OTHER_INFO_ITEM, VA_GOOGLE_ASSISTANT_LEARN_MORE, VA_AMAZON_ALEXA_LEARN_MORE, VA_TENCENT_XIAOWEI_LEARN_MORE, CHANGE_VOICE_ASSISTANT_CONFIRMATION_OK, CHANGE_VOICE_ASSISTANT_CONFIRMATION_CANCEL, CHANGE_VOICE_ASSiSTANT_PANEL_CONFIRMATION_OK, CHANGE_VOICE_ASSISTANT_PANEL_CONFIRMATION_CANCEL, CHANGE_VOICE_ASSISTANT_BTN_WITH_LR_SELECT_CONFIRMATION_LEFT, CHANGE_VOICE_ASSISTANT_BTN_WITH_LR_SELECT_CONFIRMATION_RIGHT, 
        CHANGE_VOICE_ASSISTANT_BTN_WITH_LR_SELECT_CONFIRMATION_CANCEL, CHANGE_VOICE_ASSISTANT_SENSOR_WITH_LR_SELECT_CONFIRMATION_LEFT, CHANGE_VOICE_ASSISTANT_SENSOR_WITH_LR_SELECT_CONFIRMATION_RIGHT, CHANGE_VOICE_ASSISTANT_SENSOR_WITH_LR_SELECT_CONFIRMATION_CANCEL, VA_SENSOR_DISABLE_AND_RECONNECTION_CONFIRMATION_OK, VA_SENSOR_DISABLE_AND_RECONNECTION_CONFIRMATION_CANCEL, VA_SENSOR_ENABLE_AND_RECONNECTION_CONFIRMATION_OK, VA_SENSOR_ENABLE_AND_RECONNECTION_CONFIRMATION_CANCEL, VA_BTN_DISABLE_AND_RECONNECTION_CONFIRMATION_OK, VA_BTN_DISABLE_AND_RECONNECTION_CONFIRMATION_CANCEL, 
        VA_BTN_ENABLE_AND_RECONNECTION_CONFIRMATION_OK, VA_BTN_ENABLE_AND_RECONNECTION_CONFIRMATION_CANCEL, VA_SENSOR_DISABLE_CONFIRMATION_OK, VA_SENSOR_DISABLE_CONFIRMATION_CANCEL, VA_SENSOR_ENABLE_CONFIRMATION_OK, VA_SENSOR_ENABLE_CONFIRMATION_CANCEL, VA_BTN_DISABLE_CONFIRMATION_OK, VA_BTN_DISABLE_CONFIRMATION_CANCEL, VA_BTN_ENABLE_CONFIRMATION_OK, VA_BTN_ENABLE_CONFIRMATION_CANCEL, 
        DISABLE_TOUCH_PANEL_CONFIRMATION_OK, DISABLE_TOUCH_PANEL_CONFIRMATION_CANCEL, ENABLE_TOUCH_PANEL_CONFIRMATION_OK, ENABLE_TOUCH_PANEL_CONFIRMATION_CANCEL, DISABLE_TOUCH_PANEL_AND_RECONNECTION_CONFIRMATION_OK, DISABLE_TOUCH_PANEL_AND_RECONNECTION_CONFIRMATION_CANCEL, ENABLE_TOUCH_PANEL_AND_RECONNECTION_CONFIRMATION_OK, ENABLE_TOUCH_PANEL_AND_RECONNECTION_CONFIRMATION_CANCEL, LOCATION_BACKGROUND_PERMISSION_POST_EXPLANATION_DIALOG_SETTING, LOCATION_BACKGROUND_PERMISSION_POST_EXPLANATION_DIALOG_CANCEL, 
        LOCATION_FOREGROUND_PERMISSION_POST_EXPLANATION_DIALOG_SETTING, LOCATION_FOREGROUND_PERMISSION_POST_EXPLANATION_DIALOG_CANCEL, LOCATION_FOREGROUND_PERMISSION_ALLOW, LOCATION_FOREGROUND_PERMISSION_DENY_OR_NOTDISPLAYED, LOCATION_BACKGROUND_PERMISSION_ALLOW, LOCATION_BACKGROUND_PERMISSION_DENY_OR_NOTDISPLAYED, LOCATION_PERMISSION_OS_SETTING_FOREGROUND_ALLOW, LOCATION_PERMISSION_OS_SETTING_BACKGROUND_ALLOW, LOCATION_PERMISSION_OS_SETTING_DENY_OR_CANCELLED, CAMERA_PERMISSION_POST_EXPLANATION_DIALOG_SETTING, 
        CAMERA_PERMISSION_POST_EXPLANATION_DIALOG_CANCEL, CAMERA_PERMISSION_DENY_OR_NOTDISPLAYED, CAMERA_PERMISSION_ALLOW, CAMERA_PERMISSION_OS_SETTING_ALLOW, CAMERA_PERMISSION_OS_SETTING_DENY_OR_CANCELLED, WIDGET_LAUNCH_HPC_HOME, WIDGET_LAUNCH_HPC_SIDESENSE, WIDGET_EQ_CHANGE_HOME, WIDGET_EQ_CHANGE_SIDESENSE, WIDGET_CLEARBASS_CHANGE_HOME, 
        WIDGET_CLEARBASS_CHANGE_SIDESENSE, ESA_ABS_MEASURING_START, ESA_ABS_START_FORCEFUL, ESA_ABS_NOT_WEARING_BACK, ESA_ABS_MEASURING_CANCEL, ESA_ABS_MEASURING_ERROR_RESTART, ESA_ABS_MEASURING_ERROR_FINISH, ESA_ABS_COMPLETE_RESTART, ESA_ABS_COMPLETE_FINISH, ESA_RELATIVE_MEASURING_START, 
        ESA_RELATIVE_MEASURING_FINISH, ESA_RELATIVE_START_FORCEFUL, ESA_RELATIVE_NOT_WEARING_BACK, ESA_RELATIVE_MEASURING_CANCEL, ESA_RELATIVE_MEASURING_ERROR_RESTART, ESA_RELATIVE_MEASURING_ERROR_SKIP, ESA_RELATIVE_JUDGEMENT_ERROR_FINISH, RESET_SETTINGS_FACTORY_RESET, CHANGE_VA_TO_ALEXA_CONFIRMATION_OK, CHANGE_VA_TO_ALEXA_CONFIRMATION_CANCEL, 
        CHANGE_VA_TO_OTHER_CONFIRMATION_OK, VOICE_ASSISTANT_INTRODUCTION_GOOGLE_ASSISTANT_LEARN_MORE, VOICE_ASSISTANT_INTRODUCTION_AMAZON_ALEXA_LEARN_MORE, VOICE_ASSISTANT_INTRODUCTION_TENCENT_XIAOWEI_LEARN_MORE, AMAZON_ALEXA_INSTALL_CONFIRMATION_OK, AMAZON_ALEXA_INSTALL_CONFIRMATION_CANCEL, VOICE_ASSISTANT_INTRODUCTION_SET, VOICE_ASSISTANT_INTRODUCTION_CLOSE, AMAZON_ALEXA_SPLASH_APP, AMAZON_ALEXA_THINGS_TO_TRY_APP };
  }
  
  UIPart(String paramString1) {
    this.mStrValue = paramString1;
  }
  
  public String getStrValue() {
    return this.mStrValue;
  }
  
  public enum PlaybackController {
    NEXT_TRACK,
    PAUSE,
    PLAY,
    PREVIOUS_TRACK,
    UNKNOWN("unknown");
    
    private final String mStrValue;
    
    static {
      PAUSE = new PlaybackController("PAUSE", 2, "playbackControllerPause");
      NEXT_TRACK = new PlaybackController("NEXT_TRACK", 3, "playbackControllerNextTrack");
      PREVIOUS_TRACK = new PlaybackController("PREVIOUS_TRACK", 4, "playbackControllerPreviousTrack");
      a = new PlaybackController[] { UNKNOWN, PLAY, PAUSE, NEXT_TRACK, PREVIOUS_TRACK };
    }
    
    PlaybackController(String param1String1) {
      this.mStrValue = param1String1;
    }
    
    public String getStrValue() {
      return this.mStrValue;
    }
  }
}


/* Location:              /home/egaebel/Programs/sony-headphones-hack/base-dex2jar.jar!/com/sony/songpal/mdr/j2objc/actionlog/param/UIPart.class
 * Java compiler version: 6 (50.0)
 * JD-Core Version:       1.1.3
 */