package com.sony.songpal.ble.logic;

public enum PairingSequenceError {
  CHANGE_NOTIFICATION_STATE_FAILED,
  CHANGE_NOTIFICATION_STATE_REJECTED,
  LOST_BLE_DEVICE_WHILE_PROXIMITY_CHECK,
  READ_BLUETOOTH_FRIENDLY_NAME_NOT_SUCCESS_WITH_NULL_CHARACTERISTIC,
  READ_BLUETOOTH_FRIENDLY_NAME_NOT_SUCCESS_WITH_UNEXPECTED_CHARACTERISTIC,
  READ_BLUETOOTH_FRIENDLY_NAME_REJECTED,
  READ_BLUETOOTH_FRIENDLY_NAME_SUCCESS_WITH_INVALID_SERVICE_UUID,
  READ_BLUETOOTH_FRIENDLY_NAME_SUCCESS_WITH_NULL_CHARACTERISTIC,
  READ_BLUETOOTH_FRIENDLY_NAME_SUCCESS_WITH_UNEXPECTED_CHARACTERISTIC,
  READ_RSSI_REQUEST_REJECTED("Read RSSI request is rejected."),
  RECEIVED_INVALID_SERVICE_UUID_NOTIFICATION("Read RSSI request is rejected."),
  RECEIVED_NOTIFICATION_STATE_CHANGE_WITH_INVALID_SERVICE_UUID("Read RSSI request is rejected."),
  RECEIVED_NOTIFICATION_STATE_CHANGE_WITH_UNEXPECTED_CHARACTERISTIC("Read RSSI request is rejected."),
  RECEIVED_UNEXPECTED_CHARACTERISTIC_NOTIFICATION("Read RSSI request is rejected."),
  WRITE_BLUETOOTH_MODE_REJECTED("Read RSSI request is rejected."),
  WRITE_BLUETOOTH_MODE_RESPONSE_NOT_SUCCESS("Read RSSI request is rejected."),
  WRITE_BLUETOOTH_MODE_RESPONSE_WITH_INVALID_SERVICE_UUID("Read RSSI request is rejected."),
  WRITE_BLUETOOTH_MODE_RESPONSE_WITH_UNEXPECTED_CHARACTERISTIC("Read RSSI request is rejected.");
  
  private final String message;
  
  static {
    LOST_BLE_DEVICE_WHILE_PROXIMITY_CHECK = new PairingSequenceError("LOST_BLE_DEVICE_WHILE_PROXIMITY_CHECK", 1, "Lost BleDevice while GATT proximity check.");
    WRITE_BLUETOOTH_MODE_REJECTED = new PairingSequenceError("WRITE_BLUETOOTH_MODE_REJECTED", 2, "Writing BluetoothMode is rejected.");
    WRITE_BLUETOOTH_MODE_RESPONSE_NOT_SUCCESS = new PairingSequenceError("WRITE_BLUETOOTH_MODE_RESPONSE_NOT_SUCCESS", 3, "Status of writing BluetoothMode response isn't SUCCESS.");
    WRITE_BLUETOOTH_MODE_RESPONSE_WITH_INVALID_SERVICE_UUID = new PairingSequenceError("WRITE_BLUETOOTH_MODE_RESPONSE_WITH_INVALID_SERVICE_UUID", 4, "Writing BluetoothMode response has invalid service UUID (NOT BLUETOOTH_PAIRING_SERVICE).");
    WRITE_BLUETOOTH_MODE_RESPONSE_WITH_UNEXPECTED_CHARACTERISTIC = new PairingSequenceError("WRITE_BLUETOOTH_MODE_RESPONSE_WITH_UNEXPECTED_CHARACTERISTIC", 5, "Writing BluetoothMode response has unexpected characteristic (NOT BluetoothMode)");
    CHANGE_NOTIFICATION_STATE_REJECTED = new PairingSequenceError("CHANGE_NOTIFICATION_STATE_REJECTED", 6, "Changing notification state is rejected.");
    CHANGE_NOTIFICATION_STATE_FAILED = new PairingSequenceError("CHANGE_NOTIFICATION_STATE_FAILED", 7, "Changing notification state is failed.");
    RECEIVED_NOTIFICATION_STATE_CHANGE_WITH_INVALID_SERVICE_UUID = new PairingSequenceError("RECEIVED_NOTIFICATION_STATE_CHANGE_WITH_INVALID_SERVICE_UUID", 8, "Result of changing notification state has invalid service UUID.");
    RECEIVED_NOTIFICATION_STATE_CHANGE_WITH_UNEXPECTED_CHARACTERISTIC = new PairingSequenceError("RECEIVED_NOTIFICATION_STATE_CHANGE_WITH_UNEXPECTED_CHARACTERISTIC", 9, "Result of changing notification state has unexpected characteristic (NOT BluetoothModeState).");
    RECEIVED_INVALID_SERVICE_UUID_NOTIFICATION = new PairingSequenceError("RECEIVED_INVALID_SERVICE_UUID_NOTIFICATION", 10, "Received invalid service UUID notification(NOT BLUETOOTH_PAIRING_SERVICE).");
    RECEIVED_UNEXPECTED_CHARACTERISTIC_NOTIFICATION = new PairingSequenceError("RECEIVED_UNEXPECTED_CHARACTERISTIC_NOTIFICATION", 11, "Received unexpected notification (NOT BluetoothModeStatus).");
    READ_BLUETOOTH_FRIENDLY_NAME_REJECTED = new PairingSequenceError("READ_BLUETOOTH_FRIENDLY_NAME_REJECTED", 12, "Reading BluetoothFriendlyName is rejected.");
    READ_BLUETOOTH_FRIENDLY_NAME_NOT_SUCCESS_WITH_NULL_CHARACTERISTIC = new PairingSequenceError("READ_BLUETOOTH_FRIENDLY_NAME_NOT_SUCCESS_WITH_NULL_CHARACTERISTIC", 13, "Result of reading BluetoothFriendlyName is NOT SUCCESS (with null).");
    READ_BLUETOOTH_FRIENDLY_NAME_NOT_SUCCESS_WITH_UNEXPECTED_CHARACTERISTIC = new PairingSequenceError("READ_BLUETOOTH_FRIENDLY_NAME_NOT_SUCCESS_WITH_UNEXPECTED_CHARACTERISTIC", 14, "Result of reading BluetoothFriendlyName is NOT SUCCESS (with unexpected characteristic (NOT BluetoothFriendlyName)).");
    READ_BLUETOOTH_FRIENDLY_NAME_SUCCESS_WITH_NULL_CHARACTERISTIC = new PairingSequenceError("READ_BLUETOOTH_FRIENDLY_NAME_SUCCESS_WITH_NULL_CHARACTERISTIC", 15, "Result of reading BluetoothFriendlyName is SUCCESS, but include null characteristic.");
    READ_BLUETOOTH_FRIENDLY_NAME_SUCCESS_WITH_INVALID_SERVICE_UUID = new PairingSequenceError("READ_BLUETOOTH_FRIENDLY_NAME_SUCCESS_WITH_INVALID_SERVICE_UUID", 16, "Result of reading BluetoothFriendlyName is SUCCESS, but include invalid service UUID.");
    READ_BLUETOOTH_FRIENDLY_NAME_SUCCESS_WITH_UNEXPECTED_CHARACTERISTIC = new PairingSequenceError("READ_BLUETOOTH_FRIENDLY_NAME_SUCCESS_WITH_UNEXPECTED_CHARACTERISTIC", 17, "Result of reading BluetoothFriendlyName is SUCCESS, but include unexpected characteristic (NOT BluetoothFriendlyName)");
    a = new PairingSequenceError[] { 
        READ_RSSI_REQUEST_REJECTED, LOST_BLE_DEVICE_WHILE_PROXIMITY_CHECK, WRITE_BLUETOOTH_MODE_REJECTED, WRITE_BLUETOOTH_MODE_RESPONSE_NOT_SUCCESS, WRITE_BLUETOOTH_MODE_RESPONSE_WITH_INVALID_SERVICE_UUID, WRITE_BLUETOOTH_MODE_RESPONSE_WITH_UNEXPECTED_CHARACTERISTIC, CHANGE_NOTIFICATION_STATE_REJECTED, CHANGE_NOTIFICATION_STATE_FAILED, RECEIVED_NOTIFICATION_STATE_CHANGE_WITH_INVALID_SERVICE_UUID, RECEIVED_NOTIFICATION_STATE_CHANGE_WITH_UNEXPECTED_CHARACTERISTIC, 
        RECEIVED_INVALID_SERVICE_UUID_NOTIFICATION, RECEIVED_UNEXPECTED_CHARACTERISTIC_NOTIFICATION, READ_BLUETOOTH_FRIENDLY_NAME_REJECTED, READ_BLUETOOTH_FRIENDLY_NAME_NOT_SUCCESS_WITH_NULL_CHARACTERISTIC, READ_BLUETOOTH_FRIENDLY_NAME_NOT_SUCCESS_WITH_UNEXPECTED_CHARACTERISTIC, READ_BLUETOOTH_FRIENDLY_NAME_SUCCESS_WITH_NULL_CHARACTERISTIC, READ_BLUETOOTH_FRIENDLY_NAME_SUCCESS_WITH_INVALID_SERVICE_UUID, READ_BLUETOOTH_FRIENDLY_NAME_SUCCESS_WITH_UNEXPECTED_CHARACTERISTIC };
  }
  
  PairingSequenceError(String paramString1) {
    this.message = paramString1;
  }
  
  public String message() {
    return this.message;
  }
}


/* Location:              /home/egaebel/Programs/sony-headphones-hack/base-dex2jar.jar!/com/sony/songpal/ble/logic/PairingSequenceError.class
 * Java compiler version: 6 (50.0)
 * JD-Core Version:       1.1.3
 */