package com.sony.songpal.mdr.j2objc.vim;

public enum CardId {
  ADAPTIVE_SOUND_CONTROL, AMBIENT_SOUND_MODE, ASSIGNABLE_SETTINGS, AUTO_POWER_OFF, CONNECTION_MODE, CONNECTION_MODE_BLUETOOTH_CONNECT, CONTROL_BY_WEARING, EBB, FW_UPDATE, GENERAL_SETTING1, GENERAL_SETTING2, GENERAL_SETTING3, IMMERSIVE_AUDIO, NC_AMB_TOGGLE, NC_OPTIMIZER, NOISE_CANCELLING, NOISE_CANCELLING_AND_AMBIENT_SOUND_MODE, PAIRING_DEVICE_MANAGEMENT_CLASSIC_BT, PLAYBACK_CONTROLLER, PLAYBACK_CONTROLLER_WITH_CALL_VOLUME_ADJUSTMENT, POWER_SAVING_MODE, PRESET_EQ, RESET_SETTINGS, SMART_TALKING_MODE, SOUND_POSITION, TRAINING_MODE, UPSCALING, VIBRATOR, VOICE_ASSISTANT_SETTINGS, VOICE_ASSISTANT_WAKE_WORD, VOICE_GUIDANCE, VPT, WEARING_STATUS_DETECTOR;
  
  static {
    SOUND_POSITION = new CardId("SOUND_POSITION", 1);
    EBB = new CardId("EBB", 2);
    PRESET_EQ = new CardId("PRESET_EQ", 3);
    NOISE_CANCELLING = new CardId("NOISE_CANCELLING", 4);
    NOISE_CANCELLING_AND_AMBIENT_SOUND_MODE = new CardId("NOISE_CANCELLING_AND_AMBIENT_SOUND_MODE", 5);
    UPSCALING = new CardId("UPSCALING", 6);
    CONNECTION_MODE = new CardId("CONNECTION_MODE", 7);
    CONNECTION_MODE_BLUETOOTH_CONNECT = new CardId("CONNECTION_MODE_BLUETOOTH_CONNECT", 8);
    AMBIENT_SOUND_MODE = new CardId("AMBIENT_SOUND_MODE", 9);
    NC_OPTIMIZER = new CardId("NC_OPTIMIZER", 10);
    ADAPTIVE_SOUND_CONTROL = new CardId("ADAPTIVE_SOUND_CONTROL", 11);
    VIBRATOR = new CardId("VIBRATOR", 12);
    TRAINING_MODE = new CardId("TRAINING_MODE", 13);
    PLAYBACK_CONTROLLER = new CardId("PLAYBACK_CONTROLLER", 14);
    PLAYBACK_CONTROLLER_WITH_CALL_VOLUME_ADJUSTMENT = new CardId("PLAYBACK_CONTROLLER_WITH_CALL_VOLUME_ADJUSTMENT", 15);
    POWER_SAVING_MODE = new CardId("POWER_SAVING_MODE", 16);
    CONTROL_BY_WEARING = new CardId("CONTROL_BY_WEARING", 17);
    AUTO_POWER_OFF = new CardId("AUTO_POWER_OFF", 18);
    SMART_TALKING_MODE = new CardId("SMART_TALKING_MODE", 19);
    ASSIGNABLE_SETTINGS = new CardId("ASSIGNABLE_SETTINGS", 20);
    NC_AMB_TOGGLE = new CardId("NC_AMB_TOGGLE", 21);
    VOICE_GUIDANCE = new CardId("VOICE_GUIDANCE", 22);
    FW_UPDATE = new CardId("FW_UPDATE", 23);
    GENERAL_SETTING1 = new CardId("GENERAL_SETTING1", 24);
    GENERAL_SETTING2 = new CardId("GENERAL_SETTING2", 25);
    GENERAL_SETTING3 = new CardId("GENERAL_SETTING3", 26);
    PAIRING_DEVICE_MANAGEMENT_CLASSIC_BT = new CardId("PAIRING_DEVICE_MANAGEMENT_CLASSIC_BT", 27);
    IMMERSIVE_AUDIO = new CardId("IMMERSIVE_AUDIO", 28);
    WEARING_STATUS_DETECTOR = new CardId("WEARING_STATUS_DETECTOR", 29);
    VOICE_ASSISTANT_SETTINGS = new CardId("VOICE_ASSISTANT_SETTINGS", 30);
    VOICE_ASSISTANT_WAKE_WORD = new CardId("VOICE_ASSISTANT_WAKE_WORD", 31);
    RESET_SETTINGS = new CardId("RESET_SETTINGS", 32);
    a = new CardId[] { 
        VPT, SOUND_POSITION, EBB, PRESET_EQ, NOISE_CANCELLING, NOISE_CANCELLING_AND_AMBIENT_SOUND_MODE, UPSCALING, CONNECTION_MODE, CONNECTION_MODE_BLUETOOTH_CONNECT, AMBIENT_SOUND_MODE, 
        NC_OPTIMIZER, ADAPTIVE_SOUND_CONTROL, VIBRATOR, TRAINING_MODE, PLAYBACK_CONTROLLER, PLAYBACK_CONTROLLER_WITH_CALL_VOLUME_ADJUSTMENT, POWER_SAVING_MODE, CONTROL_BY_WEARING, AUTO_POWER_OFF, SMART_TALKING_MODE, 
        ASSIGNABLE_SETTINGS, NC_AMB_TOGGLE, VOICE_GUIDANCE, FW_UPDATE, GENERAL_SETTING1, GENERAL_SETTING2, GENERAL_SETTING3, PAIRING_DEVICE_MANAGEMENT_CLASSIC_BT, IMMERSIVE_AUDIO, WEARING_STATUS_DETECTOR, 
        VOICE_ASSISTANT_SETTINGS, VOICE_ASSISTANT_WAKE_WORD, RESET_SETTINGS };
  }
}


/* Location:              /home/egaebel/Programs/sony-headphones-hack/base-dex2jar.jar!/com/sony/songpal/mdr/j2objc/vim/CardId.class
 * Java compiler version: 6 (50.0)
 * JD-Core Version:       1.1.3
 */