package com.sony.songpal.earcapture.j2objc.actionlog.param;

public enum Error {
  IA_CAMERA_AV_AUDIO_PLAYER_INITIALIZE_FAILED,
  IA_CAMERA_AV_CAPTURE_DEVICE_INPUT_FAILED,
  IA_CAMERA_CAMERA_DEVICE_STATE_ERROR,
  IA_CAMERA_CAPTURE_SESSION_CAMERA_ACCESS_EXCEPTION,
  IA_CAMERA_CAPTURE_SESSION_CONFIGURE_FAILED,
  IA_CAMERA_CREATE_CAMERA_PREVIEW_SESSION_FAILED,
  IA_CAMERA_FACE_DETECTION_SUCCEEDED,
  IA_CAMERA_GET_TARGET_CAMERA_ID_FAILED,
  IA_CAMERA_OPEN_CAMERA_GET_CAMERA_CHARACTERISTICS_FAILED,
  IA_CAMERA_OPEN_CAMERA_GET_TARGET_CAMERA_ID_FAILED,
  IA_CAMERA_STREAM_CONFIGURATION_MAP_FAILED,
  IA_CAMERA_TTS_CANTONESE_UNAVAILABLE,
  IA_CAMERA_TTS_INITIALIZE_FAILED,
  IA_CAMERA_TTS_INITIALIZE_NOT_COMPLETED,
  IA_CAMERA_TTS_INITIALIZE_STARTED("iaCameraTtsInitializeStarted"),
  IA_CAMERA_TTS_INITIALIZE_SUCCEEDED("iaCameraTtsInitializeStarted"),
  IA_CAMERA_TTS_NO_LANGUAGE("iaCameraTtsInitializeStarted"),
  IA_CAMERA_TTS_NO_VOICE("iaCameraTtsInitializeStarted"),
  IA_CAMERA_TTS_NO_VOICE_ENGLISH_AVAILABLE("iaCameraTtsInitializeStarted"),
  IA_CAMERA_TTS_NO_VOICE_ENGLISH_UNAVAILABLE("iaCameraTtsInitializeStarted"),
  IA_CAMERA_TTS_VOICE_EXCEPTION("iaCameraTtsInitializeStarted"),
  IA_CAMERA_TTS_VOICE_EXCEPTION_NO_LANGUAGE_ENGLISH_AVAILABLE("iaCameraTtsInitializeStarted"),
  IA_CAMERA_TTS_VOICE_EXCEPTION_NO_LANGUAGE_ENGLISH_UNAVAILABLE("iaCameraTtsInitializeStarted"),
  IA_OPTIMIZE_FAILED_CALLBACK_ON_ERROR("iaCameraTtsInitializeStarted"),
  IA_OPTIMIZE_FAILED_CUSTOM_URL_FORMAT_ERROR("iaCameraTtsInitializeStarted"),
  IA_OPTIMIZE_FAILED_CUSTOM_URL_OPEN_ERROR("iaCameraTtsInitializeStarted"),
  IA_OPTIMIZE_FAILED_MODEL_EMPTY("iaCameraTtsInitializeStarted");
  
  private final String mStrValue;
  
  static {
    IA_CAMERA_TTS_INITIALIZE_FAILED = new Error("IA_CAMERA_TTS_INITIALIZE_FAILED", 1, "iaCameraTtsInitializeFailed");
    IA_CAMERA_TTS_INITIALIZE_SUCCEEDED = new Error("IA_CAMERA_TTS_INITIALIZE_SUCCEEDED", 2, "iaCameraTtsInitializeSucceeded");
    IA_CAMERA_TTS_INITIALIZE_NOT_COMPLETED = new Error("IA_CAMERA_TTS_INITIALIZE_NOT_COMPLETED", 3, "iaCameraTtsInitializeNotCompleted");
    IA_CAMERA_TTS_NO_LANGUAGE = new Error("IA_CAMERA_TTS_NO_LANGUAGE", 4, "IaCameraTtsNoLanguage");
    IA_CAMERA_TTS_CANTONESE_UNAVAILABLE = new Error("IA_CAMERA_TTS_CANTONESE_UNAVAILABLE", 5, "IaCameraTtsCantoneseUnavailable");
    IA_CAMERA_TTS_NO_VOICE = new Error("IA_CAMERA_TTS_NO_VOICE", 6, "IaCameraTtsNoVoice");
    IA_CAMERA_TTS_NO_VOICE_ENGLISH_AVAILABLE = new Error("IA_CAMERA_TTS_NO_VOICE_ENGLISH_AVAILABLE", 7, "IaCameraTtsNoVoiceEnglishAvailable");
    IA_CAMERA_TTS_NO_VOICE_ENGLISH_UNAVAILABLE = new Error("IA_CAMERA_TTS_NO_VOICE_ENGLISH_UNAVAILABLE", 8, "IaCameraTtsNoVoiceEnglishUnavailable");
    IA_CAMERA_TTS_VOICE_EXCEPTION = new Error("IA_CAMERA_TTS_VOICE_EXCEPTION", 9, "IaCameraTtsVoiceException");
    IA_CAMERA_TTS_VOICE_EXCEPTION_NO_LANGUAGE_ENGLISH_AVAILABLE = new Error("IA_CAMERA_TTS_VOICE_EXCEPTION_NO_LANGUAGE_ENGLISH_AVAILABLE", 10, "IaCameraTtsVoiceExceptionNoLanguageEnglishAvailable");
    IA_CAMERA_TTS_VOICE_EXCEPTION_NO_LANGUAGE_ENGLISH_UNAVAILABLE = new Error("IA_CAMERA_TTS_VOICE_EXCEPTION_NO_LANGUAGE_ENGLISH_UNAVAILABLE", 11, "IaCameraTtsVoiceExceptionNoLanguageEnglishUnavailable");
    IA_CAMERA_CAMERA_DEVICE_STATE_ERROR = new Error("IA_CAMERA_CAMERA_DEVICE_STATE_ERROR", 12, "IaCameraCameraDeviceStateError");
    IA_CAMERA_GET_TARGET_CAMERA_ID_FAILED = new Error("IA_CAMERA_GET_TARGET_CAMERA_ID_FAILED", 13, "IaCameraGetTargetCameraIdFailed");
    IA_CAMERA_OPEN_CAMERA_GET_TARGET_CAMERA_ID_FAILED = new Error("IA_CAMERA_OPEN_CAMERA_GET_TARGET_CAMERA_ID_FAILED", 14, "IaCameraOpenCameraGetTargetCameraIdFailed");
    IA_CAMERA_OPEN_CAMERA_GET_CAMERA_CHARACTERISTICS_FAILED = new Error("IA_CAMERA_OPEN_CAMERA_GET_CAMERA_CHARACTERISTICS_FAILED", 15, "IaCameraOpenCameraGetCameraCharacteristicsFailed");
    IA_CAMERA_STREAM_CONFIGURATION_MAP_FAILED = new Error("IA_CAMERA_STREAM_CONFIGURATION_MAP_FAILED", 16, "IaCameraStreamConfigurationMapFailed");
    IA_CAMERA_CAPTURE_SESSION_CAMERA_ACCESS_EXCEPTION = new Error("IA_CAMERA_CAPTURE_SESSION_CAMERA_ACCESS_EXCEPTION", 17, "IaCameraCaptureSessionCameraAccessException");
    IA_CAMERA_CAPTURE_SESSION_CONFIGURE_FAILED = new Error("IA_CAMERA_CAPTURE_SESSION_CONFIGURE_FAILED", 18, "IaCameraCaptureSessionConfigureFailed");
    IA_CAMERA_CREATE_CAMERA_PREVIEW_SESSION_FAILED = new Error("IA_CAMERA_CREATE_CAMERA_PREVIEW_SESSION_FAILED", 19, "IaCameraCreateCameraPreviewSessionFailed");
    IA_CAMERA_AV_CAPTURE_DEVICE_INPUT_FAILED = new Error("IA_CAMERA_AV_CAPTURE_DEVICE_INPUT_FAILED", 20, "iaCameraAvCaptureDeviceInputFailed");
    IA_CAMERA_AV_AUDIO_PLAYER_INITIALIZE_FAILED = new Error("IA_CAMERA_AV_AUDIO_PLAYER_INITIALIZE_FAILED", 21, "iaCameraAvAudioPlayerInitializeFailed");
    IA_CAMERA_FACE_DETECTION_SUCCEEDED = new Error("IA_CAMERA_FACE_DETECTION_SUCCEEDED", 22, "iaCameraFaceDetectionSucceeded");
    IA_OPTIMIZE_FAILED_MODEL_EMPTY = new Error("IA_OPTIMIZE_FAILED_MODEL_EMPTY", 23, "iaOptimizeFailedModelEmpty");
    IA_OPTIMIZE_FAILED_CUSTOM_URL_FORMAT_ERROR = new Error("IA_OPTIMIZE_FAILED_CUSTOM_URL_FORMAT_ERROR", 24, "iaOptimizeFailedCustomUrlFormatError");
    IA_OPTIMIZE_FAILED_CUSTOM_URL_OPEN_ERROR = new Error("IA_OPTIMIZE_FAILED_CUSTOM_URL_OPEN_ERROR", 25, "iaOptimizeFailedCustomUrlOpenError");
    IA_OPTIMIZE_FAILED_CALLBACK_ON_ERROR = new Error("IA_OPTIMIZE_FAILED_CALLBACK_ON_ERROR", 26, "iaOptimizeFailedCallbackOnError");
    a = new Error[] { 
        IA_CAMERA_TTS_INITIALIZE_STARTED, IA_CAMERA_TTS_INITIALIZE_FAILED, IA_CAMERA_TTS_INITIALIZE_SUCCEEDED, IA_CAMERA_TTS_INITIALIZE_NOT_COMPLETED, IA_CAMERA_TTS_NO_LANGUAGE, IA_CAMERA_TTS_CANTONESE_UNAVAILABLE, IA_CAMERA_TTS_NO_VOICE, IA_CAMERA_TTS_NO_VOICE_ENGLISH_AVAILABLE, IA_CAMERA_TTS_NO_VOICE_ENGLISH_UNAVAILABLE, IA_CAMERA_TTS_VOICE_EXCEPTION, 
        IA_CAMERA_TTS_VOICE_EXCEPTION_NO_LANGUAGE_ENGLISH_AVAILABLE, IA_CAMERA_TTS_VOICE_EXCEPTION_NO_LANGUAGE_ENGLISH_UNAVAILABLE, IA_CAMERA_CAMERA_DEVICE_STATE_ERROR, IA_CAMERA_GET_TARGET_CAMERA_ID_FAILED, IA_CAMERA_OPEN_CAMERA_GET_TARGET_CAMERA_ID_FAILED, IA_CAMERA_OPEN_CAMERA_GET_CAMERA_CHARACTERISTICS_FAILED, IA_CAMERA_STREAM_CONFIGURATION_MAP_FAILED, IA_CAMERA_CAPTURE_SESSION_CAMERA_ACCESS_EXCEPTION, IA_CAMERA_CAPTURE_SESSION_CONFIGURE_FAILED, IA_CAMERA_CREATE_CAMERA_PREVIEW_SESSION_FAILED, 
        IA_CAMERA_AV_CAPTURE_DEVICE_INPUT_FAILED, IA_CAMERA_AV_AUDIO_PLAYER_INITIALIZE_FAILED, IA_CAMERA_FACE_DETECTION_SUCCEEDED, IA_OPTIMIZE_FAILED_MODEL_EMPTY, IA_OPTIMIZE_FAILED_CUSTOM_URL_FORMAT_ERROR, IA_OPTIMIZE_FAILED_CUSTOM_URL_OPEN_ERROR, IA_OPTIMIZE_FAILED_CALLBACK_ON_ERROR };
  }
  
  Error(String paramString1) {
    this.mStrValue = paramString1;
  }
  
  public String getStrValue() {
    return this.mStrValue;
  }
}


/* Location:              /home/egaebel/Programs/sony-headphones-hack/base-dex2jar.jar!/com/sony/songpal/earcapture/j2objc/actionlog/param/Error.class
 * Java compiler version: 6 (50.0)
 * JD-Core Version:       1.1.3
 */