package com.sony.songpal.mdr.j2objc.tandem.features.alert;

import com.sony.songpal.tandemfamily.message.mdr.v1.table1.param.AlertMessageType;
import com.sony.songpal.tandemfamily.message.mdr.v2.table1.alert.param.AlertMessageType;

public enum AlertMsgType {
  BATTERY_CONSUMPTION_INCREASE_DUE_TO_EQ_AND_UPSCALING,
  CAUTION_FOR_ABLE_TOUCH_SENSOR_PANEL,
  CAUTION_FOR_ABLE_TOUCH_SENSOR_PANEL_AND_RECONNECTION,
  CAUTION_FOR_ABLE_VOICE_ASSISTANT_AND_RECONNECTION_ASSIGNABLE_BUTTON,
  CAUTION_FOR_ABLE_VOICE_ASSISTANT_AND_RECONNECTION_ASSIGNABLE_SENSOR,
  CAUTION_FOR_ABLE_VOICE_ASSISTANT_ASSIGNABLE_BUTTON,
  CAUTION_FOR_ABLE_VOICE_ASSISTANT_ASSIGNABLE_SENSOR,
  CAUTION_FOR_CHANGE_VOICE_ASSISTANT,
  CAUTION_FOR_CHANGE_VOICE_ASSISTANT_TOUCH_SENSOR_PANEL,
  CAUTION_FOR_CHANGE_VOICE_ASSISTANT_TOUCH_SENSOR_PANEL_MOBILE_OR_SIRI,
  CAUTION_FOR_DISABLE_TOUCH_SENSOR_PANEL,
  CAUTION_FOR_DISABLE_TOUCH_SENSOR_PANEL_AND_RECONNECTION,
  CAUTION_FOR_DISABLE_VOICE_ASSISTANT_AND_RECONNECTION_ASSIGNABLE_BUTTON,
  CAUTION_FOR_DISABLE_VOICE_ASSISTANT_AND_RECONNECTION_ASSIGNABLE_SENSOR,
  CAUTION_FOR_DISABLE_VOICE_ASSISTANT_ASSIGNABLE_BUTTON,
  CAUTION_FOR_DISABLE_VOICE_ASSISTANT_ASSIGNABLE_SENSOR,
  CAUTION_FOR_DUAL_ASSIGNMENT_OF_PLAYBACK_CONTROL,
  DISCONNECT_CAUSED_BY_CHANGING_KEY_ASSIGN,
  DISCONNECT_CAUSED_BY_CHANGING_MULTIPOINT_TO_OFF,
  DISCONNECT_CAUSED_BY_CHANGING_MULTIPOINT_TO_ON,
  DISCONNECT_CAUSED_BY_CONNECTION_MODE_CHANGE,
  DUAL_ASSIGN_OF_VOICE_ASSISTANT_IS_UNAVAILABLE,
  FOREGROUND_CAUTION_NEED_DISCONNECTION_FOR_ENABLING_WAKE_WORD,
  FOREGROUND_CAUTION_WAKE_WORD_IS_AVAILABLE_ONLY_IN_USE_OF_ALEXA,
  GOOGLE_ASSISTANT_IS_NOW_AVAILABLE,
  NEED_DISCONNECTION_FOR_UPDATING_FIRMWARE,
  NO_USE(AlertMessageType.NO_USE, null),
  OUT_OF_RANGE(AlertMessageType.NO_USE, null);
  
  private final AlertMessageType mTypeTableSet1;
  
  private final AlertMessageType mTypeTableSet2;
  
  static {
    DISCONNECT_CAUSED_BY_CONNECTION_MODE_CHANGE = new AlertMsgType("DISCONNECT_CAUSED_BY_CONNECTION_MODE_CHANGE", 1, AlertMessageType.DISCONNECT_CAUSED_BY_CONNECTION_MODE_CHANGE, AlertMessageType.DISCONNECT_CAUSED_BY_CONNECTION_MODE_CHANGE);
    DISCONNECT_CAUSED_BY_CHANGING_KEY_ASSIGN = new AlertMsgType("DISCONNECT_CAUSED_BY_CHANGING_KEY_ASSIGN", 2, AlertMessageType.DISCONNECT_CAUSED_BY_CHANGING_KEY_ASSIGN, AlertMessageType.DISCONNECT_CAUSED_BY_CHANGING_KEY_ASSIGN);
    NEED_DISCONNECTION_FOR_UPDATING_FIRMWARE = new AlertMsgType("NEED_DISCONNECTION_FOR_UPDATING_FIRMWARE", 3, AlertMessageType.NEED_DISCONNECTION_FOR_UPDATING_FIRMWARE, AlertMessageType.NEED_DISCONNECTION_FOR_UPDATING_FIRMWARE);
    GOOGLE_ASSISTANT_IS_NOW_AVAILABLE = new AlertMsgType("GOOGLE_ASSISTANT_IS_NOW_AVAILABLE", 4, AlertMessageType.GOOGLE_ASSISTANT_IS_NOW_AVAILABLE, AlertMessageType.GOOGLE_ASSISTANT_IS_NOW_AVAILABLE);
    DUAL_ASSIGN_OF_VOICE_ASSISTANT_IS_UNAVAILABLE = new AlertMsgType("DUAL_ASSIGN_OF_VOICE_ASSISTANT_IS_UNAVAILABLE", 5, AlertMessageType.DUAL_ASSIGN_OF_VOICE_ASSISTANT_IS_UNAVAILABLE, AlertMessageType.DUAL_ASSIGN_OF_VOICE_ASSISTANT_IS_UNAVAILABLE);
    DISCONNECT_CAUSED_BY_CHANGING_MULTIPOINT_TO_ON = new AlertMsgType("DISCONNECT_CAUSED_BY_CHANGING_MULTIPOINT_TO_ON", 6, AlertMessageType.DISCONNECT_CAUSED_BY_CHANGING_MULTIPOINT_TO_ON, AlertMessageType.DISCONNECT_CAUSED_BY_CHANGING_MULTIPOINT_TO_ON);
    DISCONNECT_CAUSED_BY_CHANGING_MULTIPOINT_TO_OFF = new AlertMsgType("DISCONNECT_CAUSED_BY_CHANGING_MULTIPOINT_TO_OFF", 7, AlertMessageType.DISCONNECT_CAUSED_BY_CHANGING_MULTIPOINT_TO_OFF, AlertMessageType.DISCONNECT_CAUSED_BY_CHANGING_MULTIPOINT_TO_OFF);
    BATTERY_CONSUMPTION_INCREASE_DUE_TO_EQ_AND_UPSCALING = new AlertMsgType("BATTERY_CONSUMPTION_INCREASE_DUE_TO_EQ_AND_UPSCALING", 8, AlertMessageType.BATTERY_CONSUMPTION_INCREASE_DUE_TO_EQ_AND_UPSCALING, AlertMessageType.BATTERY_CONSUMPTION_INCREASE_DUE_TO_EQ_AND_UPSCALING);
    CAUTION_FOR_DUAL_ASSIGNMENT_OF_PLAYBACK_CONTROL = new AlertMsgType("CAUTION_FOR_DUAL_ASSIGNMENT_OF_PLAYBACK_CONTROL", 9, null, AlertMessageType.CAUTION_FOR_DUAL_ASSIGNMENT_OF_PLAYBACK_CONTROL);
    CAUTION_FOR_DISABLE_TOUCH_SENSOR_PANEL = new AlertMsgType("CAUTION_FOR_DISABLE_TOUCH_SENSOR_PANEL", 10, null, AlertMessageType.CAUTION_FOR_DISABLE_TOUCH_SENSOR_PANEL);
    CAUTION_FOR_DISABLE_TOUCH_SENSOR_PANEL_AND_RECONNECTION = new AlertMsgType("CAUTION_FOR_DISABLE_TOUCH_SENSOR_PANEL_AND_RECONNECTION", 11, null, AlertMessageType.CAUTION_FOR_DISABLE_TOUCH_SENSOR_PANEL_AND_RECONNECTION);
    CAUTION_FOR_ABLE_TOUCH_SENSOR_PANEL = new AlertMsgType("CAUTION_FOR_ABLE_TOUCH_SENSOR_PANEL", 12, null, AlertMessageType.CAUTION_FOR_ABLE_TOUCH_SENSOR_PANEL);
    CAUTION_FOR_ABLE_TOUCH_SENSOR_PANEL_AND_RECONNECTION = new AlertMsgType("CAUTION_FOR_ABLE_TOUCH_SENSOR_PANEL_AND_RECONNECTION", 13, null, AlertMessageType.CAUTION_FOR_ABLE_TOUCH_SENSOR_PANEL_AND_RECONNECTION);
    CAUTION_FOR_DISABLE_VOICE_ASSISTANT_ASSIGNABLE_BUTTON = new AlertMsgType("CAUTION_FOR_DISABLE_VOICE_ASSISTANT_ASSIGNABLE_BUTTON", 14, null, AlertMessageType.CAUTION_FOR_DISABLE_VOICE_ASSISTANT_ASSIGNABLE_BUTTON);
    CAUTION_FOR_DISABLE_VOICE_ASSISTANT_ASSIGNABLE_SENSOR = new AlertMsgType("CAUTION_FOR_DISABLE_VOICE_ASSISTANT_ASSIGNABLE_SENSOR", 15, null, AlertMessageType.CAUTION_FOR_DISABLE_VOICE_ASSISTANT_ASSIGNABLE_SENSOR);
    CAUTION_FOR_DISABLE_VOICE_ASSISTANT_AND_RECONNECTION_ASSIGNABLE_BUTTON = new AlertMsgType("CAUTION_FOR_DISABLE_VOICE_ASSISTANT_AND_RECONNECTION_ASSIGNABLE_BUTTON", 16, null, AlertMessageType.CAUTION_FOR_DISABLE_VOICE_ASSISTANT_AND_RECONNECTION_ASSIGNABLE_BUTTON);
    CAUTION_FOR_DISABLE_VOICE_ASSISTANT_AND_RECONNECTION_ASSIGNABLE_SENSOR = new AlertMsgType("CAUTION_FOR_DISABLE_VOICE_ASSISTANT_AND_RECONNECTION_ASSIGNABLE_SENSOR", 17, null, AlertMessageType.CAUTION_FOR_DISABLE_VOICE_ASSISTANT_AND_RECONNECTION_ASSIGNABLE_SENSOR);
    CAUTION_FOR_ABLE_VOICE_ASSISTANT_ASSIGNABLE_BUTTON = new AlertMsgType("CAUTION_FOR_ABLE_VOICE_ASSISTANT_ASSIGNABLE_BUTTON", 18, null, AlertMessageType.CAUTION_FOR_ABLE_VOICE_ASSISTANT_ASSIGNABLE_BUTTON);
    CAUTION_FOR_ABLE_VOICE_ASSISTANT_ASSIGNABLE_SENSOR = new AlertMsgType("CAUTION_FOR_ABLE_VOICE_ASSISTANT_ASSIGNABLE_SENSOR", 19, null, AlertMessageType.CAUTION_FOR_ABLE_VOICE_ASSISTANT_ASSIGNABLE_SENSOR);
    CAUTION_FOR_ABLE_VOICE_ASSISTANT_AND_RECONNECTION_ASSIGNABLE_BUTTON = new AlertMsgType("CAUTION_FOR_ABLE_VOICE_ASSISTANT_AND_RECONNECTION_ASSIGNABLE_BUTTON", 20, null, AlertMessageType.CAUTION_FOR_ABLE_VOICE_ASSISTANT_AND_RECONNECTION_ASSIGNABLE_BUTTON);
    CAUTION_FOR_ABLE_VOICE_ASSISTANT_AND_RECONNECTION_ASSIGNABLE_SENSOR = new AlertMsgType("CAUTION_FOR_ABLE_VOICE_ASSISTANT_AND_RECONNECTION_ASSIGNABLE_SENSOR", 21, null, AlertMessageType.CAUTION_FOR_ABLE_VOICE_ASSISTANT_AND_RECONNECTION_ASSIGNABLE_SENSOR);
    CAUTION_FOR_CHANGE_VOICE_ASSISTANT = new AlertMsgType("CAUTION_FOR_CHANGE_VOICE_ASSISTANT", 22, null, AlertMessageType.CAUTION_FOR_CHANGE_VOICE_ASSISTANT);
    CAUTION_FOR_CHANGE_VOICE_ASSISTANT_TOUCH_SENSOR_PANEL = new AlertMsgType("CAUTION_FOR_CHANGE_VOICE_ASSISTANT_TOUCH_SENSOR_PANEL", 23, null, AlertMessageType.CAUTION_FOR_CHANGE_VOICE_ASSISTANT_TOUCH_SENSOR_PANEL);
    CAUTION_FOR_CHANGE_VOICE_ASSISTANT_TOUCH_SENSOR_PANEL_MOBILE_OR_SIRI = new AlertMsgType("CAUTION_FOR_CHANGE_VOICE_ASSISTANT_TOUCH_SENSOR_PANEL_MOBILE_OR_SIRI", 24, null, AlertMessageType.CAUTION_FOR_CHANGE_VOICE_ASSISTANT_TOUCH_SENSOR_PANEL_MOBILE_OR_SIRI);
    FOREGROUND_CAUTION_NEED_DISCONNECTION_FOR_ENABLING_WAKE_WORD = new AlertMsgType("FOREGROUND_CAUTION_NEED_DISCONNECTION_FOR_ENABLING_WAKE_WORD", 25, null, AlertMessageType.FOREGROUND_CAUTION_NEED_DISCONNECTION_FOR_ENABLING_WAKE_WORD);
    FOREGROUND_CAUTION_WAKE_WORD_IS_AVAILABLE_ONLY_IN_USE_OF_ALEXA = new AlertMsgType("FOREGROUND_CAUTION_WAKE_WORD_IS_AVAILABLE_ONLY_IN_USE_OF_ALEXA", 26, null, AlertMessageType.FOREGROUND_CAUTION_WAKE_WORD_IS_AVAILABLE_ONLY_IN_USE_OF_ALEXA);
    OUT_OF_RANGE = new AlertMsgType("OUT_OF_RANGE", 27, null, AlertMessageType.OUT_OF_RANGE);
    a = new AlertMsgType[] { 
        NO_USE, DISCONNECT_CAUSED_BY_CONNECTION_MODE_CHANGE, DISCONNECT_CAUSED_BY_CHANGING_KEY_ASSIGN, NEED_DISCONNECTION_FOR_UPDATING_FIRMWARE, GOOGLE_ASSISTANT_IS_NOW_AVAILABLE, DUAL_ASSIGN_OF_VOICE_ASSISTANT_IS_UNAVAILABLE, DISCONNECT_CAUSED_BY_CHANGING_MULTIPOINT_TO_ON, DISCONNECT_CAUSED_BY_CHANGING_MULTIPOINT_TO_OFF, BATTERY_CONSUMPTION_INCREASE_DUE_TO_EQ_AND_UPSCALING, CAUTION_FOR_DUAL_ASSIGNMENT_OF_PLAYBACK_CONTROL, 
        CAUTION_FOR_DISABLE_TOUCH_SENSOR_PANEL, CAUTION_FOR_DISABLE_TOUCH_SENSOR_PANEL_AND_RECONNECTION, CAUTION_FOR_ABLE_TOUCH_SENSOR_PANEL, CAUTION_FOR_ABLE_TOUCH_SENSOR_PANEL_AND_RECONNECTION, CAUTION_FOR_DISABLE_VOICE_ASSISTANT_ASSIGNABLE_BUTTON, CAUTION_FOR_DISABLE_VOICE_ASSISTANT_ASSIGNABLE_SENSOR, CAUTION_FOR_DISABLE_VOICE_ASSISTANT_AND_RECONNECTION_ASSIGNABLE_BUTTON, CAUTION_FOR_DISABLE_VOICE_ASSISTANT_AND_RECONNECTION_ASSIGNABLE_SENSOR, CAUTION_FOR_ABLE_VOICE_ASSISTANT_ASSIGNABLE_BUTTON, CAUTION_FOR_ABLE_VOICE_ASSISTANT_ASSIGNABLE_SENSOR, 
        CAUTION_FOR_ABLE_VOICE_ASSISTANT_AND_RECONNECTION_ASSIGNABLE_BUTTON, CAUTION_FOR_ABLE_VOICE_ASSISTANT_AND_RECONNECTION_ASSIGNABLE_SENSOR, CAUTION_FOR_CHANGE_VOICE_ASSISTANT, CAUTION_FOR_CHANGE_VOICE_ASSISTANT_TOUCH_SENSOR_PANEL, CAUTION_FOR_CHANGE_VOICE_ASSISTANT_TOUCH_SENSOR_PANEL_MOBILE_OR_SIRI, FOREGROUND_CAUTION_NEED_DISCONNECTION_FOR_ENABLING_WAKE_WORD, FOREGROUND_CAUTION_WAKE_WORD_IS_AVAILABLE_ONLY_IN_USE_OF_ALEXA, OUT_OF_RANGE };
  }
  
  AlertMsgType(AlertMessageType paramAlertMessageType, AlertMessageType paramAlertMessageType1) {
    this.mTypeTableSet1 = paramAlertMessageType;
    this.mTypeTableSet2 = paramAlertMessageType1;
  }
  
  public static AlertMsgType fromTableSet1(AlertMessageType paramAlertMessageType) {
    for (AlertMsgType alertMsgType : values()) {
      if (alertMsgType.mTypeTableSet1 == paramAlertMessageType)
        return alertMsgType; 
    } 
    return NO_USE;
  }
  
  public static AlertMsgType fromTableSet2(AlertMessageType paramAlertMessageType) {
    for (AlertMsgType alertMsgType : values()) {
      if (alertMsgType.mTypeTableSet2 == paramAlertMessageType)
        return alertMsgType; 
    } 
    return NO_USE;
  }
  
  public AlertMessageType tableSet1() {
    return this.mTypeTableSet1;
  }
  
  public AlertMessageType tableSet2() {
    return this.mTypeTableSet2;
  }
}


/* Location:              /home/egaebel/Programs/sony-headphones-hack/base-dex2jar.jar!/com/sony/songpal/mdr/j2objc/tandem/features/alert/AlertMsgType.class
 * Java compiler version: 6 (50.0)
 * JD-Core Version:       1.1.3
 */